package.json
Fixes #12603 
Related PR: brave/brave-core#7100
=> Upgraded from Chromium 86.0.4240.158 to Chromium 86.0.4240.193.

CHANGELOG_ANDROID.md
=> Release notes for 1.16.x Release #5

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.16.x Release #5

package.json
Fixes #12645
Related PR: brave/brave-core#7123
=> Upgraded from Chromium 86.0.4240.193 to Chromium 86.0.4240.198.

CHANGELOG_ANDROID.md
=> Release notes for 1.16.x Release #6

package.json
Fixes #12676 
Related PR: brave/brave-core#7136
=> Upgraded from Chromium 87.0.4280.49 to Chromium 87.0.4280.60.

package.json
Fixes #12676
Related PR: brave/brave-core#7142
Uplift from #12677 
=> Upgraded from Chromium 87.0.4280.49 to Chromium 87.0.4280.60 (1.18.x).

package.json
Fixes #12676
Related PR: brave/brave-core#7143
Uplift from #12677
=> Upgraded from Chromium 87.0.4280.49 to Chromium 87.0.4280.60 (1.17.x).

.github/PULL_REQUEST_TEMPLATE.md
Fixes https://github.com/brave/brave-browser/issues/12691
PR to brave-core: https://github.com/brave/brave-core/pull/7140
=> 12691: Improve the PR checklist.

package.json
Fixes #12727
Related PR: brave/brave-core#7158
=> Upgraded from Chromium 87.0.4280.60 to Chromium 87.0.4280.63.

package.json
Fixes #12741
Related PR: brave/brave-core#7167
=> Upgraded from Chromium 87.0.4280.63 to Chromium 87.0.4280.66.

package.json
Fixes #12727
Fixes #12741
Related PR: brave/brave-core#7181
Uplift from #12728
Uplift from #12742
=> Upgraded from Chromium 87.0.4280.60 to Chromium 87.0.4280.66 (1.18.x).

package.json
Fixes #12727
Fixes #12741
Related PR: brave/brave-core#7182
Uplift from #12728
Uplift from #12742
=> Upgraded from Chromium 87.0.4280.60 to Chromium 87.0.4280.66 (1.17.x).

package.json
Fixes #12793 
Related PR: brave/brave-core#7198
=> Upgraded from Chromium 87.0.4280.66 to Chromium 87.0.4280.67.

package.json
Fixes #12793
Related PR: brave/brave-core#7205
Uplift from #12794
=> Upgraded from Chromium 87.0.4280.66 to Chromium 87.0.4280.67 (1.17.x).

package.json
Fixes #12793
Related PR: brave/brave-core#7204
Uplift from #12794 
=> Upgraded from Chromium 87.0.4280.66 to Chromium 87.0.4280.67 (1.18.x).

CHANGELOG_ANDROID.md
=> Release notes for 1.17.x - Release #1

CHANGELOG_ANDROID.md
=> Release notes for 1.17.x - Release #3

CHANGELOG_ANDROID.md
=> Release notes for 1.17.x - Release #3 (Fix)

package.json
Fixes #13006
Related PR: brave/brave-core#7318
=> Upgraded from Chromium 87.0.4280.67 to Chromium 87.0.4280.88.

package.json
Fixes #13006
Related PR: brave/brave-core#7322
Uplift from #13007 
=> Upgraded from Chromium 87.0.4280.67 to Chromium 87.0.4280.88 (1.19.x).

package.json
Fixes #13006
Related PR: brave/brave-core#7323
Uplift from #13007 
=> Upgraded from Chromium 87.0.4280.67 to Chromium 87.0.4280.88 (1.18.x).

package.json
Fixes #13006
Related PR: brave/brave-core#7324
Uplift from #13007
=> Upgraded from Chromium 87.0.4280.67 to Chromium 87.0.4280.88 (1.17.x).

CHANGELOG_DESKTOP.md
=> Release notes for 1.17.x - Release #4

package.json
Fixes #13081 
Related PR: brave/brave-core#7375
=> Upgraded from Chromium 87.0.4280.88 to Chromium 87.0.4280.101.

package.json
Fixes #12331 
Related PR: brave/brave-core#6957
=> Upgrade from Chromium 87 to Chromium 88.

package.json
Fixes #13081
Related PR: brave/brave-core#7384
Uplift from #13082 
=> Upgraded from Chromium 87.0.4280.88 to Chromium 87.0.4280.101 (1.18.x).

package.json
Fixes #13081
Related PR: brave/brave-core#7383
Uplift from #13082 
=> Upgraded from Chromium 87.0.4280.88 to Chromium 87.0.4280.101 (1.19.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.18.x Release #2

CHANGELOG_ANDROID.md
=> [Android] Release notes for 1.18.x Release #2

package.json
Resolves #13281
Related PR: brave/brave-core#7491
=> Upgraded from Chromium 88.0.4315.5 to Chromium 88.0.4315.7.

CHANGELOG_DESKTOP.md
=> Release notes for 1.18.x Release #3

CHANGELOG_ANDROID.md
=> Release notes for Release #3 (Release Channel) 

package.json
Fixes #13103
Related PR: brave/brave-core#7408
=> Upgrade from Chromium 88.0.4315.5 to Chromium 88.0.4324.51.

package.json
Fixes #13399
Related PR: brave/brave-core#7530
=> Upgrade from Chromium 87.0.4280.101 to Chromium 87.0.4280.141 (1.19.x).

package.json
Fixes #13399
Related PR: brave/brave-core#7539
Uplift from #13400 
=> Upgrade from Chromium 87.0.4280.101 to Chromium 87.0.4280.141 (1.18.x).

package.json
Fixes #13427
Related PR: brave/brave-core#7544
=> Upgraded from Chromium 88.0.4324.51 to Chromium 88.0.4324.79.

CHANGELOG_DESKTOP.md
=> Release notes for 1.18.x Release #4

package.json
Fixes #12331
Fixes #13281
Fixes #13103
Fixes #13427
Related PR: brave/brave-core#7518
Uplift from #12332
Uplift from #13282
Uplift from #13143
Uplift from #13429
=> Upgrade from Chromium 87 to Chromium 88.0.4324.79 (1.19.x).

package.json
Fixes #13559
Related PR: brave/brave-core#7592
=> Upgraded from Chromium 88.0.4324.79 to Chromium 88.0.4324.87.

package.json
Fixes #13559
Related PR: brave/brave-core#7605
Uplift from #13561 
=> Upgraded from Chromium 88.0.4324.79 to Chromium 88.0.4324.87 (1.20.x).

package.json
Fixes #13559
Related PR: brave/brave-core#7606
Uplift from #13561
=> Upgraded from Chromium 88.0.4324.79 to Chromium 88.0.4324.87 (1.19.x).

package.json
Fixes #13602
Related PR: brave/brave-core#7612
=> Upgraded from Chromium 88.0.4324.87 to Chromium 88.0.4324.89.

package.json
Fixes #13602
Related PR: brave/brave-core#7629
Uplift from #13603 
=> Upgraded from Chromium 88.0.4324.87 to Chromium 88.0.4324.89 (1.20.x).

package.json
Fixes #13602
Related PR: brave/brave-core#7630
Uplift from #13603
=> Upgraded from Chromium 88.0.4324.87 to Chromium 88.0.4324.89 (1.19.x).

package.json
Fixes #13637
Related PR: brave/brave-core#7643
=> Upgrade from Chromium 88.0.4324.89 to Chromium 88.0.4324.96.

package.json
Fixes #13637
Related PR: brave/brave-core#7649
Uplift from #13640 
=> Upgrade from Chromium 88.0.4324.89 to Chromium 88.0.4324.96 (1.20.x).

package.json
Fixes #13637
Related PR: brave/brave-core#7648
Uplift from #13640  
=> Upgrade from Chromium 88.0.4324.89 to Chromium 88.0.4324.96 (1.19.x).

CHANGELOG_DESKTOP.md
=> Release notes 1.19.x Fix

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/13663
N/A
=> Release notes for 1.19.x

CHANGELOG_ANDROID.md
=> Release notes for 1.19.x - Release #2

package.json
Fixes #13900
Related PR: brave/brave-core#7790
=> Upgraded from Chromium 88.0.4324.96 to Chromium 88.0.4324.146.

package.json
Fixes #13900
Related PR: brave/brave-core#7795
Uplift from #13907
=> Upgraded from Chromium 88.0.4324.96 to Chromium 88.0.4324.146 (1.19.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.19.x Release #3

CHANGELOG_DESKTOP.md
=> Update Desktop Release Notes for 1.19.x Release #3

CHANGELOG_ANDROID.md
=> Release notes for 1.19.x Release #4

package.json
Fixes #13969
Related PR: brave/brave-core#7835
=> Upgrade from Chromium 88.0.4324.146 to Chromium 88.0.4324.152.

package.json
Fixes #13969
Related PR: brave/brave-core#7844
Uplift from #13979
=> Upgrade from Chromium 88.0.4324.146 to Chromium 88.0.4324.152 (1.19.x).

package.json
Fixes #13969
Related PR: brave/brave-core#7843
Uplift from #13979 
=> Upgrade from Chromium 88.0.4324.146 to Chromium 88.0.4324.152 (1.20.x).

package.json
Fixes #13969
Related PR: brave/brave-core#7842
Uplift from #13979  
=> Upgrade from Chromium 88.0.4324.146 to Chromium 88.0.4324.152 (1.21.x).

package.json
Fixes #13238
Related PR: brave/brave-core#7460
=> Upgrade from Chromium 88 to Chromium 89.

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.19.x Release #5

CHANGELOG_ANDROID.md
=> [Android] Release notes for 1.19.x Release #5

.github/PULL_REQUEST_TEMPLATE.md
For https://github.com/brave/brave-browser/issues/13962
=> Update PR template suggestion for auto-closing issues

Jenkinsfile
Resolves https://github.com/brave/devops/issues/4415
=> Add clean lock file before checkout

Jenkinsfile
Uplift of https://github.com/brave/brave-browser/pull/13993
=> lock fix for ci pipeline (1.21.x)

Jenkinsfile
Uplift of https://github.com/brave/brave-browser/pull/13993
=> lock fix for ci pipeline (1.20.x)

package.json
Fixes #14112 
Related PR: brave/brave-core#7936
=> Upgrade from Chromium 89.0.4389.40 to Chromium 89.0.4389.48

package.json
Fixes #14187
Related PR: brave/brave-core#7976
=> Upgrade from Chromium 88.0.4324.152 to Chromium 88.0.4324.182

package.json
Fixes #14187
Related PR: brave/brave-core#7981
Uplift from #14190
=> Upgrade from Chromium 88.0.4324.152 to Chromium 88.0.4324.182 (1.20.x).

package.json
Fixes #14227
Related PR: brave/brave-core#7988
=> Upgrade from Chromium 89.0.4389.48 to Chromium 89.0.4389.58

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.20.x Release 2

CHANGELOG_ANDROID.md
=> Release notes for 1.20.x Release #2

package.json
Fixes #14302
Related PR: brave/brave-core#8037
=> Upgrade from Chromium 88.0.4324.182 to Chromium 88.0.4324.192 (1.20.x).

package.json
Fixes #13238
Fixes #14112
Fixes #14227
Related PR: brave/brave-core#8009
Uplift from #13221
Uplift from #14113
Uplift from #14230
=> Upgrade from Chromium 88 to Chromium 89 (1.21.x).

.github/PULL_REQUEST_TEMPLATE.md
Same change as https://github.com/brave/brave-core/pull/8018.
=> Make the security review step clearer

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.20.x Release 3

package.json
Fixes #14353
Related PR: brave/brave-core#8070
=> Upgrade from Chromium 89.0.4389.58 to Chromium 89.0.4389.69

package.json
Fixes #14353
Related PR: brave/brave-core#8083
Uplift from #14354 
=> Upgrade from Chromium 89.0.4389.58 to Chromium 89.0.4389.69 (1.22.x).

package.json
Fixes #14353
Related PR: brave/brave-core#8084
Uplift from #14354
=> Upgrade from Chromium 89.0.4389.58 to Chromium 89.0.4389.69 (1.21.x).

package.json
Fixes #14412
Related PR: brave/brave-core#8095
=> Upgrade from Chromium 89.0.4389.69 to Chromium 89.0.4389.72

package.json
Fixes #14412
Related PR: brave/brave-core#8100
Uplift from #14416
=> Upgrade from Chromium 89.0.4389.69 to Chromium 89.0.4389.72 (1.22.x).

package.json
Fixes #14412
Related PR: brave/brave-core#8099
Uplift from #14416
=> Upgrade from Chromium 89.0.4389.69 to Chromium 89.0.4389.72 (1.21.x).

CHANGELOG_ANDROID.md
=> Release notes for 1.21.x

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.21.x Release #2

CHANGELOG_ANDROID.md, CHANGELOG_DESKTOP.md
=> Release notes for 1.21.x Release #2

package.json
Fixes #14506
Related PR: brave/brave-core#8155
=> Upgrade from Chromium 89.0.4389.72 to Chromium 89.0.4389.82

package.json
Fixes #14579
Related PR: brave/brave-core#8186
=> Upgrade from Chromium 89.0.4389.82 to Chromium 89.0.4389.86.

package.json
Fixes #14506
Related PR: brave/brave-core#8182
Uplift from #14507
=> Upgrade from Chromium 89.0.4389.72 to Chromium 89.0.4389.82 (1.22.x).

package.json
Fixes #14506
Related PR: brave/brave-core#8183
Uplift from #14507
=> Upgrade from Chromium 89.0.4389.72 to Chromium 89.0.4389.82 (1.21.x).

package.json
Fixes #14579
Related PR: brave/brave-core#8189
Uplift from #14580 
=> Upgrade from Chromium 89.0.4389.82 to Chromium 89.0.4389.86 (1.22.x).

package.json
Fixes #14579
Related PR: brave/brave-core#8190
Uplift from #14580
=> Upgrade from Chromium 89.0.4389.82 to Chromium 89.0.4389.86 (1.21.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.21.x Release #3

CHANGELOG_ANDROID.md
=> Release notes for 1.21.x Release #3

package.json
Fixes #14694
Related PR: brave/brave-core#8238
=> Upgrade from Chromium 89.0.4389.86 to Chromium 89.0.4389.90

package.json
Fixes #14694
Related PR: brave/brave-core#8249
Uplift from #14695
=> Upgrade from Chromium 89.0.4389.86 to Chromium 89.0.4389.90 (1.22.x).

package.json
Fixes #14694
Related PR: brave/brave-core#8250
Uplift from #14695 
=> Upgrade from Chromium 89.0.4389.86 to Chromium 89.0.4389.90 (1.21.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.21.x Release #4

CHANGELOG_ANDROID.md
=> Release notes for 1.21.x Release #4

package.json
Resolves #13205
Basically sorted all package.json keys and scripts using https://www.npmjs.com/package/sort-package-json-scripts to make it easier to navigate.
=> Sort package.json keys and scripts

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.22.x Release #1

package.json
Fixes #14891
Related PR: brave/brave-core#8329 
=> Upgrade from Chromium 89.0.4389.90 to Chromium 89.0.4389.105

CHANGELOG_DESKTOP.md
=> Release notes for 1.22.x Release #2

package.json
Fixes #14037
Related PR: brave/brave-core#7866
=> Upgrade from Chromium 89 to Chromium 90.

package.json
Fixes #14891
Related PR: brave/brave-core#8331
Uplift from #14892 
=> Upgrade from Chromium 89.0.4389.90 to Chromium 89.0.4389.105 (1.23.x).

package.json
Fixes #14891
Related PR: brave/brave-core#8332
Uplift from #14892
=> Upgrade from Chromium 89.0.4389.90 to Chromium 89.0.4389.105 (1.22.x).

CHANGELOG_ANDROID.md
=> Release notes for 1.22.x Release #3

CHANGELOG_DESKTOP.md
=> Release notes for 1.22.x Release #4

package.json
Fixes brave/brave-browser#14931
Related PR: brave/brave-core#8354
=> Upgrade from Chromium 90.0.4430.30 to Chromium 90.0.4430.41.

README.md
Resolves https://github.com/brave/brave-browser/issues/14966
=> Update URL for adblock-rust-ffi

package.json
Fixes brave/brave-browser#15030
Related PR: brave/brave-core#8393
=> Upgrade from Chromium 89.0.4389.105 to Chromium 89.0.4389.114

package.json
Fixes #15030
Related PR: brave/brave-core#8398
Uplift from #15031 
=> Upgrade from Chromium 89.0.4389.105 to Chromium 89.0.4389.114 (1.22.x).

Jenkinsfile
For https://github.com/brave/devops/issues/4742
=> CI pipeline skip improvements

CHANGELOG_DESKTOP.md
=> Release notes for 1.22.x Release #5

package.json
Fixes brave/brave-browser#15052
Related PR: brave/brave-core#8405
=> Upgrade from Chromium 90.0.4430.41 to Chromium 90.0.4430.51

package.json
Fixes brave/brave-browser#14037
Fixes brave/brave-browser#14931
Fixes brave/brave-browser#15052
Related PR: brave/brave-core#8440
Uplift from #14038
Uplift from #14934
Uplift from #15054
=> Upgrade from Chromium 89 to Chromium 90 (1.23.x).

package.json
Fixes brave/brave-browser#15181
Related PR: brave/brave-core#8472
=> Upgrade from Chromium 90.0.4430.51 to Chromium 90.0.4430.61

package.json
Fixes #15181
Related PR: brave/brave-core#8486
Uplift from #15182 
=> Upgrade from Chromium 90.0.4430.51 to Chromium 90.0.4430.61 (1.24.x).

package.json
Fixes #15181
Related PR: brave/brave-core#8485
Uplift from #15182 
=> Upgrade from Chromium 90.0.4430.51 to Chromium 90.0.4430.61 (1.23.x).

package.json
Fixes #15239
Related PR: brave/brave-core#8509
=> Upgrade from Chromium 90.0.4430.61 to Chromium 90.0.4430.70.

package.json
Fixes #15239
Related PR: brave/brave-core#8517
Uplift from #15240
=> Upgrade from Chromium 90.0.4430.61 to Chromium 90.0.4430.70 (1.23.x).

package.json
Fixes #15239
Related PR: brave/brave-core#8516
Uplift from #15240  
=> Upgrade from Chromium 90.0.4430.61 to Chromium 90.0.4430.70 (1.24.x).

CHANGELOG_DESKTOP.md
=> Release notes for 1.22.x Release #6

package.json
Fixes #15299
Related PR: brave/brave-core#8540
=> Upgrade from Chromium 90.0.4430.70 to Chromium 90.0.4430.72

package.json
Fixes #15299
Related PR: brave/brave-core#8541
Uplift from #15300 
=> Upgrade from Chromium 90.0.4430.70 to Chromium 90.0.4430.72 (1.24.x).

package.json
Fixes #15299
Related PR: brave/brave-core#8542
Uplift from #15300
=> Upgrade from Chromium 90.0.4430.70 to Chromium 90.0.4430.72 (1.23.x).

package.json
Removes unused GitHub upload target. 
=> removed unused npm target

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.23.x Release #1

package.json
Fixes #15397
Related PR: brave/brave-core#8579
=> Upgrade from Chromium 90.0.4430.72 to Chromium 90.0.4430.85

CHANGELOG_ANDROID.md
=> Release notes 1.23

CHANGELOG_ANDROID.md
=> Release notes for 1.23.x Fix

package.json
Fixes #15397
Related PR: brave/brave-core#8583
Uplift from #15398 
=> Upgrade from Chromium 90.0.4430.72 to Chromium 90.0.4430.85 (1.24.x).

package.json
Fixes #15397
Related PR: brave/brave-core#8584
Uplift from #15398
=> Upgrade from Chromium 90.0.4430.72 to Chromium 90.0.4430.85 (1.23.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.23.x Release #2

CHANGELOG_ANDROID.md
=> Release notes for 1.23.x Release #3

CHANGELOG_ANDROID.md
=> Release notes for 1.23.x Release #3 Fix

package.json
Fixes #15502 
Related PR: brave/brave-core#8644
=> Upgrade from Chromium 90.0.4430.85 to Chromium 90.0.4430.93.

package.json
Fixes #15502
Related PR: brave/brave-core#8652
Uplift from #15503 
=> Upgrade from Chromium 90.0.4430.85 to Chromium 90.0.4430.93 (1.23.x).

package.json
Fixes #15502
Related PR: brave/brave-core#8651
Uplift from #15503 
=> Upgrade from Chromium 90.0.4430.85 to Chromium 90.0.4430.93 (1.24.x).

CHANGELOG_DESKTOP.md
=> Release notes for 1.23.x Release #4

CHANGELOG_ANDROID.md
=> Release notes for 1.23.x Release #5

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.24.x Release #1

package.json
Fixes #15641
Related PR: brave/brave-core#8729
=> Upgrade from Chromium 91.0.4472.19 to Chromium 91.0.4472.38.

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.24.x Release #2

package.json
Fixes #15725
Related PR: brave/brave-core#8766
=> Upgrade from Chromium 90.0.4430.93 to Chromium 90.0.4430.212 (1.25.x).

CHANGELOG_ANDROID.md
=> Release notes for 1.24.x - Release #2

package.json
Fixes #15725
Related PR: brave/brave-core#8780
Uplift from #15727
=> Upgrade from Chromium 90.0.4430.93 to Chromium 90.0.4430.212 (1.24.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.24.x Release #3

CHANGELOG_ANDROID.md
=> Release notes for 1.24.x Release #3

package.json
Fixes #15800
Related PR: brave/brave-core#8793
=> Upgrade from Chromium 91.0.4472.38 to Chromium 91.0.4472.57

.github/CODEOWNERS
These files were moved to brave-core and I've filed https://github.com/brave/brave-core/pull/8835 to move the CODEOWNERS there.
=> Remove files moved to brave-core.

package.json
Fixes brave/brave-browser#14848
Related PR: brave/brave-core#8840
Uplift from brave/brave-browser#14849
=> Upgrade from Chromium 90 to Chromium 91 (1.25.x).

package.json
Fixes #15973
Related PR: brave/brave-core#8870
=> Upgrade from Chromium 91.0.4472.57 to Chromium 91.0.4472.70.

CHANGELOG_ANDROID.md
=> [Android] Release notes for 1.24.x Release #4

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.24.x Release #4

package.json
Fixes #15973
Related PR: brave/brave-core#8875
Uplift from #15980 
=> Upgrade from Chromium 91.0.4472.57 to Chromium 91.0.4472.70 (1.26.x).

package.json
Fixes #15973
Related PR: brave/brave-core#8876
Uplift from #15980
=> Upgrade from Chromium 91.0.4472.57 to Chromium 91.0.4472.70 (1.25.x).

package.json
Fixes #16054
Related PR: brave/brave-core#8916
=> Upgrade from Chromium 91.0.4472.70 to Chromium 91.0.4472.77

package.json
Fixes #16054
Related PR: brave/brave-core#8924
Uplift from #16055
=> Upgrade from Chromium 91.0.4472.70 to Chromium 91.0.4472.77 (1.25.x).

package.json
Fixes #16054
Related PR: brave/brave-core#8925
Uplift from #16055
=> Upgrade from Chromium 91.0.4472.70 to Chromium 91.0.4472.77 (1.26.x).

CHANGELOG_ANDROID.md
=> Release notes for 1.25.x Release #2

CHANGELOG_DESKTOP.md
=> Release notes for 1.25.x Release #3

.github/PULL_REQUEST_TEMPLATE.md
Resolves https://github.com/brave/brave-browser/issues/15203
=> Update handbook links to point to the public wiki instead

package.json
Fixes #16243
Related PR: brave/brave-core#9019
=> Upgrade from Chromium 91.0.4472.77 to Chromium 91.0.4472.88.

package.json
Fixes #16243
Related PR: brave/brave-core#9025
Uplift from #16245 
=> Upgrade from Chromium 91.0.4472.77 to Chromium 91.0.4472.88 (1.26.x).

package.json
Fixes #16243
Related PR: brave/brave-core#9026
Uplift from #16245 
=> Upgrade from Chromium 91.0.4472.77 to Chromium 91.0.4472.88 (1.25.x).

CHANGELOG_ANDROID.md
=> Release notes for 1.25.x - Release #4

package.json
Fixes #16314
Related PR: brave/brave-core#9066
=> Upgrade from Chromium 91.0.4472.88 to Chromium 91.0.4472.101

Jenkinsfile
Part of https://github.com/brave/devops/issues/5204
To be merged after https://github.com/brave/devops/pull/5205 along with https://github.com/brave/brave-core/pull/9076 
=> Enabled on-demand audit-deps in PRs.

CHANGELOG_ANDROID.md
=> Release notes 1.25.71 Fix

package.json
Fixes #16314
Related PR: brave/brave-core#9070
Uplift from #16320
=> Upgrade from Chromium 91.0.4472.88 to Chromium 91.0.4472.101 (1.26.x).

package.json
Fixes #16314
Related PR: brave/brave-core#9071
Uplift from #16320
=> Upgrade from Chromium 91.0.4472.88 to Chromium 91.0.4472.101 (1.25.x).

CHANGELOG_DESKTOP.md
=> Release notes for 1.25.72

CHANGELOG_DESKTOP.md
=> Release notes for 1.25.x - Release #5 addition

CHANGELOG_ANDROID.md
=> Release notes for 1.25.x Release #5

package.json
Fixes brave/brave-browser#16422
Related PR: brave/brave-core#9126
=> Upgrade from Chromium 91.0.4472.101 to Chromium 91.0.4472.106

package.json
Fixes #16422
Related PR: brave/brave-core#9139
Uplift from #16424  
=> Upgrade from Chromium 91.0.4472.101 to Chromium 91.0.4472.106 (1.26.x).

package.json
Fixes #16422
Related PR: brave/brave-core#9140
Uplift from #16424 
=> Upgrade from Chromium 91.0.4472.101 to Chromium 91.0.4472.106 (1.25.x).

CHANGELOG_DESKTOP.md
=> Release notes for 1.25.x - Release #6

CHANGELOG_ANDROID.md
=> Release notes for `1.25.x - Release #6`

package.json
Fixes brave/brave-browser#16489
Related PR: brave/brave-core#9166
=> Upgrade from Chromium 91.0.4472.106 to Chromium 91.0.4472.114

package.json
Fixes #16576
Related PR: brave/brave-core#9222
=> Upgrade from Chromium 91.0.4472.114 to Chromium 91.0.4472.120

CHANGELOG_ANDROID.md
=> Release notes for 1.26.x

package.json
Fixes #16576
Related PR: brave/brave-core#9227
Uplift from #16577 
=> Upgrade from Chromium 91.0.4472.114 to Chromium 91.0.4472.120 (1.27.x).

package.json
Fixes #16576
Related PR: brave/brave-core#9228
Uplift from #16577
=> Upgrade from Chromium 91.0.4472.114 to Chromium 91.0.4472.120 (1.26.x).

package.json
Fixes #16600
Related PR: brave/brave-core#9239
=> Upgrade from Chromium 91.0.4472.120 to Chromium 91.0.4472.124

package.json
Fixes #16600
Related PR: brave/brave-core#9244
Uplift from #16601 
=> Upgrade from Chromium 91.0.4472.120 to Chromium 91.0.4472.124 (1.27.x).

package.json
Fixes #16600
Related PR: brave/brave-core#9245
Uplift from #16601
=> Upgrade from Chromium 91.0.4472.120 to Chromium 91.0.4472.124 (1.26.x).

CHANGELOG_ANDROID.md
=> Release notes for 1.26.x - Release #2

package.json
Fixes brave/brave-browser#15316
Related PR: brave/brave-core#8545
=> Upgrade from Chromium 91 to Chromium 92

CHANGELOG_DESKTOP.md
=> Release notes for `1.26.x - Release #3`

package.json
Fixes brave/brave-browser#16726
Related PR: brave/brave-core#9303
=> Updated from Chromium 92.0.4515.70 to Chromium 92.0.4515.81.

Jenkinsfile
For https://github.com/brave/devops/issues/5365
=> param for devops repo branch

package.json
Fixes #16852
Related PR: brave/brave-core#9372
=> Upgrade from Chromium 92.0.4515.81 to Chromium 92.0.4515.93

package.json
Fixes #15316
Fixes #16726
Fixes #16852
Related PR: brave/brave-core#9361
Uplift from #15317 
Uplift from #16735
Uplift from #16854
=> Upgrade from Chromium 91 to Chromium 92 (1.27.x).

package.json
Fixes brave/brave-browser#16951
Related PR: brave/brave-core#9435
=> Upgrade from Chromium 92.0.4515.93 to Chromium 92.0.4515.101

package.json
Fixes #16977
Related PR: brave/brave-core#9455
=> Upgrade from Chromium 91.0.4472.124 to Chromium 91.0.4472.164 (1.26.x).

package.json
Fixes #16951
Related PR: brave/brave-core#9451
Uplift from #16952 
=> Upgrade from Chromium 92.0.4515.93 to Chromium 92.0.4515.101 (1.27.x).

package.json
Fixes #16951
Related PR: brave/brave-core#9450
Uplift from #16952 
=> Upgrade from Chromium 92.0.4515.93 to Chromium 92.0.4515.101 (1.28.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.26.x Release #4

CHANGELOG_ANDROID.md
=> [Android] Release notes for 1.26.x Release #4

package.json
Fixes brave/brave-browser#17036
Related PR: brave/brave-core#9492
=> Upgrade from Chromium 92.0.4515.101 to Chromium 92.0.4515.107

package.json
Fixes #17036
Related PR: brave/brave-core#9515
Uplift from #17040 
=> Upgrade from Chromium 92.0.4515.101 to Chromium 92.0.4515.107 (1.28.x).

package.json
Fixes #17036
Related PR: brave/brave-core#9516
Uplift from #17040 
=> Upgrade from Chromium 92.0.4515.101 to Chromium 92.0.4515.107 (1.27.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.27.x Release #1

package.json
Fixes #17162
Related PR: brave/brave-core#9554
=> Upgrade from Chromium 92.0.4515.107 to Chromium 92.0.4515.115

package.json
Fixes #17162
Related PR: brave/brave-core#9562
Uplift from #17165 
=> Upgrade from Chromium 92.0.4515.107 to Chromium 92.0.4515.115 (1.28.x).

package.json
Fixes #17162
Related PR: brave/brave-core#9563
Uplift from #17165
=> Upgrade from Chromium 92.0.4515.107 to Chromium 92.0.4515.115 (1.27.x).

.gitignore, .npmrc
Required for https://github.com/brave/brave-core/pull/9560/files#diff-4a7ab71a64ac5712bb35fb91782847039cf2def6ee9c3d64a7efa66562a99acfR252
Resolves https://github.com/brave/brave-browser/issues/11099
=> Remove .npmrc

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.27.x Release #2

CHANGELOG_ANDROID.md
=> Release notes for `1.27.x - Release #2`

package.json
Fixes brave/brave-browser#17306
Related PR: brave/brave-core#9620
=> Updated from Chromium 92.0.4515.115 to Chromium 92.0.4515.131.

package.json
Fixes #17306
Related PR: brave/brave-core#9626
Uplift from #17307 
=> Updated from Chromium 92.0.4515.115 to Chromium 92.0.4515.131 (1.28.x).

package.json
Fixes #17306
Related PR: brave/brave-core#9627
Uplift from #17307
=> Updated from Chromium 92.0.4515.115 to Chromium 92.0.4515.131 (1.27.x).

CHANGELOG_DESKTOP.md
=> Release notes for 1.27.x - Release #3

CHANGELOG_ANDROID.md
=> Release notes for `1.27.x - Release #3`

.gitattributes
Fixes brave/brave-browser#17317
Related PR: brave/brave-core#9625
=> Added .gitattbutes.

CHANGELOG_DESKTOP.md
=> `1.27.x - Release #3` Fix Typo

.gitattributes
Fixes #17317
Related PR: brave/brave-core#9690
Uplift from #17318 
=> Added .gitattbutes (1.29.x).

.gitattributes
Fixes #17317
Related PR: brave/brave-core#9691
Uplift from #17318 
=> Added .gitattbutes (1.28.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.28.x Release #1

CHANGELOG_ANDROID.md
=> Release notes for `1.28.x`

package.json
Fixes #17513
Related PR: brave/brave-core#9764
=> Upgrade from Chromium 92.0.4515.131 to Chromium 92.0.4515.159

package.json
Fixes #17513
Related PR: brave/brave-core#9765
Uplift from #17514  
=> Upgrade from Chromium 92.0.4515.131 to Chromium 92.0.4515.159 (1.29.x).

package.json
Fixes #17513
Related PR: brave/brave-core#9766
Uplift from #17514
=> Upgrade from Chromium 92.0.4515.131 to Chromium 92.0.4515.159 (1.28.x).

package.json
Fixes brave/brave-browser#16306
Related PR: brave/brave-core#9062
=> Upgrade from Chromium 92 to Chromium 93

package.json
Fixes #17549
Related PR: brave/brave-core#9786
=> Update from Chromium 93.0.4573.42 to Chromium 93.0.4577.51.

CHANGELOG_DESKTOP.md
=> Release notes for `1.28.x - Release #2`

CHANGELOG_ANDROID.md
=> Release notes for 1.28.x - Release #2

CHANGELOG_DESKTOP.md
=> Release notes for 1.28.x - Release #2 Fix

package.json
=> Adding myself to contributors.

package.json
Resolves #17668
Related PR: brave/brave-core#9839
=> Upgrade from Chromium 93.0.4577.51 to Chromium 93.0.4577.58.

package.json
Resolves #17790
Related PR: brave/brave-core#9931
=> Upgrade from Chromium 93.0.4577.58 to Chromium 93.0.4577.63

package.json
Resolves #17790
Related PR: brave/brave-core#9938
Uplift from #17791 
=> Upgrade from Chromium 93.0.4577.58 to Chromium 93.0.4577.63 (1.30.x)

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.29.x Release #2

CHANGELOG_ANDROID.md
=> Add Changelog for Android 1.29.78

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.29.x Release #4

CHANGELOG_ANDROID.md
=> Release notes for `1.29.x - Release #4`

CHANGELOG_DESKTOP.md
=> Release notes for `1.29.x - Release #5`

package.json
Fixes #17170
Related PR: brave/brave-core#9558
=> Upgrade from Chromium 93 to Chromium 94.

package.json
Resolves #18066
Related PR: brave/brave-core#10069
=> Upgrade from Chromium 93.0.4577.63 to Chromium 93.0.4577.82 (1.30.x)

package.json
Resolves #18066
Related PR: brave/brave-core#10076
Uplift from #18067  
=> Upgrade from Chromium 93.0.4577.63 to Chromium 93.0.4577.82 (1.29.x)

CHANGELOG_ANDROID.md
=> Release notes for `1.29.x - Release #6`

package.json
Fixes #18149
Related PR: brave/brave-core#10114
=> Upgrade from Chromium 94.0.4606.41 to Chromium 94.0.4606.50

package.json
Fixes #17170
Fixes #18149
Related PR: brave/brave-core#10086
Uplift from #17171
Uplift from #18150
=> Upgrade from Chromium 93 to Chromium 94 (1.30.x).

package.json
Fixes brave/brave-browser#18222
Related PR: brave/brave-core#10154
=> Upgrade from Chromium 94.0.4606.50 to Chromium 94.0.4606.54

package.json
Fixes #18222
Related PR: brave/brave-core#10162
Uplift from #18225 
=> Upgrade from Chromium 94.0.4606.50 to Chromium 94.0.4606.54 (1.31.x).

package.json
Fixes #18222
Related PR: brave/brave-core#10163
Uplift from #18225
=> Upgrade from Chromium 94.0.4606.50 to Chromium 94.0.4606.54 (1.30.x).

package.json
Fixes #18333 
Related PR: brave/brave-core#10241
=> Upgrade from Chromium 94.0.4606.54 to Chromium 94.0.4606.61

package.json
Fixes #18333
Related PR: brave/brave-core#10246
Uplift from #18338
=> Upgrade from Chromium 94.0.4606.54 to Chromium 94.0.4606.61 (1.31.x).

package.json
Fixes #18333
Related PR: brave/brave-core#10247
Uplift from #18338
=> Upgrade from Chromium 94.0.4606.54 to Chromium 94.0.4606.61 (1.30.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.30.x Release #1

package.json
Fixes #18477
Related PR: brave/brave-core#10329
=> Upgrade from Chromium 94.0.4606.61 to Chromium 94.0.4606.71

CHANGELOG_ANDROID.md
=> Release notes for `1.30.x - Release`

package.json
Fixes #18477
Related PR: brave/brave-core#10334
Uplift from #18478 
=> Upgrade from Chromium 94.0.4606.61 to Chromium 94.0.4606.71 (1.31.x).

package.json
Fixes #18477
Related PR: brave/brave-core#10335
Uplift from #18478
=> Upgrade from Chromium 94.0.4606.61 to Chromium 94.0.4606.71 (1.30.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.30.x Release #2

CHANGELOG_ANDROID.md
=> [Android] Release notes for 1.30.x Release #2

package.json
Fixes #17792
Related PR: brave/brave-core#9934
=> Upgrade from Chromium 94 to Chromium 95

CONTRIBUTING.md
Fix two small grammatical typos found in the body of the document.
The word "setup" should be the phrase "set up." The phrase describes a person's state of being, the former is a noun.
I also changed the phrase "can be ran" to "can be run."
Resolves 
=> Fixed Typos in Contributing.md

package.json
Resolves #19083
Related PR brave/brave-core#10757
Uplift from #19084 
=> Upgrade from Chromium 95.0.4638.54 to Chromium 95.0.4638.69 (1.32.x).

CHANGELOG_ANDROID.md
=> Release notes for `1.31.x - Release`

CHANGELOG_ANDROID.md
=> Release notes for `1.31.x - Release #2`

CHANGELOG_ANDROID.md
=> Release notes for `1.31.x - Release #3`

package.json
Fixes brave/brave-browser#19215
Related PR: brave/brave-core#10861
=> Upgrade from Chromium 96.0.4664.27 to Chromium 96.0.4664.35

README.md
Additional information for https://github.com/brave/brave-browser/issues/16419. This will never need to be uplifted.
=> Readme: describe `--ignore_chromium` flag

.github/PULL_REQUEST_TEMPLATE.md
Resolves https://github.com/brave/brave-browser/issues/19281
=> Add Brave Wallet to the list of documentation

package.json
Fixes #18131
Fixes #19215
Related PR: brave/brave-core#10888
Uplift from: #18133
Uplift from: #19216
=> Upgrade from Chromium 95 to Chromium 96 (1.32.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.31.x Release #4

CHANGELOG_ANDROID.md
=> Release notes for `1.31.x - Release #4`

package.json
Fixes #16419
Related PR brave/brave-core#11055
Uplift from #16558 
=> Move chromium version ref to brave-core/package.json (1.32.x).

CHANGELOG_DESKTOP.md
Resolves  
Typos in changelog_desktop.md file.
=> Fixed typos in changelog_desktop.md

README.md
Found some grammatical corrections during reading the readme .
Resolves 
=> grammatical-corrections in readme.md

CHANGELOG_ANDROID.md
=> Release notes for `1.32.x - Release`

CHANGELOG_ANDROID.md
=> Release notes for `1.32.x - Release #2`

lib/util.js
Resolves https://github.com/brave/brave-browser/issues/19398
=> make project compatible with npm 7

CHANGELOG_DESKTOP.md
=> Release notes for `1.32.x - Release #3`

lib/util.js
Reverts https://github.com/brave/brave-browser/pull/19724 
=> reverted project compatible with npm 7

lib/util.js
Npm <= 6 did not preserve dashes in package.json keys
Resolves https://github.com/brave/brave-browser/issues/19398
=> Support npm >=7 package.json -> environment variable conversion

CHANGELOG_DESKTOP.md
=> Release notes for `1.32.x - Release #4`

CHANGELOG_ANDROID.md
=> Release notes for `1.33.x - Release`

CHANGELOG_ANDROID.md
=> Release notes for `1.34.x - Release`

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.34.x Release #2

docs/source/conf.py
Simple change, but important at the same time
=> Changed Year From 2021 To 2022

README.md
This PR provides minor improvements to the readme's syntax. The headings toward the end were inconsistent, so for example I made them #### headers.
=> Modify heading and syntax

CHANGELOG_ANDROID.md
=> Release nots for `1.34.x - Release #2`

CHANGELOG_ANDROID.md
=> Release notes for `1.35.x`

CHANGELOG_DESKTOP.md
=> Release notes for `1.35.x - Release #2`

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.35.x Release #3

CHANGELOG_DESKTOP.md
=> Release notes for 1.35.x Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release notes for 1.36.x Release #2

README.md
=> Updating time required to run "npm run init" in README.md file 

CHANGELOG_DESKTOP.md
=> Release notes for `1.36.x - Release #3`

CHANGELOG_ANDROID.md
=> Release notes for `1.36.x - Release #2`

CHANGELOG_DESKTOP.md
=> Desktop Release notes for 1.36.x Release #4

CHANGELOG_DESKTOP.md
=> Release notes for 1.36.x - Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release notes for 1.36.x Release #6

CHANGELOG_ANDROID.md
=> Release notes for `1.36.x - Release #4`

CHANGELOG_DESKTOP.md
=> Release notes for `1.36.x - Release #7`

scripts/init.js
This is cleanup. No need to re-checkout brave-core since we won't be using gclient to manage git checkout for it anymore as of https://github.com/brave/brave-core/pull/11543. 
**Do not merge before that brave-core PR is uplifted to every current release branch.**
=> Init: don't re-checkout brave-core

scripts/init.js
Uplift of https://github.com/brave/brave-browser/pull/20020 
=> No gclient brave core 1.38.x

scripts/init.js
Uplift of https://github.com/brave/brave-browser/pull/20020 
=> No gclient brave core 1.37.x

CHANGELOG_ANDROID.md
=> Release notes for `1.37.x - Release`

CHANGELOG_ANDROID.md
=> Release notes for `1.37.x - Release #2`

CHANGELOG_ANDROID.md
=> Release notes for `1.37.x - Release #3`

CHANGELOG_DESKTOP.md
=> Desktop Relese Notes for 1.37.x Release #3

package-lock.json, package.json
Resolves 
https://ci.brave.com/job/chromium-update-minor/170/console failed so, it failed to pin `v1.37.111` to b-b
=> Pin v1.37.111

CHANGELOG_ANDROID.md
=> Release notes for `1.37.x - Release #4`

CHANGELOG_ANDROID.md
=> Release notes for `1.37.x - Release #5`

CHANGELOG_DESKTOP.md
=> Release notes for `1.37.x - Release #7`

CHANGELOG_ANDROID.md
=> Release notes for `1.38.x - Release #3`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.38.x Release #4

CHANGELOG_DESKTOP.md
=> Release notes for `1.38.x - Release #5`

CHANGELOG_ANDROID.md
=> Release notes for `1.38.x - Release #6`

CHANGELOG_ANDROID.md
=> Release notes for `1.39.x - Release #2`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.39.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/23344
=> Release notes for `1.39.x - Release #3`

CHANGELOG_DESKTOP.md
Fix #23395 + changes to previous version release notes
n/a
=> Desktop Release Notes for 1.39.x Release #4

CHANGELOG_DESKTOP.md
=> Update 1.39.x Release #4 Release Notes

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/23459
=> Release notes for `1.39.x - Release #5`

CHANGELOG_ANDROID.md
=> Android release notes for `1.40.x - Release`

CHANGELOG_ANDROID.md
=> Release notes for `1.40.x - Release #2`

CHANGELOG_DESKTOP.md
=> Release notes for `1.40.x - Release #3`

CHANGELOG_ANDROID.md
=> Release notes for `1.40.x - Release #5`

CHANGELOG_ANDROID.md
=> Android Release Notes for 1.40.x Release #6

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.41.x Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.41.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/24064
N/A
=> Android release notes for `1.41.x - Release`

CHANGELOG_ANDROID.md
Resolves #https://github.com/brave/brave-browser/issues/24260
N/A
=> Release notes for `1.41.x - Release #2`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/24263
N/A
=> Release notes for `1.41.x - Release #3`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.42.x - Release #2

CHANGELOG_ANDROID.md
Resolves #https://github.com/brave/brave-browser/issues/24613
N/A
=> Release notes for `1.42.x - Release #3`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.42.x Release #5

CHANGELOG_ANDROID.md
=> Add Release Notes to Android Release v1.42.x Release #5

CHANGELOG_DESKTOP.md
=> Release notes for `1.43.x - Release #2`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/25195
N/A
=> Release notes for `1.43.x - Release #3`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.43.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/25413
N/A
=> Release notes for `1.43.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/25455
N/A
=> Release notes for `1.43.x - Release #5`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/25652
N/A
=> Release notes for `1.44.x - Release`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.44.x Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/25779
N/A
=> Release notes for `1.44.x - Release #2`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.44.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.44.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/25934
N/A
=> Release notes for `1.44.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/26017
=> Release notes for `1.44.x - Release #5`

README.md
=> Updated README.md with learnings when building locally

README.md
Resolves https://github.com/brave/brave-browser/issues/26111
=> Update README.md and fix broken link

CONTRIBUTING.md
Resolves https://github.com/brave/brave-browser/issues/26111
=> Update CONTRIBUTING.md to fix broken link #26118

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/26261
=> Release notes for `1.45.x - Release #2`

.github/ISSUE_TEMPLATE/chromium_minor_bump.md
Resolves https://github.com/brave/brave-browser/issues/26297
=> Added GitHub issue template for Chromium Minor bumps.

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/26334
=> Release notes for `1.45.x - Release`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.45.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/26358
=> Release notes for 1.45.x - Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.45.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/26563
=> Release notes for `1.45.x - Release #5`

package-lock.json, package.json
Resolves https://github.com/brave/brave-browser/issues/26633
=> Bump version on 1.45.release6 branch to 1.45.122.

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/26630
=> Release notes for `1.45.x - Release #6`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.45.x Release #7

CHANGELOG_ANDROID.md
=> Android Release Notes for 1.45.x Release #7

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.45.x Release #8

CHANGELOG_ANDROID.md
=> Add Release Notes for Android 1.45.x Release #8

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/26972
N/A
=> Release notes for `1.45.x - Release #9`

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/27134
N/A
=> Release notes for `1.46.x - Release #2`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.46.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.46.x Release #4

CONTRIBUTING.md, README.md
I updated some broken links from translation.
The Transifex links where all broken in the CONTRIBUTIN.md and the README.md
=> fixing some broken links

.github/workflows/tweet-nightly.yml
Signed-off-by: Ahmed Kamal <email.ahmedkamal@googlemail.com>
Resolves 
=> Tweet nightly fix

.github/workflows/tweet-nightly.yml
Signed-off-by: Ahmed Kamal <email.ahmedkamal@googlemail.com>
Resolves 
=> Fix issue url

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/27389
N/A
=> Release notes for `1.46.x - Release #6`

.github/workflows/tweet-nightly.yml
Resolves #https://github.com/brave/devops/issues/8819
=> Fix job name

.github/CODEOWNERS
Part of https://github.com/brave/devops/issues/8876
This was coupled with enabling enforcement of code owner approvals on non-master branches a moment ago.
=> Added catch-all code owners

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.46.x Release #7

docs/source/conf.py
=> Changed Year From 2022 to 2023

package.json
YOU HAVE AN ANDROID CHANGELOG
Resolves 
=> You are on Android am I mistaken?

.github/CODEOWNERS
Resolves https://bravesoftware.slack.com/archives/C7VLGSR55/p1673308773278559
=> Dropped uplift-approvers as catch-all code owners and assingned only for changelogs

README.md
=> Added links to information about the npm config needed to build

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/27785
N/A
=> Release notes for `1.47.x - Release #2`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/27824
N/A
=> Release notes for `1.47.x - Release #3`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.47.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/28180
N/A
=> Release notes for `1.47.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/28127
N/A
=> Release notes for 1.47.x - Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.48.x Release #3

CHANGELOG_DESKTOP.md
=> Updated Desktop Release Notes for 1.48.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.48.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/28697
=> Release notes for `1.48.x - Release #3`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.48.x Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/28795
N/A
=> Release notes for `1.48.x - Release #5`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.49.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.49.x Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/28983
N/A
=> Release notes for `1.49.x - Release #2`

CHANGELOG_DESKTOP.md
Fix #29496
- [] Ran `git rebase master` (if needed)
n/a
=> Desktop Release Notes for 1.50.x

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.50.x Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.50.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.50.x Release #4

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/29902
=> Release notes for `1.50.x - Release #5`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/30002
N/A
=> Release notes for `1.50.x - Release #4`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.51.x Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/30240
N/A
=> Release notes for `1.51.x - Release #2`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.51.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/30409
N/A
=> Release notes for `1.51.x - Release #3`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/30537
N/A
=> Release notes for `1.51.x - Release #4`

.gitignore
These are the results of running `npm run init`.
=> Add build files to gitignore

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.52.x

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.52.x Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.52.x Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.52.x Release #7

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/30723
N/A
=> Release notes for `1.52.x - Release`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/30789
N/A
=> Release notes for `1.52.x - Release #3`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/30870
N/A
=> Release notes for `1.52.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/31517
N/A
=> Release notes for `1.52.x - Release #5`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/31519
N/A
=> Release notes for `1.52.x - Release #6`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/31522
N/A
=> Release notes for `1.52.x - Release #7`

README.md
Resolves https://github.com/brave/brave-browser/issues/31594
=> Add Rust information to brave-browser README.md

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.56.x Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.56.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.56.x Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.56.x Release #7

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/32243
N/A
=> Release notes for `1.56.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/31901
N/A
=> Release notes for `1.56.x - Release #6`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/32247
N/A
=> Release notes for `1.56.x - Release #7`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.57.x

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.57.x Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.57.x Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.57.x Release #5

README.md
=> Fixed capital letter in README.md

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.57.x Release #7

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.57.x Release #8

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/32389
N/A
=> Release notes for `1.57.x - Release #3`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/32983
N/A
=> Release notes for `1.58.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/32631
N/A
=> Release notes for `1.57.x - Release #6`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/32785
=> Release notes for `1.57.x - Release #7`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.58.x

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.58.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.58.x Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.58.x Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.58.x Release #6

renovate.json
Resolves https://github.com/brave/brave-browser/issues/33325
=> renovate.json: add org-level config

.github/workflows/pull_request.yml
Resolves https://github.com/brave/brave-browser/issues/33360
=> ci: pull_request.yml pin deps

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.58.x Release #7

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/33725
N/A
=> Release notes for `1.59.x - Release #2`

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/33763
N/A
=> Release notes for `1.59.x - Release #3`

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/33913
N/A
=> Release notes for `1.59.x - Release #4`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.60.x

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.60.x Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/33024
N/A
=> Release notes for `1.58.x - Release #2`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34349
N/A
=> Release notes for `1.58.x - Release #5`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34359
N/A
=> Release notes for `1.58.x - Release #6`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34361
N/A
=> Release notes for `1.58.x - Release #7`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34364
N/A
=> Release notes for `1.58.x - Release`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34409
N/A
=> Release notes for `1.60.x - Release`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34241
N/A
=> Release notes for `1.60.x - Release #3`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34423
N/A
=> Release notes for `1.60.x - Release #4`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.60.x Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.61.x Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34739
N/A
=> Release notes for `1.61.x - Release`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.61.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34922
N/A
=> Release notes for `1.61.x - Release #3`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.61.x Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.61.x Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/35003
N/A
=> Release notes for `1.61.x - Release #5`

README.md
got discussed here:
- https://github.com/brave/brave-browser/pull/34505
Closes: 
- #34505
=> (chor) Remove goma information from readme

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.61.x Release #6

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/35121
N/A
=> Release notes for `1.61.x - Release #6`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.61.x Release #7

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/35230
N/A
=> Release notes for `1.61.x - Release #7`

README.md
Fix https://github.com/brave/brave-browser/issues/35354
Resolves 
=> Add more development docs

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.61.x Release #8

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/35368
N/A
=> Release notes for `1.61.x - Release #8`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/34420
N/A
=> Release notes for `1.62.x - Release #2`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.62.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/35741
N/A
=> Release notes for `1.62.x - Release #3`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.62.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/36029
N/A
=> Release notes for `1.62.x - Release #4`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.63.x Release

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/36320
N/A
=> Release notes for `1.62.x - Release #5`

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/36329
N/A
=> Release notes for `1.63.x - Release #2`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.63.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.63.x Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.63.x Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/36768
N/A
=> Release notes for `1.63.x - Release #3`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/36782
N/A
=> Release notes for `1.63.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/36927
N/A
=> Release notes for `1.63.x - Release #5`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.64.x Release

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.64.x Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.64.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.64.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/37654
N/A
=> Release notes for `1.64.x - Release`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/37658
N/A
=> Release notes for `1.64.x - Release #2`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/37562
N/A
=> Android release notes for 1.64.x - Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.65.x Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.65.x Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.65.x Release #4

CHANGELOG_iOS.md
Resolves [#36959](https://github.com/brave/brave-browser/issues/36959)
=> Release Notes for iOS Release 1.64.123

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.65.x Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.65.x Release #6

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.66.x Release

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.66.x Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.66.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/37861
N/A
=> Release notes for `1.65.x - Release #2`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/38621
N/A
=> Release notes for `1.65.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/38623
N/A
=> Release notes for `1.65.x - Release #6`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/38626
N/A
=> Release notes for `1.65.x - Release #7`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/38630
N/A
=> Release notes for `1.66.x - Release #2`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/38633
N/A
=> Release notes for `1.66.x - Release #4`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.66.x Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/38748
N/A
=> Android release notes for 1.66.x - Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/38835
N/A
=> Android release notes for 1.66.x - Release #6

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.67.x Release

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/39054
N/A
=> Release notes for `1.67.x - Release #2`

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/39168
N/A
=> Release notes for `1.67.x - Release #3`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/39172
N/A
=> Android release notes for 1.67.x - Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.67.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/39360
N/A
=> Android release notes for 1.67.x - Release #4

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/39765
N/A
=> Add Release Notes for iOS Release 1.66.123

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/39149
N/A
=> Add Release Notes for iOS Release 1.66.124 (1.66.2)

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/39832
N/A
=> Android release notes for 1.67.x - Release #7

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.68.x Release

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/40043
=> Release notes for `1.68.x - Release #2`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.68.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/39956
N/A
=> Android release notes for 1.68.x - Release

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/40183
N/A
=> Android release notes for 1.68.x - Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.68.x Release #6

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/40404
N/A
=> Release notes for `1.68.x - Release #6`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.68.x Release #7

CHANGELOG_ANDROID.md, CHANGELOG_DESKTOP.md
=> docs: fix typo

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/40616
N/A
=> Android release notes for 1.69.x - Release

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.69.x Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.69.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/40773
N/A
=> Android release notes for 1.69.x - Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/40883
N/A
=> Android release notes for 1.69.x - Release #4

.git-blame-ignore-revs
This file is being added to mirror upstream config settings for it, to avoid issues where the settings for the upstream file interfere with git blaming in brave-core.
Resolves 
=> Adding `.git-blame-ignore-revs` file

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.69.x Release #5

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/41109
N/A
=> Add Release Notes for iOS Release 1.68.145

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/41246
=> Release notes for `1.70.x - Release #2`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/41249
N/A
=> Android release notes for 1.70.x - Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.70.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/41366
N/A
=> Android release notes for 1.70.x - Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.70.x Release #4

CHANGELOG_ANDROID.md
Resolves [#41522](https://github.com/brave/brave-browser/issues/41522)
N/A
=> Android release notes for 1.70.x - Release #4

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/41772
N/A
=> Add Release Notes for iOS Release 1.69.172

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.71.x Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/41838
N/A
=> Android release notes for 1.71.x - Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.71.x Release #3

CHANGELOG_ANDROID.md
=> Android release notes for 1.71.x - Release #3

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/42006
N/A
=> Add Release Notes for iOS Release 1.70.133

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/42130
N/A
=> Android release notes for 1.71.x - Release #4

CHANGELOG_ANDROID.md
=> Android release notes for 1.73.x - Release

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.73.x Release #2

CHANGELOG_ANDROID.md
=> Android release notes for 1.73.x - Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.73.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/42677
N/A
=> Android release notes for 1.73.x - Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.73.x Release #5

CHANGELOG_ANDROID.md
=> Android release notes for 1.73.x - Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.73.x Release #6

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/42992
N/A
=> Android release notes for 1.73.x - Release #6

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.73.x Release #7

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/43180
N/A
=> Android release notes for 1.73.x - Release #7

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.74.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/43460
N/A
=> Android release notes for 1.74.x - Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.74.x Release #4

CHANGELOG_ANDROID.md
=> Android release notes for 1.74.x - Release #4

CHANGELOG_ANDROID.md
=> Android release notes for 1.75.x - Release

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.75.x Release #2

README.md
Resolves https://github.com/brave/brave-browser/issues/43966
=> Update android development link

CHANGELOG_ANDROID.md
=> Android release notes for 1.75.x - Release #2

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/44098
=> Release notes for `1.75.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/44104
N/A
=> Android release notes for 1.75.x - Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.75.x Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.76.x Release

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.76.x Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/44618
N/A
=> Android release notes for 1.76.x - Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.76.x Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/44834
N/A
=> Android release notes for 1.76.x - Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.76.x Release #6

CHANGELOG_ANDROID.md
=> Release notes for `1.76.x - Release #6`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.76.x Release #7

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/45157
N/A
=> Android release notes for 1.77.x - Release

CHANGELOG_DESKTOP.md
=> Update Desktop Release Notes for 1.77.95

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.77.x Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/45381
N/A
=> Release notes for `1.77.x - Release #2`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.77.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/45490
N/A
=> Android release notes for 1.77.x - Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/45646
N/A
=> Android release notes for 1.77.x - Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.78.x

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/45763
N/A
=> Android release notes for 1.78.x - Release

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/45850
N/A
=> Android release notes for 1.78.x - Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.78.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/45925
N/A
=> Android release notes for 1.78.x - Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/45996
N/A
=> Android release notes for 1.78.x - Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.78.x Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/46106
N/A
=> Android release notes for 1.78.x - Release #5

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/46267
N/A
=> Add Release Notes for 1.78.1 

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.79.x Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/46553
N/A
=> Android release notes for 1.79.x - Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/46759
N/A
=> Android release notes for 1.79.x - Release #3

CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/46938
=> Release notes for `1.79.x - Release #5`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/46945
N/A
=> Android release notes for 1.79.x - Release #5

CHANGELOG_ANDROID.md, CHANGELOG_DESKTOP_ARCHIVE.md
Remove redundant word in CHANGELOG_ANDROID.md and CHANGELOG_DESKTOP_ARCHIVE.md
=> Remove redundant word in CHANGELOG_ANDROID.md and CHANGELOG_DESKTOP_ARCHIVE.md

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.80.x Release

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/47016
N/A
=> Android release notes for 1.80.x - Release

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/47324
N/A
=> Android release notes for 1.80.x - Release #2

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/47114
N/A
=> Add Release Notes for iOS Release 1.80 [Changelog]

CHANGELOG_iOS.md
=> Update Release Notes for 1.80.116 [Changelog]

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/47528
N/A
=> Add Release Notes for iOS Release 1.80.1 [Changelog]

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.80.x Release #6

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.80.x Release #7

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.80.x Release #8

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/48057
N/A
=> Android release notes for 1.80.x - Release #9

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.81.x Release

.github/ISSUE_TEMPLATE/config.yml, CHANGELOG_iOS.md, README.md
For https://github.com/brave/devops/issues/13832
The redirect is included, so all the links will still work. Merge at your convenience.
=> chore: Update community domain name

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.81.x Release #3

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/48393
=> Release notes for `1.81.x - Release #3`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/48752
=> Release notes for `1.81.x - Release #5`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.82.x Release

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/48979
N/A
=> Android release notes for 1.82.x - Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/49116
N/A
=> Android release notes for 1.82.x - Release #3

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.82.x Release #4

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/49149
N/A
=> Android release notes for 1.82.x - Release #4

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.82.x Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/49406
N/A
=> Android release notes for 1.82.x - Release #5

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.82.x Release #7

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/49811
N/A
=> Add Release Notes for iOS Release 1.82.1 [changelog] 

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.83.x Release

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.83.x Release #2

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/49823
N/A
=> Android release notes for 1.83.x - Release #2

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.83.x Release #3
