package.json

use http url for brave-core

---

.github/ISSUE_TEMPLATE.md

Updated template to match new version. 
Closes #166
N/A

Update issue template for new version

---

lib/config.js

disable nacl

---

scripts/commands.js

Add channel param to create_dist

---

lib/config.js

Close https://github.com/brave/brave-browser/issues/251

Use debug build as a default mode

---

package.json

Fix npm dependency

---

package.json

Fix https://github.com/brave/brave-browser/issues/265
- [x ] Added/updated tests for this change (for new code or code which already has tests).

Update Chromium to 67.0.3396.62

---

package.json

All updates to the version should be done in both brave-core and
brave-browser repositories.

Sync version with brave-core

---

package.json

Fixes: https://github.com/brave/brave-browser/issues/320

Changes the package description to the same as the repository description

---

package.json

Fix https://github.com/brave/brave-browser/issues/333

Upgrade to Chromium 67.0.3396.87

---

lib/config.js

Closes https://github.com/brave/brave-browser/issues/330

Use jumbo build to non-official build

---

package.json

Bump patch version for new internal build

Bump patch version for new internal build

---

lib/l10nUtil.js

Fix https://github.com/brave/brave-browser/issues/133

Add support for translating brave_generated_resources.grd

---

lib/build.js

Issue https://github.com/brave/brave-browser/issues/352

Touch overridden objective-c++ file(.mm) also

---

Dockerfile

Add lsb-release dependency which is used by install-build-deps.sh

---

lib/config.js
lib/util.js
scripts/sync.js

Closes #362
Run CI with it. Also clone on laptop and attempt build with and without flag.

add optional cache for cloning repos

---

lib/l10nUtil.js
lib/updatePatches.js
lib/util.js

This is for replacing branding strings, see https://github.com/brave/brave-core/pull/179 for the corresponding brave-core PR.
I'll merge this along with brave-core PR after both PRs are reviewed.

add required resources for branding in settings and extensions page

---

package.json

Fix https://github.com/brave/brave-browser/issues/437

Update to Chromium 67.0.3396.103

---

lib/config.js

Fixes issue #444, add vendored path to Python requests module

---

lib/util.js

Copy midl files only on Windows

---

.github/ISSUE_TEMPLATE.md

Reword website section

---

package-lock.json

Adds package-lock

---

lib/createDist.js

close https://github.com/brave/brave-browser/issues/582

Rename unstable to dev in linux build output

---

lib/l10nUtil.js

Update crash reporting label to remove reference to "statistics"

---

package.json

Bump to 68.0.3440.68

---

.gitignore

Adds ignore rules for CLion

---

.github/ISSUE_TEMPLATE.md

Adds info to the issue template that this repo is for upcoming version of Brave

---

lib/build.js
lib/config.js

Fix https://github.com/brave/brave-browser/issues/657

Use brave-browser version and check for inconsistency with src/chrome/VERSION

---

lib/test.js
scripts/commands.js

Fix https://github.com/brave/brave-browser/issues/692

Add switch for running tests in single process mode

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR submitter checklist

---

package.json

Upgrade to Chromium 69.0.3497.32

---

package.json

Upgrade to Chromium 69.0.3497.42

---

lib/config.js
package-lock.json
package.json

Before merging I will get rid of the branch commit.
Related: https://github.com/brave/brave-core/pull/358

Upgrade to Chromium 70.0.3528.4

---

lib/start.js
scripts/commands.js

Support --vmodule for verbose logging from specific modules

---

package.json

New apply_patches command is more memorable than sync --run_hooks.

---

lib/util.js

This module is for adding brave appearance options to settings page.
Issue: https://github.com/brave/brave-browser/issues/789
This pr should be merged together with https://github.com/brave/brave-core/pull/361

Copy brave_appearance_page module

---

package-lock.json
package.json

Fix https://github.com/brave/brave-browser/issues/952

Upgrade from Chromium 70.0.3528.4 to 70.0.3538.12

---

lib/config.js

App name will be changed from Brave-Browser-XXX to Brave Browser XXX.
Close https://github.com/brave/brave-browser/issues/1109
This PR should be merged with https://github.com/brave/brave-core/pull/437

Reflect new mac app name to start script

---

lib/test.js
scripts/commands.js

Fix https://github.com/brave/brave-browser/issues/1158

Add --test_launcher_jobs=X test arg

---

package.json

Fix https://github.com/brave/brave-browser/issues/1249

Update from 70.0.3538.16 to 70.0.3538.22

---

lib/util.js

Add default Brave shield settings

---

package-lock.json
package.json

Fix https://github.com/brave/brave-browser/issues/1291

Bump version to 0.56.1

---

package-lock.json
package.json

Fix https://github.com/brave/brave-browser/issues/1293

Bump to 0.57.1

---

lib/config.js

Fixes https://github.com/brave/brave-browser/issues/1328

Allow commit hash for brave-core

---

package.json

Fix https://github.com/brave/brave-browser/issues/1313

Upgrade to Chromium 70.0.3538.35

---

package.json

Fix https://github.com/brave/brave-browser/issues/1425

Upgrade Chromium from 70.0.3538.35 to 70.0.3538.45

---

package.json

Fix https://github.com/brave/brave-browser/issues/1522

Upgrade Chromimum to 70.0.3538.54

---

package-lock.json
package.json

Fix https://github.com/brave/brave-browser/issues/1617

Bump 0.58.1

---

package.json

Fix: https://github.com/brave/brave-browser/issues/1629

Update from 70.0.3538.54 to 70.0.3538.67

---

.gitignore
lib/start.js
scripts/commands.js

Partial https://github.com/brave/brave-browser/issues/1161

Adds QA flags for rewards

---

docs/source/installing-brave.rst

Fixes issue https://github.com/brave/brave-browser/issues/1653

Include Linux release channel instructions in ReadTheDocs.

---

package.json

For the contributors in package.json

Update per @mkarolin :)

---

README.md
package.json

Fix https://github.com/brave/brave-browser/issues/1702

Update README and support email

---

lib/start.js
lib/whitelistedUrlPrefixes.js
package-lock.json
package.json
scripts/commands.js

Fix https://github.com/brave/brave-browser/issues/1706

Detect internal IPs, expand whitelist, add output_path option for release builds

---

docs/source/installing-brave.rst

docs/installing: Add new public key URL for new signing key

---

README.md

Add translations to README

---

.github/ISSUE_TEMPLATE.md

Remove browser-laptop from issue template

---

lib/l10nUtil.js

see https://github.com/brave/brave-core/pull/719

update paths for https://github.com/brave/brave-core/pull/719

---

package.json

Fix https://github.com/brave/brave-browser/issues/1848

Upgrade from 70.0.3538.67 to 70.0.3538.77

---

docs/source/installing-brave.rst

Fix typo on Cent/RHEL

---

package-lock.json
package.json

Relating to https://github.com/brave/brave-browser/issues/1953

Bump 0.59.1

---

lib/updatePatches.js

Some filies in chrome/app/theme should be patched.
Should be merged together with https://github.com/brave/brave-core/pull/813.
Issue https://github.com/brave/brave-browser/issues/2001

Modify updatePatches to make patches in chrome/app/theme

---

package.json

Fix https://github.com/brave/brave-browser/issues/2078

Upgrade from Chromium 71.0.3578.31 to 71.0.3578.44

---

package.json

Note: This is only for 0.56.x and is being PR'ed against that branch.
Fix https://github.com/brave/brave-browser/issues/2099

Update patches for Chromium 70.0.3538.102

---

lib/l10nUtil.js

Fix https://github.com/brave/brave-browser/issues/2108
Must be merged with: https://github.com/brave/brave-core/pull/893

Copy rewards l10n files when there are changes

---

docs/source/installing-brave.rst

Fix incorrect name of .list file for dev ubuntu.

---

docs/source/installing-brave.rst

Fixes https://github.com/brave/brave-browser/issues/2120

removed append from tee

---

package.json

Fix https://github.com/brave/brave-browser/issues/2177

Upgrade from Chromium 71.0.3578.44 to 71.0.3578.53

---

CHANGELOG.md

Release notes for 0.56.x Hotfix 2

---

lib/start.js
scripts/commands.js

Partial for https://github.com/brave/brave-browser/issues/2102

Adds support for unified rewards flag

---

package.json

See also https://github.com/brave/brave-core/pull/983
Fix https://github.com/brave/brave-browser/issues/2284

Upgrade from Chromium 71.0.3578.53 to 71.0.3578.75

---

package-lock.json
package.json

Fix https://github.com/brave/brave-browser/issues/2292

Bump master to 0.60.1

---

package.json

Fix https://github.com/brave/brave-browser/issues/2352
Related https://github.com/brave/brave-core/pull/1018

Upgrade from 71.0.3578.75 to 71.0.3578.80

---

scripts/audit.js

fix https://github.com/brave/brave-browser/issues/2380

check src/brave/brave_sync/extension for npm vulnerabilities

---

CHANGELOG.md

Release notes for 0.57.x

---

docs/source/installing-brave.rst

Add a note to each of the release/beta/dev install sections with the fingerprint of the key being used.

Note current signing key fingerprints

---

package-lock.json
package.json

Fix https://github.com/brave/brave-browser/issues/2491

Bump version to 0.61.0

---

lib/start.js
scripts/commands.js

pass through ads command line opts

---

CHANGELOG.md

Release notes for 0.58.x Hotfix 1 (Release Channel)

---

package.json

Fix https://github.com/brave/brave-browser/issues/2706
Related: https://github.com/brave/brave-core/pull/1185

Upgrade from 72.0.3626.17 to 72.0.3626.28

---

CHANGELOG.md

Release notes for 0.58.x Hotfix 2 (Release Channel)

---

lib/build.js
lib/config.js
lib/start.js
lib/util.js

fix https://github.com/brave/brave-browser/issues/2794
requires https://github.com/brave/brave-core/pull/1198

add support for building/running signed app in development

---

CHANGELOG.md

Release notes for 0.58.x Hotfix 3 (Release Channel)

---

package.json

Fix https://github.com/brave/brave-browser/issues/2932
Must be merged with: https://github.com/brave/brave-core/pull/1314

Upgrade from Chromium 72.0.3626.28 to 72.0.3626.53

---

docs/source/installing-brave.rst

Update RHEL/Centos docs to prevent permission denied errors

---

docs/source/installing-brave.rst

Replace tee -a with just tee in Centos/RHEL docs

---

lib/l10nUtil.js

Fixes #2983
Uplift request from #2989

Replace "Chrome Web Store" with "Web Store"

---

package.json

Fix https://github.com/brave/brave-browser/issues/3008

Upgrade from Chromium 72.0.3626.53 to 72.0.3626.64

---

README.md

Update the Read Me link to the current repository for iOS.
No issue created because it is a trivial change to the Read Me file.

Update iOS repository information

---

package-lock.json
package.json

Fix https://github.com/brave/brave-browser/issues/3074

Bump 0.62.0

---

package.json

Fix https://github.com/brave/brave-browser/issues/3086

Upgrade from 72.0.3626.64 to 72.0.3626.71

---

docs/source/installing-brave.rst

Use a separate keyring for the apt signing keys (closes #2508)

---

scripts/commands.js

It can be also used on Windows installer.
Fix https://github.com/brave/brave-browser/issues/3149

Change description of --skip_signing

---

package.json

Fix https://github.com/brave/brave-browser/issues/3146

Upgrade from Chromium 72.0.3626.71 to 72.0.3626.81

---

CHANGELOG.md

Fixes version for 0.59.x release notes

---

CHANGELOG.md

Release notes for 0.59.x Hotfix 1

---

package.json

Fixes #3255 
Related: brave/brave-core#1603

Upgrade from 72.0.3626.81 to 72.0.3626.96

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/3251

added Windows to PR builder pipeline

---

Jenkinsfile

Uplift of https://github.com/brave/brave-browser/pull/3283
Fixes: https://github.com/brave/brave-browser/issues/3310

Include capability to run official builds

---

lib/whitelistedUrlPrefixes.js

Use CDN for publisher list

---

package.json

Fixes #3358
Related: brave/brave-core#1675

Upgrade from 72.0.3626.96 to 72.0.3626.109

---

lib/whitelistedUrlPrefixes.js

Fix https://github.com/brave/brave-browser/issues/3317

Add Brave catalog service to network audit whitelist

---

package.json

Fix https://github.com/brave/brave-browser/issues/3374

Upgrade from 73.0.3683.27 to 73.0.3683.39

---

package-lock.json
package.json

Per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#how-to-do-branch-migrations

Update Nightly channel to: 0.63.0

---

package.json

Fixes #3447 
Related: brave/brave-core#1757

Upgrade from 72.0.3626.109 to 72.0.3626.119

---

README.md
lib/l10nUtil.js

Fix https://github.com/brave/brave-browser/issues/1506
Fix https://github.com/brave/brave-browser/issues/3399
Fix https://github.com/brave/brave-browser/issues/1555
Branch name will be removed before merging. 

Updates for brave_extension in brave-core

---

Jenkinsfile

refactored PR builder

---

Jenkinsfile

Comment out sccache in .npmrc on Windows

---

CHANGELOG.md

Fix #3536
N/A, release notes for `0.60.47`.

Release notes for 0.60.x Hotfix #1

---

package.json

Fixes #3546 
Related: brave/brave-core#1820

Upgrade from Chromium 72.0.3626.119 to Chromium 72.0.3626.121

---

package.json

Fixes #3594 
Related: brave/brave-core#1865

Upgrade from Chromium 73.0.3683.39 to Chromium 73.0.3683.56

---

CHANGELOG.md

Fix #3591
N/A. Ran through the following manual passes:
* https://github.com/brave/brave-browser/issues/3585 (Linux manual pass)
* https://github.com/brave/brave-browser/issues/3583 (macOS manual pass)
* https://github.com/brave/brave-browser/issues/3584 (Windows manual pass)

Release notes for 0.60.x Hotfix 2

---

Jenkinsfile

Added `nightly` channel, ability to disable `sccache` and to wipe workspace, longer timeout per build and specific timeouts per test type.

fixes for pr builder

---

Jenkinsfile

pr builder fixes 0.61

---

Jenkinsfile

pr builder fixes 0.62

---

package.json

Fixes #3608 
Related: brave/brave-core#1883

Upgrade from Chromium 73.0.3683.56 to Chromium 73.0.3683.67

---

package.json

Fixes #3669
Related: brave/brave-core#1915

Upgrade from Chromium 73.0.3683.67 to Chromium 73.0.3683.75

---

docs/source/conf.py
docs/source/index.rst
docs/source/installing-brave.rst

Closes https://github.com/brave/brave-browser/issues/3782

added nightly channel to docs

---

package.json

Fixes #3813
Related: brave/brave-core#2021

Upgrade from Chromium 73.0.3683.75 to Chromium 73.0.3683.86

---

.github/PULL_REQUEST_TEMPLATE.md

fix https://github.com/brave/brave-browser/issues/3841

Issue 3841: Update PR template to add a check for test-security

---

CHANGELOG.md

Release notes for 0.61.x Hotfix 1

---

package.json

Fixes: #3858
Related: brave/brave-core#2040

Upgrade from Chromium 74.0.3729.22 to Chromium 74.0.3729.28

---

package.json

This reverts commit 22001ccc0e5a3779da7b6dbf16c9ef8d140169bb, reversing
changes made to 04f0099dc4c1a3391cfc64bee5ec89e54c3160a5.

Revert "Merge pull request #3857 from brave/74.0.3729.28_master_21"

---

docs/source/installing-brave.rst

Added a section for unofficial packages in to the installing brave documentation.
- verified it looked good through GitHub rendering the page

Add official packages section and add Solus

---

package.json

Fixes #4014 
Related: brave/brave-core#2163

Upgrade Chromium 73.0.3683.86 to Chromium 73.0.3683.103 on 0.62.x

---

CHANGELOG.md

Release notes for 0.62.x Fix

---

CHANGELOG.md

Release notes for 0.62.x Hotfix 1

---

package.json

Fixes #4033 
Related: brave/brave-core#2172

Upgrade Chromium 74.0.3729.40 to Chromium 74.0.3729.61

---

Jenkinsfile

Related https://github.com/brave/devops/issues/856

disabled git cache on mac

---

package.json

Fixes #4065 
Related: brave/brave-core#2194

Upgrade Chromium 74.0.3729.61 to Chromium 74.0.3729.75

---

Jenkinsfile
lib/util.js

Closes https://github.com/brave/devops/issues/856

added cache_dir option to gclient

---

.github/ISSUE_TEMPLATE.md

Updating the Issue template

---

.github/PULL_REQUEST_TEMPLATE.md

Fix https://github.com/brave/brave-browser/issues/4134
See also: https://github.com/brave/brave-core/pull/2238

Update PR template to include documentation fixes

---

package.json

Fixes #4145
Related: brave/brave-core#2254

Upgrade Chromium 74.0.3729.75 to Chromium 74.0.3729.91

---

package.json

Fixes #4192
Related: brave/brave-core#2314
Related: #4193

Upgrade Chromium 74.0.3729.91 to Chromium 74.0.3729.108

---

Jenkinsfile

improved pipeline

---

CHANGELOG.md

Removing unneeded/duplicate text in release notes

---

package.json

Fixes https://github.com/brave/brave-browser/issues/4278
(waiting until CI finishes)

Upgrade from Chromium "74.0.3729.108" to Chromium 74.0.3729.131

---

CHANGELOG.md

Release notes for 0.63.x Hotfix #1

---

Jenkinsfile

Closes https://github.com/brave/devops/issues/874
Closes https://github.com/brave/devops/issues/881

multiple pipeline fixes

---

lib/config.js
lib/util.js
scripts/commands.js
scripts/sync.js

```npm run build -- --target_os=android```

Add support for building android apk

---

Jenkinsfile

add android to ci pipeline

---

lib/config.js

fix https://github.com/brave/brave-browser/issues/4453

don't default to arm (x86/x64 builds are better for the emulator)

---

CHANGELOG.md

Release notes for 0.64.x Hotfix 1

---

package.json

Will fill this in soon; wanting to let CI run
Related https://github.com/brave/brave-core/pull/2451

Upgrade from Chromium 75.0.3770.27 to Chromium 75.0.3770.38

---

package.json

Fixes https://github.com/brave/brave-browser/issues/4526

Upgrade from Chromium 74.0.3729.157 to Chromium 74.0.3729.169

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4520

ci pipeline pinning fix

---

CHANGELOG.md

Release notes for 0.64.x Hotfix 2

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4543

fixed ci skipping

---

lib/config.js
scripts/sync.js

Support diff cpu architecture for Android

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4592

added early fail in CI pipeline if version mismatch between b-b and b-c

---

lib/config.js
lib/util.js
scripts/commands.js
scripts/sync.js

Support of mono and modern apks, branding resources

---

Dockerfile

Resolving problem with rustup in Dockerfile

---

lib/config.js

add Brave's Android package name

---

Jenkinsfile

Includes workaround for https://github.com/brave/brave-browser/issues/1922
Closes https://github.com/brave/brave-browser/issues/4665
Closes https://github.com/brave/brave-browser/issues/4666
Closes https://github.com/brave/brave-browser/issues/4667
Closes https://github.com/brave/brave-browser/issues/4668

removed sync, added optional signing and multiple fixes to CI pipeline

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4686
- [] Added/updated tests for this change (for new code or code which already has tests).

added labels to skip building specified OS in CI pipeline

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4687

added skip of build per OS based on b-c PR labels

---

Jenkinsfile

fixed CI pipeline skipping by OS

---

Jenkinsfile
lib/config.js
lib/util.js
scripts/commands.js

fixes brave/brave-browser#3080 with https://github.com/brave/brave-core/pull/2552

add support for `--target_os=ios`

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4703

added ios to ci pipeline

---

package.json

Fixes brave/brave-browser#4547
Related brave/brave-core#2585

Upgrade from Chromium 75.0.3770.38 to Chromium 75.0.3770.75

---

lib/config.js

Fixes: https://github.com/brave/brave-browser/issues/4716

Fix check for target os equality with 'ios'

---

package.json

Fixes #4724
Related https://github.com/brave/brave-core/pull/2597

Upgrade from Chromium 75.0.3770.75 to Chromium 75.0.3770.80

---

Jenkinsfile
lib/config.js

added dist to ios build in ci pipeline

---

CHANGELOG.md

Release notes for 0.65.x

---

Jenkinsfile

CI pipeline update uplift 0.65.x

---

Jenkinsfile

CI pipeline update uplift 0.66.x

---

Jenkinsfile

CI pipeline update uplift 0.67.x

---

package.json

Fixes #4780 
Related: brave/brave-core#2644

Upgrade from Chromium 75.0.3770.80 to Chromium 75.0.3770.87

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4810
Closes https://github.com/brave/brave-browser/issues/4811

various ci pipeline fixes

---

Jenkinsfile
lib/build.js
lib/config.js
lib/util.js
scripts/commands.js

Fix https://github.com/brave/brave-browser/issues/944
Related: https://github.com/brave/brave-core/pull/2158

Enable widevine cdm host verification

---

Jenkinsfile

F/U PR of https://github.com/brave/brave-browser/pull/4000
Fix https://github.com/brave/brave-browser/issues/944

Delete wrong appended character

---

Jenkinsfile

several CI pipeline improvements

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4862

added test execution for ios in ci pipeline

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4864

switched to arm instead of arm64 for android in ci pipeline

---

.github/PULL_REQUEST_TEMPLATE.md

added android and ios to github issue template

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4883

fixed lint to use b-c base branch when no b-b PR

---

lib/config.js

Sig file is not generated properly.
F/U PR of https://github.com/brave/brave-browser/pull/4000
Issue: https://github.com/brave/brave-browser/issues/944

Disable widevine cdm host verification on MacOS

---

package.json

Fixes #4888
Related: brave/brave-core#2691
Related: 4892

Upgrade from Chromium 75.0.3770.80 to Chromium 75.0.3770.90 (on 0.65.x)

---

lib/config.js

Issue: https://github.com/brave/brave-browser/issues/4905

Enable widevine vmp on MacOS

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4917

switched to digicert timestamp server

---

package.json

Fixes #4888 
Related: brave/brave-core#2686

Upgrade from Chromium 75.0.3770.87 to Chromium 75.0.3770.90

---

CHANGELOG.md

Release notes for 0.65.x Hotfix1

---

lib/config.js

fix https://github.com/brave/brave-browser/issues/4931

add ccache support

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4959

fixed test result parsing in CI pipeline

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/4965

added slack notifications for b-c prs

---

package.json

Fixes #4962 
Related: brave/brave-core#2728

Upgrade from Chromium 75.0.3770.90 to Chromium 75.0.3770.100

---

package.json

Fixes #4962
Related: brave/brave-core#2730
Uplift request from #4964

Upgrade from Chromium 75.0.3770.90 to Chromium 75.0.3770.100 (0.67.x)

---

package.json

Fixes #4962
Related: brave/brave-core#2731
Uplift request from #4964

Upgrade from Chromium 75.0.3770.90 to Chromium 75.0.3770.100 (0.66.x)

---

CHANGELOG.md

Release notes for 0.65.x Hotfix 2

---

lib/config.js

Remove brave_enable_cdm_host_verification gn var.
It's sufficient to use existing enable_cdm_host_verification.
Issue: https://github.com/brave/brave-browser/issues/4905

Cleanup previous widevine vmp PRs

---

lib/config.js

Fix https://github.com/brave/brave-browser/issues/4905

Enable widevine VMP on MacOS by default

---

lib/config.js

Fix https://github.com/brave/brave-browser/issues/5002

config.shouldSign() should return false if skip_signing is true

---

Jenkinsfile

attempted fix for test result parsing and init on windows

---

Jenkinsfile

removed test result parsing and added s3 init step

---

CHANGELOG.md

Release notes for 0.66.x

---

docs/source/installing-brave.rst

Fixes: https://github.com/brave/brave-browser/issues/5100

Remove brave-keyring from install documentation

---

lib/start.js

fix https://github.com/brave/brave-browser/issues/5082
* Catch non-http(s) protocols
* Catch IPv6 hosts
Test plan:
* run 'npm run network-audit'
* browse to localhost:8080 (doesn't have to be resolvable)
* browse to http://[2001:db8:85a3::8a2e:370:7334]/
* quit brave or wait for audit to finish
* in the terminal, you should see an audit failure for
http://http://[2001:db8:85a3::8a2e:370:7334]/ but not localhost.

Expand coverage of network-audit script

---

Jenkinsfile

added official build checkbox to ci pipeline

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/5174

credential fixes for CI pipeline

---

Jenkinsfile
lib/test.js
package.json

Fix #5083
Related PR: brave/brave-core#2892
See #5083

Upgrade from Chromium 75.0.3770.100 to Chromium 76.0.3809.62

---

Jenkinsfile
jest.config.js
lib/calculateFileChecksum.js
lib/calculateFileChecksum.test.js
lib/gitPatcher.js
lib/gitPatcher.test.js
lib/jsconfig.json
lib/sync/logging.js
lib/util.js
package-lock.json
package.json
scripts/sync.js

Allow switching between brave-core branches and not incurring a lengthy build because all ~400 chromium source files were reset and had patches re-applied.
Instead, only reset target files and apply patches when appropriate: when either the patch file has changed or the chromium source file has been modified.
1. "reset" a project repo (`chromium` or `brave-core`) only when the working directory commit reference does not match the target branch commit reference. Before, this happened every sync.
2. "reset" and re-apply patched individual files _only_ when either the .patch file has changed, or the patched target file has changed. Before, this happened every sync.
3. Applies any v8 patches found in `brave-core/patches/v8` directory (created by #4955)
4. Adds more visual logging to the …

 Apply patches now only selectively resets repo paths and applies patches

---

lib/build.js

Fix https://github.com/brave/brave-browser/issues/5208

Build: Only fail when versions mismatch in CI environment

---

package.json

Fixes https://github.com/brave/brave-browser/issues/5253
Related https://github.com/brave/brave-core/pull/2926

Upgrade from Chromium 75.0.3770.100 to Chromium 75.0.3770.142

---

CHANGELOG.md

Release notes for 0.66.x Hotfix 1

---

Jenkinsfile
lib/test.js
package.json

Fix #5083
Related PR: brave/brave-core#2934
Uplift request from #5206 

Upgrade from Chromium 75.0.3770.100 to Chromium 76.0.3809.62 (0.68.x)

---

lib/whitelistedUrlPatterns.js

Uplift request for: https://github.com/brave/brave-browser/pull/5276

Fix #5275: Update whitelist patterns for new crlset request URLs (#5276) (uplift to 0.66.x)

---

lib/whitelistedUrlPatterns.js

Uplift request for: https://github.com/brave/brave-browser/pull/5276

Fix #5275: Update whitelist patterns for new crlset request URLs (#5276) (uplift to 0.67.x)

---

lib/whitelistedUrlPatterns.js

Uplift request for: https://github.com/brave/brave-browser/pull/5276

Fix #5275: Update whitelist patterns for new crlset request URLs (#5276) (uplift to 0.68.x)

---

Jenkinsfile
lib/test.js
package.json

Fix #5083
Related PR: brave/brave-core#2939
Uplift request from #5206

Upgrade from Chromium 75.0.3770.100 to Chromium 76.0.3809.62 (0.67.x)

---

CHANGELOG.md

Release notes for 0.66.x Hotfix 2

---

docs/source/installing-brave.rst

Fixed #5343 and addresses https://github.com/brave/brave-browser/issues/5156#issuecomment-508577491.

Improve apt installation instructions

---

package.json

Fixes #5299 
Related PR: brave/brave-core#2976

Upgrade from Chromium 76.0.3809.62 to Chromium 76.0.3809.72

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/5364
Fixes https://github.com/brave/brave-browser/issues/5299
`brave-core` PR is WIP...

Upgrade from Chromium 76.0.3809.62 to Chromium 76.0.3809.72 (RELEASE)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/5364
Fixes https://github.com/brave/brave-browser/issues/5299
Related https://github.com/brave/brave-core/pull/3019

Upgrade from Chromium 76.0.3809.62 to Chromium 76.0.3809.72 (DEV)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/5364
Fixes https://github.com/brave/brave-browser/issues/5299

Upgrade from Chromium 76.0.3809.62 to Chromium 76.0.3809.72 (BETA)

---

package.json

Fixes https://github.com/brave/brave-browser/issues/5424
Related: https://github.com/brave/brave-core/pull/3040

Upgrade from Chromium 76.0.3809.72 to Chromium 76.0.3809.87

---

Jenkinsfile
lib/config.js
scripts/commands.js

CI pipeline sync uplift to 0.67.x

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/5446
Related: https://github.com/brave/brave-core/pull/3047
Fixes https://github.com/brave/brave-browser/issues/5424

Upgrade from Chromium 76.0.3809.72 to Chromium 76.0.3809.87 (DEV)

---

CHANGELOG.md

Release notes for 0.67.x

---

lib/util.js

copy Android related resources

---

package.json

Fixes https://github.com/brave/brave-browser/issues/5554
Related: https://github.com/brave/brave-core/pull/3099

Upgrade from Chromium 76.0.3809.87 to Chromium 76.0.3809.100

---

CHANGELOG.md

Release notes for 0.67.x Hotfix1

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/5556
Related: https://github.com/brave/brave-core/pull/3106
Fixes https://github.com/brave/brave-browser/issues/5554

Upgrade from Chromium 76.0.3809.87 to Chromium 76.0.3809.100 (DEV)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/5556
Related: https://github.com/brave/brave-core/pull/3107
Fixes https://github.com/brave/brave-browser/issues/5554

Upgrade from Chromium 76.0.3809.87 to Chromium 76.0.3809.100 (BETA)

---

CHANGELOG.md

Release notes for 0.67.x Hotfix2

---

lib/config.js

Fix brave/brave-browser#5683
Build on Android and iOS and observe no warnings.

Delete brave_infura_project_id arg on mobile

---

Jenkinsfile

Brave-Core PRs are getting the error:
```
groovy.lang.MissingPropertyException: No such property: bbPrNumber for class: WorkflowScript
```
This is caused by invalid property names in the Jenkinsfile. Only brave-browser PRs were tested by https://github.com/brave/brave-browser/pull/5700 which introduced this issue.
Fix https://github.com/brave/brave-browser/issues/5732

Build: fix data collection for brave-core PRs

---

lib/util.js

Handle missing directory when in 'update branding' stage of build

---

lib/l10nUtil.js

Address https://github.com/brave/brave-browser/issues/5665 but fixed with brave-core PR.
Generated results are in https://github.com/brave/brave-core/pull/3249

Rename 'people' / 'person' in chromium strings to 'profile(s)'

---

Jenkinsfile

Closes https://github.com/brave/devops/issues/1316

add test build step for windows

---

Jenkinsfile

fixed ci pipeline

---

Jenkinsfile

switch CI pipeline to EC2 fleet and use aws s3 for upload

---

lib/whitelistedUrlPrefixes.js

Issue 5857: Whitelist the P3A endpoint.

---

Jenkinsfile

Uplift PR Builder Jenkinsfile changes from master

---

Jenkinsfile

Use shorter workspace on Windows CI builds

---

docs/source/installing-brave.rst

This will hopefully reduce the number of support requests from people trying to install our packages on a 32-bit distro.

Mention that only 64-bit distros are supported.

---

Jenkinsfile

Use shorter workspace on Windows CI builds (attempt #2)

---

package.json

Fixes #5966 
Related PR: brave/brave-core#3400

Upgrade from Chromium 77.0.3865.65 to Chromium 77.0.3865.75

---

lib/start.js

Fixes brave/brave-browser#5992
net-log-capture-mode IncludeSocketBytes has been deprecated. We should
use Everything instead.
This doesn't result in an error as the Chromium code auto substitutes
the value, but might as well transition to the new value.
Chromium change:
https://chromium.googlesource.com/chromium/src/+/3124cde5bcd57129d9fd1e53a89a1938e926cfcd
<pre>
commit	3124cde5bcd57129d9fd1e53a89a1938e926cfcd	[log] [tgz]
author	Eric Roman <eroman@chromium.org>	Wed Jul 10 22:26:15 2019
committer	Commit Bot <commit-bot@chromium.org>	Wed Jul 10 22:26:15 2019
tree	d50fe295f8144e9263e43f6fc78d45d548ed81b2
parent	88cba811376c38706fb03929e61d7e35eb003d26 [diff]
Make NetLogCaptureMode an enum.
Historically the capture mode had aspirations for more complex parameterization, but in practice it …

Fixes network-audit net-log-capture-mode.

---

CHANGELOG.md

Release notes for 0.68.x HF2

---

Jenkinsfile

Related to https://github.com/brave/brave-browser/issues/5387

CI pipeline fixes

---

Jenkinsfile

Follow-up after https://github.com/brave/brave-browser/pull/5986

fixed lint in CI pipeline

---

Jenkinsfile

Mplesa ci pipeline windows sdk 0.71.x

---

Jenkinsfile

Mplesa ci pipeline windows sdk 0.70.x

---

Jenkinsfile

Mplesa ci pipeline windows sdk 0.69.x

---

lib/config.js
package.json
scripts/lint.py

Fixes #5375
Related PR: brave/brave-core#3433
Uplift request from #5896

Upgrade from Chromium 76.0.3809.132 to Chromium 77.0.3865.65 (0.69.x)

---

package.json

Fixes #5966
Related PR: brave/brave-core#3457
Uplift request from #5967

Upgrade from Chromium 77.0.3865.65 to Chromium 77.0.3865.75 (0.70.x).

---

package.json

Fixes #5966
Related PR: brave/brave-core#3456
Uplift request from #5967

Upgrade from Chromium 77.0.3865.65 to Chromium 77.0.3865.75 (0.69.x).

---

package.json

Fixes https://github.com/brave/brave-browser/issues/6062
Related https://github.com/brave/brave-core/pull/3474

Upgrade from Chromium 77.0.3865.75 to Chromium 77.0.3865.90

---

package.json

Fixes #6062
Related brave/brave-core#3486
Uplift request from #6065

Upgrade from Chromium 77.0.3865.75 to Chromium 77.0.3865.90 (0.69.x)

---

package.json

Fixes #6062
Related brave/brave-core#3485
Uplift request from #6065

Upgrade from Chromium 77.0.3865.75 to Chromium 77.0.3865.90 (0.70.x)

---

package.json

Fixes #6062
Related brave/brave-core#3484
Uplift request from #6065 

Upgrade from Chromium 77.0.3865.75 to Chromium 77.0.3865.90 (0.71.x)

---

docs/source/installing-brave.rst

Add OpenSUSE installation instructions

---

CHANGELOG.md

Release notes for 0.68.x HF3

---

Jenkinsfile

CI pipeline sync

---

CHANGELOG.md

Release notes for 0.68.x Hotfix 4

---

CHANGELOG.md

Release notes for 0.68.x Hotfix 5

---

CHANGELOG.md

Release notes for 0.68.x Hotfix 6

---

docs/source/installing-brave.rst

Fixes #6231 .
I followed the Fedora 28+ instructions to install Brave in a CentOS 8 VM.

Add install instructions for CentOS 8

---

CHANGELOG.md

Fix spelling mistake in 0.69.x release notes

---

package.json

Pinned branched was left over from a merge.
Fixed back to master.

Fixes b-c branch pinning.

---

package.json

Fixes https://github.com/brave/brave-browser/issues/6414
Related https://github.com/brave/brave-core/pull/3659
-----

Upgrade from Chromium 77.0.3865.90 to Chromium 77.0.3865.120

---

package-lock.json
package.json

Update Nightly channel to: 0.73.0

---

package.json

fix branch in package.json

---

lib/config.js

Fix https://github.com/brave/brave-browser/issues/5691
Will be tested with the brave-core PR: https://github.com/brave/brave-core/pull/3198

Issue 5691: Add brave service key to the npm config

---

package.json

Fixes #6508
Related PR: brave/brave-core#3760

Upgrade from Chromium 78.0.3904.50 to Chromium 78.0.3904.70

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/6571
Fixes https://github.com/brave/brave-browser/issues/6508
Related https://github.com/brave/brave-core/pull/3772

Upgrade from Chromium 78.0.3904.50 to Chromium 78.0.3904.70 (uplift to 0.70.x)

---

lib/config.js
lib/util.js
scripts/commands.js

Depends on another PR https://github.com/brave/brave-core/pull/3731

Android enable rewards

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/6571
Fixes https://github.com/brave/brave-browser/issues/6508
Related https://github.com/brave/brave-core/pull/3773

Upgrade from Chromium 78.0.3904.50 to Chromium 78.0.3904.70 (uplift to 0.72.x)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/6571
Fixes https://github.com/brave/brave-browser/issues/6508
Related https://github.com/brave/brave-core/pull/3774

Upgrade from Chromium 78.0.3904.50 to Chromium 78.0.3904.70 (uplift to 0.71.x)

---

Jenkinsfile

Issue 6593: Trying to fix git cache path on Win.

---

package.json

Fixes #6692 
Related PR: brave/brave-core#3845

Upgrade from Chromium 78.0.3904.70 to Chromium 78.0.3904.87

---

CHANGELOG.md

Release notes for 0.70.x Hotfix 1

---

package.json

Fixes #6692
Related PR: brave/brave-core#3852
Uplift from #6694 

Upgrade from Chromium 78.0.3904.70 to Chromium 78.0.3904.87 (0.71.x)

---

package.json

Fixes #6692
Related PR: brave/brave-core#3851
Uplift from #6694 

Upgrade from Chromium 78.0.3904.70 to Chromium 78.0.3904.87 (0.72.x)

---

lib/config.js
lib/createDist.js
scripts/commands.js

Uplift of #5485
Related https://github.com/brave/brave-core/pull/3856
Approved, please ensure that before merging:

Add MacOS notarization (Uplift of #5485 to 0.72.x)

---

Jenkinsfile

CI pipeline sync 0.72.x

---

Jenkinsfile

CI pipeline sync 0.71.x

---

Jenkinsfile

CI pipeline sync 0.70.x

---

package-lock.json

`brave-browser` version of https://github.com/brave/brave-core/pull/3878

Fixing handlebars vulnerability

---

Jenkinsfile

Fixes: https://github.com/brave/brave-browser/issues/6787

CI: avoid 'Method code too large!' error

---

Jenkinsfile

fixed method code too large

---

Jenkinsfile

Uplift of https://github.com/brave/brave-browser/issues/6803

fixed method code too large 0.71.x

---

Jenkinsfile

Uplift of https://github.com/brave/brave-browser/issues/6803

fixed method code too large 0.72.x

---

Jenkinsfile

Uplift of https://github.com/brave/brave-browser/issues/6803

fixed method code too large 0.73.x

---

package.json

Fixes #6789
Related PR: brave/brave-core#3904

Upgrade from Chromium 78.0.3904.87 to Chromium 78.0.3904.97 (0.70.x)

---

package.json

added package.json back

---

package.json

fixed pinned branch for b-c

---

CHANGELOG.md

Release notes for 0.70.x Hotfix 2

---

package.json

Fixes #6789 
Related PR: brave/brave-core#3893

Upgrade from Chromium 78.0.3904.87 to Chromium 78.0.3904.97

---

package.json

Fixes #6789
Related PR: brave/brave-core#3930
Uplift request from: #6790 

Upgrade from Chromium 78.0.3904.87 to Chromium 78.0.3904.97 (0.71.x)

---

lib/config.js

Fix https://github.com/brave/brave-browser/issues/4859
Need to be merged together with https://github.com/brave/brave-core/pull/3905

Enable ads in android

---

lib/config.js

Fix https://github.com/brave/brave-browser/issues/6838

Add brave_safetynet_api_key to gn args only for android build

---

package.json

Fixes #6789
Related PR: brave/brave-core#3950
Uplift request from: #6790

Upgrade from Chromium 78.0.3904.87 to Chromium 78.0.3904.97 (0.72.x)

---

package.json

Fixes #6789
Related PR: brave/brave-core#3949
Uplift request from: #6790

Upgrade from Chromium 78.0.3904.87 to Chromium 78.0.3904.97 (0.73.x)

---

lib/config.js

Add app IDs for nightly/dev/beta on Android

---

package-lock.json

Uplifts: https://github.com/brave/brave-browser/pull/6935
Fixes: https://github.com/brave/brave-browser/issues/6934

Fixing handlebars vulnerability (1.1.x)

---

package-lock.json

Uplifts: https://github.com/brave/brave-browser/pull/6935
Fixes: https://github.com/brave/brave-browser/issues/6934

Fixing handlebars vulnerability (1.2.x)

---

lib/util.js

Use appropriate icon set on Android

---

package.json

Fix https://github.com/brave/brave-browser/issues/6974
1. Debug build after updating widevine version string in `package.json`
2. Start browser (`yarn start --vmodule=*widevine*=2`) with existing profile (widevine is already installed) and check below logs
```
[18294:18294:0624/064937.097475:VERBOSE1:brave_widevine_bundle_manager.cc(287)] StartupCheck: widevine prefs state looks fine
[18294:18294:0624/064937.097561:VERBOSE1:brave_widevine_bundle_manager.cc(288)] StartupCheck: installed widevine version: 4.10.1440.18
[18294:18294:0624/064937.097612:VERBOSE1:brave_widevine_bundle_manager.cc(292)] StartupCheck: new widevine version(4.10.1582.2) is found …
```

Update Widevine version to 4.10.1582.2 on linux

---

LICENSE

The third-parties listed in this file were removed when we switched from Muon to brave-core.

Remove outdated entries from LICENSE

---

package.json

Fixes #6987 
Related PR: brave/brave-core#4009

Upgrade from Chromium 78.0.3904.97 to Chromium 78.0.3904.108

---

lib/config.js

Disable widevine on android

---

CHANGELOG.md

Release notes for 1.0.x Hotfix 1

---

package-lock.json

Fix handlebars vulnerability

---

package-lock.json
package.json

Fixes #6987
Related PR: brave/brave-core#4022
Uplift from #6990

Upgrade from Chromium 78.0.3904.97 to Chromium 78.0.3904.108 (1.1.x)

---

lib/util.js

Fix https://github.com/brave/brave-browser/issues/6406
Co-PR: https://github.com/brave/brave-core/pull/4047

Android dark mode

---

Jenkinsfile

improve test macos install step

---

lib/l10nUtil.js
lib/util.js
package.json

Fixes #6588
Related PR brave/brave-core#4091

Upgrade from Chromium 78.0.3904.108 to Chromium 79.0.3945.56

---

lib/l10nDeleteTranslations.js
lib/l10nUtil.js
lib/pullL10n.js
lib/transifexAPI.js
package.json
scripts/commands.js

Background: When addressing https://github.com/brave/brave-browser/issues/738, we discovered that the string replacements we are doing for chromium's generated_resources.grd (and other related grdp files), did not have their translations re-translated with the new replaced source strings. I created a script to take the affected string_ids and clear out the translations for each of the fifty-something languages. That script is included in this PR under `delete_string_translations`. After I ordered the updated resource to have these now-deleted strings be re-translated, I also wanted a way to pull only that resource's translations back to source. I updated the `pull10n` script to accept a path parameter.
```
❯ npm run delete_string_translations -- --help
> brave@0.73.51 …
```

Delete transifex translations

---

package.json

Fixes #7213 
Related PR: brave/brave-core#

Upgrade from Chromium 79.0.3945.56 to Chromium 79.0.3945.70

---

.npmrc

https://github.com/brave/brave-browser/issues/7244

removed checksum upload

---

lib/build.js
lib/licensing.js

Uplift of #7155 .
This depends on https://github.com/brave/brave-core/pull/4127 in order to build successfully.

Automatically generate LICENSE files for external components (uplift to 1.2.x)

---

package.json

Fixes #7213
Related PR: brave/brave-core#4153
Uplift from #7216

Upgrade from Chromium 79.0.3945.56 to Chromium 79.0.3945.70 (1.2.x)

---

package.json

Fixes #7213
Related PR: brave/brave-core#4154
Uplift from #7216

Upgrade from Chromium 79.0.3945.56 to Chromium 79.0.3945.70 (1.1.x)

---

package.json

Fixes #7213
Related PR: brave/brave-core#4152
Uplift from #7216 

Upgrade from Chromium 79.0.3945.56 to Chromium 79.0.3945.70 (1.3.x)

---

package.json

Fixes #7282 
Related PR: brave/brave-core#4184

Upgrade from Chromium 79.0.3945.70 to Chromium 79.0.3945.74

---

package.json

Fixes #7282
Related PR: brave/brave-core#4198
Uplift from #7287 

Upgrade from Chromium 79.0.3945.70 to Chromium 79.0.3945.74 (1.1.x)

---

CHANGELOG.md

Release notes for 1.1.x

---

package.json

Fixes #7282
Related PR: brave/brave-core#4200
Uplift from #7287

Upgrade from Chromium 79.0.3945.70 to Chromium 79.0.3945.74 (1.3.x)

---

package.json

Fixes #7282
Related PR: brave/brave-core#4199
Uplift from #7287

Upgrade from Chromium 79.0.3945.70 to Chromium 79.0.3945.74 (1.2.x)

---

docs/source/installing-brave.rst

Replaces https://github.com/brave/brave-browser/pull/3195.
Fixes: https://github.com/brave/brave-browser/issues/2343, https://github.com/brave/brave-browser/issues/5156, https://github.com/brave/brave-website/issues/194.
Look at https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux and confirm that:
- There are no more `${UBUNTU_CODENAME}` variable in the instructions.
- There is a single Debian/Ubuntu/Mint section in each channel.
- There is a link to https://brave.com/signing-keys/ near the top of the page.

Easier Debian/Ubuntu installation instructions

---

package.json

Fixes #7314 
Related PR: brave/brave-core#4207

Upgrade from Chromium 79.0.3945.74 to Chromium 79.0.3945.79.

---

package.json

Fixes #7314
Related PR: brave/brave-core#4219
Uplift from #7320

Upgrade from Chromium 79.0.3945.74 to Chromium 79.0.3945.79 (1.1.x)

---

package.json

Fixes #7314
Related PR: brave/brave-core#4217
Uplift from #7320 

Upgrade from Chromium 79.0.3945.74 to Chromium 79.0.3945.79 (1.3.x)

---

package.json

Fixes #7314
Related PR: brave/brave-core#4218
Uplift from #7320

Upgrade from Chromium 79.0.3945.74 to Chromium 79.0.3945.79 (1.2.x)

---

CHANGELOG.md

Release notes for 1.1.x Hotfix #1

---

Jenkinsfile
lib/config.js

Fix https://github.com/brave/brave-browser/issues/7391

Revert component build release

---

CHANGELOG.md

Release notes for 1.1.x Hotfix 2

---

lib/config.js

Sign apk for Android release builds

---

package.json

Fixes #7435
Related PR: brave/brave-core#4254

Upgrade from Chromium 79.0.3945.79 to Chromium 79.0.3945.88 (1.1.x)

---

package.json

Fixes #7435 
Related PR: brave/brave-core#4244

Upgrade from Chromium 79.0.3945.79 to Chromium 79.0.3945.88

---

package.json

Fixes #7435
Related PR: brave/brave-core#4258
Uplift from #7436

Upgrade from Chromium 79.0.3945.79 to Chromium 79.0.3945.88 (1.2.x)

---

package.json

Fixes #7435
Related PR: brave/brave-core#4257
Uplift from #7436 

Upgrade from Chromium 79.0.3945.79 to Chromium 79.0.3945.88 (1.3.x)

---

CHANGELOG.md

Release Notes for 1.1.x Hotfix 3

---

Jenkinsfile
lib/build.js
lib/config.js
lib/util.js
scripts/commands.js

default to Component build config

add Component and Static build configs

---

lib/l10nUtil.js

Fixes https://github.com/brave/brave-browser/issues/7614 along with https://github.com/brave/brave-core/pull/4311.
Open https://testsafebrowsing.appspot.com/s/phishing.html and click "Details".
Check that it says "**Google** Safe Browsing" and not "**Brave** Safe Browsing".

Credit Google for Safe Browsing (fixes brave/brave-browser#7506)

---

package.json

Fixes https://github.com/brave/brave-browser/issues/7640
Related https://github.com/brave/brave-core/pull/4319

Upgrade from Chromium 79.0.3945.88 to Chromium 79.0.3945.117

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/7644
Fixes https://github.com/brave/brave-browser/issues/7640
Related: https://github.com/brave/brave-core/pull/4320

Upgrade from Chromium 79.0.3945.88 to Chromium 79.0.3945.117 (uplift to 1.2)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/7644
Fixes https://github.com/brave/brave-browser/issues/7640
Related: https://github.com/brave/brave-core/pull/4322

Upgrade from Chromium 79.0.3945.88 to Chromium 79.0.3945.117 (uplift to 1.4)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/7644
Fixes https://github.com/brave/brave-browser/issues/7640
Related: https://github.com/brave/brave-core/pull/4321

Upgrade from Chromium 79.0.3945.88 to Chromium 79.0.3945.117 (uplift to 1.3)

---

Jenkinsfile

fix-testinstall-mac when no params found

---

CHANGELOG.md

Release notes for 1.2.x Hotfix 1

---

lib/l10nUtil.js

Fix https://github.com/brave/brave-browser/issues/7587
brave-core PR: https://github.com/brave/brave-core/pull/4355

Do not replace Google Play to Brave Play

---

lib/config.js

Fix https://github.com/brave/brave-browser/issues/7681
- Build in release mode
- Verify that app has the correct channel identifier

Set android_channel based on channel

---

lib/config.js

Related to https://github.com/brave/brave-browser/issues/7681

Development build should have android_channel set to default

---

lib/util.js

Overwrite google default ntp tiles (android)

---

lib/upload.js
scripts/commands.js

added github upload for android apks

---

package.json

Fixes https://github.com/brave/brave-browser/issues/7781
Related https://github.com/brave/brave-core/pull/4383

Upgrade from Chromium 79.0.3945.117 to Chromium 79.0.3945.130

---

lib/util.js

Addresses brave/brave-browser#4837
Required by https://github.com/brave/brave-core/pull/4329 
brave-core repo should point to or should have https://github.com/brave/brave-core/pull/4329 changes
1. Run build
2. After passing `copy Android app icons and app resources` `brave-browser/src/chrome/android/java/res_template/xml/syncadapter.xml` should be overwritten by Brave's stub from  `brave-browser/src/brave/android/java/res_template/xml/syncadapter.xml`
```
<sync-adapter />
```

Copy res_template dir files for Android build

---

.github/ISSUE_TEMPLATE/android-issue.md
.github/ISSUE_TEMPLATE/desktop.md

Add Android issue template

---

CHANGELOG.md

Release notes for 1.2.x Hotfix 2

---

.github/CODEOWNERS
lib/whitelistedUrlPrefixes.js

Fixes #7789.
`npm run network-audit`

Cleanup network audit whitelist 

---

scripts/commands.js

depends on https://github.com/brave/brave-core/pull/4396

collects Android object files

---

Jenkinsfile

fix issue 7858 for test-install on macOS

---

lib/config.js

closes https://github.com/brave/brave-browser/issues/7600

enable video playing on Android

---

.github/PULL_REQUEST_TEMPLATE.md
scripts/audit.js

Fix https://github.com/brave/brave-browser/issues/7851

Simplify audit_deps and add it to PR template

---

Jenkinsfile

added dist to android in ci pipeline

---

Jenkinsfile

For https://github.com/brave/brave-browser/issues/7892

added qa code to android core npm config

---

.github/ISSUE_TEMPLATE/android-issue.md

Add Android-related label for Android template

---

lib/whitelistedUrlPrefixes.js

Fix #7959 
Covered by `npm run network-audit` in CI

Fix 7959: Add tor.bravesoftware.com to audit whitelist

---

lib/l10nUtil.js
lib/util.js
package.json

Fixes #7255
Related PR: brave/brave-core#4374

Upgrade from Chromium 79.0.3945.117 to Chromium 80.0.3987.66

---

package.json

Fixes #7975 
Related PR: brave/brave-core#4464

Upgrade from Chromium 80.0.3987.66 to Chromium 80.0.3987.78.

---

package.json

Fixes #8033 
Related PR: brave/brave-core#4483

Upgrade from Chromium 80.0.3987.78 to Chromium 80.0.3987.85.

---

package.json

Fixes #8033
Related PR: brave/brave-core#4495
Uplift request from: #8036

Upgrade from Chromium 80.0.3987.78 to Chromium 80.0.3987.85 (1.5.x).

---

package.json

Fixes #8033
Related PR: brave/brave-core#4497
Uplift request from: #8036

Upgrade from Chromium 80.0.3987.78 to Chromium 80.0.3987.85 (1.4.x).

---

package.json

Fixes #8033
Related PR: brave/brave-core#4498
Uplift request from: #8036

Upgrade from Chromium 80.0.3987.78 to Chromium 80.0.3987.85 (1.3.x).

---

package.json

Fixes #8058 
Related PR: brave/brave-core#4506

Upgrade from Chromium 80.0.3987.85 to Chromium 80.0.3987.87.

---

package.json

Fixes #8058
Related PR: brave/brave-core#4520
Uplift from #8064

Upgrade from Chromium 80.0.3987.85 to Chromium 80.0.3987.87 (1.4.x).

---

lib/whitelistedUrlPatterns.js
lib/whitelistedUrlPrefixes.js

Fix #8034 
Uplift for https://github.com/brave/brave-browser/pull/8035

Fix 8034: Add Crowd Deny requests to audit whitelist (uplift to 1.3)

---

lib/whitelistedUrlPatterns.js
lib/whitelistedUrlPrefixes.js

Fix #8034 
Uplift for https://github.com/brave/brave-browser/pull/8035

Fix 8034: Add Crowd Deny requests to audit whitelist (uplift to 1.5)

---

Jenkinsfile

Fix error: "No such property: RUN_NETWORK_AUDIT for class: WorkflowScript"
This reverts commit b61595dfdea03d05f7d3a86733b8a5b1cb3157cd, reversing
changes made to a6950427c9367e51e17ef6b87dcaf2af6a0a51a0.

Revert "Merge PR #8101 brave/mplesa-ci-pipeline-network-audit-label"

---

Jenkinsfile

Redo of https://github.com/brave/brave-browser/pull/8101

added feature to run network audit on demand

---

scripts/lint.py

Fix 8127: Update GetChange to remove the author arg (uplift for 1.5.x)

---

scripts/lint.py

Fix 8127: Update GetChange to remove the author arg (uplift for 1.4.x)

---

scripts/lint.py

Fix 8127: Update GetChange to remove the author arg (uplift for 1.3.x)

---

lib/util.js

Original PR https://github.com/brave/brave-browser/pull/8131

Fixes app icon on mono builds

---

CHANGELOG.md

Release notes for 1.3.x Hotfix 1

---

Jenkinsfile

improve testInstallMac step

---

lib/licensing.js

This change to match the Chromium style does not affect anything
else than the contents of the Brave Adblock component in the
brave://rewards page.
This is a follow-up to 4a702ecd1ef018d052f9ebb21e21d363a8910ca4
(brave/brave-browser#7176).
Goes with https://github.com/brave/brave-core/pull/4485.
Look at the "Brave Adblock" entry in `brave://credits` and ensure it looks mostly the same as before. There will be some ordering changes and some hyphens are now underscores.

Remove hyphens in the adblock list directories

---

Jenkinsfile

Fixes brave/brave-browser#8167 for CI / PR Builder builds.

Use proxy for the Mozilla Location Service

---

package.json

Fixes #8188 
Related PR: brave/brave-core#4593

Upgrade from Chromium 80.0.3987.87 to Chromium 80.0.3987.100.

---

package.json

Fixes #8188
Related PR: brave/brave-core#4620
Uplift from #8195 

Upgrade from Chromium 80.0.3987.87 to Chromium 80.0.3987.100 (1.5.x).

---

Jenkinsfile

uplift of 7859 8179 8101

---

package.json

Fixes #8241 
Related PR: brave/brave-core#4638

Upgrade from Chromium 80.0.3987.100 to Chromium 80.0.3987.106.

---

package.json

Fixes #8241
Related PR: brave/brave-core#4645
Uplift from: #8242

Upgrade from Chromium 80.0.3987.100 to Chromium 80.0.3987.106 (1.3.x).

---

package.json

Fixes #8241
Related PR: brave/brave-core#4643
Uplift from: #8242 

Upgrade from Chromium 80.0.3987.100 to Chromium 80.0.3987.106 (1.5.x).

---

package.json

Fixes #8241
Related PR: brave/brave-core#4644
Uplift from: #8242

Upgrade from Chromium 80.0.3987.100 to Chromium 80.0.3987.106 (1.4.x).

---

Jenkinsfile

Fixes: https://github.com/brave/devops/issues/2507

Update to use GitHub Oauth2 token vs. deprecated querystring

---

package.json

Fixes #8304 
Related PR: brave/brave-core#4677

Upgrade from Chromium 80.0.3987.106 to Chromium 80.0.3987.116.

---

package.json

Fixes #8304
Related PR: brave/brave-core#4683
Uplift from: #8305

Upgrade from Chromium 80.0.3987.106 to Chromium 80.0.3987.116 (1.3.x).

---

package.json

Fixes #8304
Related PR: brave/brave-core#4681
Uplift from: #8305 

Upgrade from Chromium 80.0.3987.106 to Chromium 80.0.3987.116 (1.5.x).

---

package.json

Fixes #8304
Related PR: brave/brave-core#4682
Uplift from: #8305

Upgrade from Chromium 80.0.3987.106 to Chromium 80.0.3987.116 (1.4.x).

---

CHANGELOG.md

Release notes for 1.3.x Hotfix 2

---

CHANGELOG.md

Release notes 1.3.x hotfix 2 (Spacing Fix)

---

package.json

Fixes #8379 
Related PR: brave/brave-core#4723

Upgrade from Chromium 80.0.3987.116 to Chromium 80.0.3987.122.

---

package.json

Fixes #8379
Related PR: brave/brave-core#4729
Uplift from #8380

Upgrade from Chromium 80.0.3987.116 to Chromium 80.0.3987.122 (1.4.x).

---

CHANGELOG.md

Release notes for 1.4.x

---

package.json

Fixes #8379
Related PR: brave/brave-core#4728
Uplift from #8380

Upgrade from Chromium 80.0.3987.116 to Chromium 80.0.3987.122 (1.5.x).

---

lib/util.js

Resolves https://github.com/brave/brave-browser/issues/7620

Visual changes for search accelerator button

---

package.json

Fixes #8379
Related PR: brave/brave-core#4727
Uplift from #8380 

Upgrade from Chromium 80.0.3987.116 to Chromium 80.0.3987.122 (1.6.x).

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/8443

fixed null error in ci pipeline

---

lib/start.js

Resolves https://github.com/brave/brave-browser/issues/8432
defined in the issue

Fixes start for release

---

lib/gitPatcher.js

Resolves https://github.com/brave/brave-browser/issues/8414

Fixes init for Ubuntu

---

lib/util.js

Manual uplift of https://github.com/brave/brave-browser/pull/8418

Visual changes for search accelerator button (uplift to 1.6.x)

---

lib/util.js

Manual uplift of https://github.com/brave/brave-browser/pull/8418

Visual changes for search accelerator button (uplift to 1.5.x)

---

package.json

Fixes #8499 
Related PR: https://github.com/brave/brave-core/pull/4817

Upgrade from Chromium 80.0.3987.122 to Chromium 80.0.3987.132.

---

package.json

Fixes #8499
Related PR: brave/brave-core#4825
Uplift from: #8500 

Upgrade from Chromium 80.0.3987.122 to Chromium 80.0.3987.132 (1.4.x).

---

package.json

Fixes #8499
Related PR: brave/brave-core#4827
Uplift from: #8500

Upgrade from Chromium 80.0.3987.122 to Chromium 80.0.3987.132 (1.6.x).

---

package.json

Fixes #8499
Related PR: brave/brave-core#4826
Uplift from: #8500

Upgrade from Chromium 80.0.3987.122 to Chromium 80.0.3987.132 (1.5.x).

---

CHANGELOG.md

Release notes for 1.4.x Hotfix 1

---

package-lock.json

Related: https://github.com/brave/brave-browser/issues/8588

Updates acorn to v7.1.1

---

scripts/lint.py

Fix #8599 
Change: https://chromium.googlesource.com/chromium/tools/depot_tools/+/a12175c2a7a9f79c3296068a022ac4f3051f8600%5E%21/#F0
1. Run `npm run lint` to confirm it works without any issues.

Fix 8599: Update GetChange

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/8611

removed audit deps

---

scripts/lint.py

Uplift for: https://github.com/brave/brave-browser/pull/8600
Fix  https://github.com/brave/brave-browser/issues/8599
1. Run `npm run lint` to confirm it works without any issues.

Update GetChange to use 3 arguments (Uplift For 1.5.x)

---

lib/test.js

Fixes https://github.com/brave/brave-browser/issues/8670

Fix failing tests for macOS RE: speedreader

---

Jenkinsfile

With https://github.com/brave/brave-core/pull/4943

synced ci pipeline

---

CHANGELOG.md

Release notes for 1.5.x

---

package.json

Fixes #8728 
Related PR: brave/brave-core#4974

Upgrade from Chromium 80.0.3987.132 to Chromium 80.0.3987.149.

---

package.json

Fixes #8728
Related PR: brave/brave-core#4981
Uplift from: #8729

Upgrade from Chromium 80.0.3987.132 to Chromium 80.0.3987.149 (1.7.x).

---

package.json

Fixes #8728
Related PR: brave/brave-core#4982
Uplift from: #8729

Upgrade from Chromium 80.0.3987.132 to Chromium 80.0.3987.149 (1.5.x).

---

Jenkinsfile

added symbols upload to all platforms

---

CHANGELOG.md

Release notes for 1.5.x Hotfix 1

---

CHANGELOG.md

Release notes for 1.5.x Hotfix 2

---

lib/config.js

required for https://github.com/brave/brave-core/pull/5064

pass brave_channel in env

---

package.json

Fixes #8878 
Related PR: brave/brave-core#5075

Upgrade from Chromium 81.0.4044.69 to Chromium 81.0.4044.83.

---

package.json

Fixes https://github.com/brave/brave-browser/issues/8947
Related https://github.com/brave/brave-core/pull/5130

Upgrade from Chromium 80.0.3987.149 to Chromium 80.0.3987.162

---

README.md

Remove reference to tracking-protection from README.md

---

README.md

Only makes changes to the READEME.md

Change reference to ad-block to adblock-rust

---

Jenkinsfile

fixed multiple issues with ci pipeline

---

CHANGELOG.md

Release notes for 1.5.x Hotfix 3

---

package.json

Fixes https://github.com/brave/brave-browser/issues/8997
Related https://github.com/brave/brave-core/pull/5148

Upgrade from Chromium 80.0.3987.162 to Chromium 80.0.3987.163

---

Jenkinsfile

For https://github.com/brave/brave-browser/issues/8979

fixed missing param init for chromium repo

---

CHANGELOG.md

Release notes for 1.5.x Hotfix4

---

CHANGELOG_ANDROID.md

[Android] Release notes for 1.5.x

---

CHANGELOG_ANDROID.md

[Android] Release notes for 1.5.x Hotfix #1

---

Jenkinsfile

uplift PR 9007 to 1.8.x

---

package.json

Fixes https://github.com/brave/brave-browser/issues/9000
Related https://github.com/brave/brave-core/pull/5150
See https://github.com/brave/brave-browser/issues/9000

Upgrade from Chromium 81.0.4044.83 to Chromium 81.0.4044.92

---

Jenkinsfile

remove-chromium-src-param

---

CHANGELOG_ANDROID.md

[Android] Release notes for 1.5.x Hotfix 2

---

package.json

fixed chromium branch

---

package.json

reverted to chromium tag

---

lib/util.js

remove extra fetch that was slowing things down

---

lib/build.js
lib/createDist.js

move apks signing on Android to create_dist

---

scripts/sync.js

Fixes https://github.com/brave/brave-browser/issues/9127

fail on errors

---

Jenkinsfile

Closes https://github.com/brave/devops/issues/2907

added signing for android in ci pipeline

---

lib/util.js

don't change the brave-core remote

---

Jenkinsfile

added signing for android in ci pipeline 1.7.x

---

Jenkinsfile
scripts/sync.js

Uplift parts of https://github.com/brave/brave-browser/pull/9125 to 1.7.x

Sync and PR builder fixes

---

scripts/sync.js

Add process.exit to sync

---

Jenkinsfile

increased init timeout in ci pipeline

---

CHANGELOG_DESKTOP.md

Update 1.7.x Release notes

---

lib/build.js
lib/createDist.js

Uplift for https://github.com/brave/brave-browser/pull/9115

Pr9115 android signing uplift 1.8.x

---

lib/config.js
lib/util.js
package.json
scripts/sync.js
scripts/updatePatches.js

Fixes #8308
Fixes #8878 
Fixes #9000 
Related PR: brave/brave-core#5204
Uplift from #8309 
Uplift from #8879
Uplift from #9001

Upgrade from Chromium 80.0.3987.163 to Chromium 81.0.4044.92 (1.7.x)

---

Jenkinsfile

ci pipeline init timeout 1.8.x

---

Jenkinsfile

ci pipeline init timeout 1.7.x

---

lib/config.js
package.json

auto-generate the chromium repo url if it is not specified

---

Jenkinsfile

disabled python 3 for gclient

---

package.json

Fixes https://github.com/brave/brave-browser/issues/9251
Related https://github.com/brave/brave-core/pull/5268
See https://github.com/brave/brave-browser/issues/9251

Upgrade from Chromium 81.0.4044.92 to Chromium 81.0.4044.113

---

Jenkinsfile

I don't think Python is the root cause- there must be a specific config difference. Plus, we'll eventually need to switch to Python 3
I'd like to propose reverting and then continuing to find the root cause
----------
This reverts commit af4213d5248ff8c907686049b3c5ef9771805a8f, reversing
changes made to 6fb7321b6579ef79e91302b2316084d204909e04.

Revert "Merge pull request #9259 from brave/mplesa-ci-pipeline-gclient-py-version"

---

lib/config.js

Delete binance client id build arg on Android

---

Jenkinsfile

Closes https://github.com/brave/brave-browser/issues/9114

took out build step for android

---

Jenkinsfile

For https://github.com/brave/brave-browser/issues/9114

ci pipeline sync 1.8.x

---

Jenkinsfile

For https://github.com/brave/brave-browser/issues/9114

ci pipeline sync 1.7.x

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/9252
Fixes https://github.com/brave/brave-browser/issues/9251
Related https://github.com/brave/brave-core/pull/5277

Upgrade from Chromium 81.0.4044.92 to Chromium 81.0.4044.113 (uplift to 1.8.x)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/9252
Fixes https://github.com/brave/brave-browser/issues/9251
Related https://github.com/brave/brave-core/pull/5279

Upgrade from Chromium 81.0.4044.92 to Chromium 81.0.4044.113 (uplift to 1.7.x)

---

lib/config.js
lib/util.js
scripts/sync.js

Fixes https://github.com/brave/brave-browser/issues/9308

simplify init/sync and make them compatible with GIT_CACHE_DIR

---

lib/util.js

use correct brave-core branch name

---

lib/util.js

Uplift of https://github.com/brave/brave-browser/pull/9343

use correct brave-core branch name (uplift to 1.9.x)

---

lib/util.js

restore accidentally removed `--with_branch_heads`

---

package.json

Fixes #9361
Related PR: brave/brave-core#5309

Upgrade from Chromium 81.0.4044.113 to Chromium 81.0.4044.122.

---

README.md

Remove link to deprecated browser-android-tabs repo in README.md

---

Jenkinsfile

Temporarily disable gclient/git caching

---

Jenkinsfile

Temporarily disable gclient/git caching (1.9.x) 

---

Jenkinsfile

Temporarily disable gclient/git caching (1.7.x)

---

Jenkinsfile

Temporarily disable gclient/git caching (1.8.x)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/9362
Fixes https://github.com/brave/brave-browser/issues/9361
Related https://github.com/brave/brave-core/pull/5324

Upgrade from Chromium 81.0.4044.113 to Chromium 81.0.4044.122. (uplift to 1.9.x)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/9362
Fixes https://github.com/brave/brave-browser/issues/9361
Related https://github.com/brave/brave-core/pull/5325

Upgrade from Chromium 81.0.4044.113 to Chromium 81.0.4044.122. (uplift to 1.8.x)

---

package.json

Uplift of https://github.com/brave/brave-browser/pull/9362
Fixes https://github.com/brave/brave-browser/issues/9453
Related https://github.com/brave/brave-core/pull/5326

Upgrade from Chromium 81.0.4044.113 to Chromium 81.0.4044.122. (uplift to 1.7.x)

---

lib/l10nUtil.js

Fix https://github.com/brave/brave-browser/issues/9266

Modify safe browsing label

---

.github/PULL_REQUEST_TEMPLATE.md

Update PULL_REQUEST_TEMPLATE.md with new FP wiki page

---

package.json

Fixes https://github.com/brave/brave-browser/issues/9493
Related https://github.com/brave/brave-core/pull/5398
See https://github.com/brave/brave-browser/issues/9493

Upgrade from Chromium 81.0.4044.122 to Chromium 81.0.4044.129

---

lib/l10nUtil.js

Fix safe browsing label (uplift to 1.9)

---

lib/l10nUtil.js

Fix safe browsing label (uplift to 1.8)

---

Jenkinsfile

separated ci pipeline

---

CHANGELOG_DESKTOP.md

Release notes for 1.8.x Hotfix1

---

package.json

Fixes #9632 
Related PR: brave/brave-core#5463

Upgrade from Chromium 81.0.4044.129 to Chromium 81.0.4044.138

---

package.json

Fixes #9632
Related PR: brave/brave-core#5468
Uplift from #9633

Upgrade from Chromium 81.0.4044.129 to Chromium 81.0.4044.138 (1.8.x).

---

Jenkinsfile

With https://github.com/brave/brave-core/pull/5460

fixed draft PR skip, slack and PR statuses in CI pipeline

---

CHANGELOG_DESKTOP.md

Release notes for 1.8.x Hotfix2

---

package.json

Fixes #9632
Related PR: brave/brave-core#5467
Uplift from #9633 

Upgrade from Chromium 81.0.4044.129 to Chromium 81.0.4044.138 (1.9.x)

---

Jenkinsfile

fixed pr details init

---

CHANGELOG_ANDROID.md

Release notes for Android 1.7.x

---

CHANGELOG_ANDROID.md

Release notes for Android 1.8.x

---

CHANGELOG_DESKTOP.md

Release notes for 1.8.x Hotfix 3

---

CHANGELOG_ANDROID.md

Release notes for Android 1.8.x Hotfix 1

---

CHANGELOG_DESKTOP.md

Release notes for 1.9.x

---

CONTRIBUTING.md

I haven’t performed the steps on the checklist because it’s a short documentation fix (the previous link was broken). Didn’t seem worth it to open an issue beforehand.

CONTRIBUTING.md: distinguish between desktop and android release notes

---

Jenkinsfile

refactored ci pipeline

---

Jenkinsfile

ci pipeline sync 1.10.x

---

Jenkinsfile

ci pipeline sync 1.9.x

---

lib/test.js
scripts/commands.js

Resolves https://github.com/brave/brave-browser/issues/9965

Adds support for vmodule

---

scripts/audit.js

Uplift of https://github.com/brave/brave-browser/pull/9952
Fixes https://github.com/brave/brave-browser/issues/9951

Using audit_deps.py for npm audit (uplift to 1.10.x)

---

scripts/audit.js

Uplift of https://github.com/brave/brave-browser/pull/9952
Fixes https://github.com/brave/brave-browser/issues/9951

Using audit_deps.py for npm audit (uplift to 1.9.x)

---

CHANGELOG_DESKTOP.md

Release notes for 1.9.x Hotfix 1

---

lib/util.js

don't use -D because users could lose their local git branches

---

lib/config.js
lib/test.js
lib/util.js
package.json

Fixes #9760
Related PR: brave/brave-core#5735
Uplift from #9765

Upgrade from Chromium 81 to Chromium 83 (1.10.x).

---

.github/ISSUE_TEMPLATE/desktop.md

Add OS/Desktop label for desktop issues

---

CHANGELOG_DESKTOP.md

Release notes for 1.9.x Hotfix 2

---

CHANGELOG_ANDROID.md

[Android] Release notes for 1.9.x HF1

---

lib/config.js

Fixes https://github.com/brave/brave-browser/issues/10177
At some point in Chromium bump debug builds broke due to the enabling of `fatal_linker_errors` argument. This isn't an issue on Debug since we do not ship with Debug binaries
We enable dSYMs for iOS debug mode since we primarily use it for debugging and breakpoints. Without dSYMs, Xcode breakpoints do not work correctly (and crashes do not land on the source lines)

Fix iOS debug builds and generate dSYMs for iOS debug builds

---

package.json

Fixes #10075 
Related PR: brave/brave-core#5734

Upgrade from Chromium 83.0.4103.61 to Chromium 83.0.4103.97.

---

lib/whitelistedUrlPrefixes.js

Resolves https://github.com/brave/brave-browser/issues/10192

Whitelist brave sync v2 servers in the network auditor

---

README.md
lib/config.js
lib/test.js

Resolves: #10182 
For developers: Before building please use the npmconfig specified here - https://github.com/brave/devops/wiki/npm-config-for-Brave-Developers
1. Open Brave Browser with a clean profile
2. Wait for ~5 mins  and confirm `<user-data-dir>/Safe Browsing` has the `*.store` files
3. Using Little Snitch or fiddler ensure that we are not reaching out to googleapis.com
4. Navigate to `https://testsafebrowsing.appspot.com` - Confirm that webpage tests work.

Fix 10182: Set SafeBrowsing endpoint at build time

---

README.md
lib/config.js
lib/test.js

This reverts commit 76b9b304c1010a4744f2fe596da0a9d04fa09b66, reversing
changes made to e741a15943bc13c828620ea661dc14715d883f1c.
Reverts fix for https://github.com/brave/brave-browser/issues/10182

Revert "Merge pull request #10187 from brave/safebrowsing_endpoint"

---

CHANGELOG_DESKTOP.md

Release notes for 1.10.x

---

package.json

Fixes #10268
Related PR: brave/brave-core#5845

Upgrade from Chromium 83.0.4103.97 to Chromium 83.0.4103.106

---

scripts/sync.js

The removed line breaks the build if a branch in a-c cannot be
checked out.

Drop unwanted logging.

---

lib/util.js

let `util.run` handle logging

---

package.json

Fixes #10268
Related PR: brave/brave-core#5862
Uplift from #10270

Upgrade from Chromium 83.0.4103.97 to Chromium 83.0.4103.106 (1.11.x).

---

package.json

Fixes #10268
Related PR: brave/brave-core#5861
Uplift from #10270 

Upgrade from Chromium 83.0.4103.97 to Chromium 83.0.4103.106 (1.10.x).

---

CHANGELOG_DESKTOP.md

Release notes 1.10.x hotfix1

---

lib/config.js

Fix default 'Component' build for iOS

---

package.json

fix package

---

CHANGELOG_DESKTOP.md

Release notes for 1.10.x Hotfix 2

---

CHANGELOG_ANDROID.md

[Android] Release notes for 1.10.x

---

package.json

Fixes #10406
Related PR: brave/brave-core#5917

Upgrade from Chromium 83.0.4103.106 to Chromium 83.0.4103.116

---

CHANGELOG_ANDROID.md

[Android] Release notes for 1.10.x Hotfix 1

---

package.json

Fixes #10406
Related PR: brave/brave-core#5922
Uplift from #10410

Upgrade from Chromium 83.0.4103.106 to Chromium 83.0.4103.116 (1.11.x).

---

package.json

Fixes #10406
Related PR: brave/brave-core#5921
Uplift from #10410

Upgrade from Chromium 83.0.4103.106 to Chromium 83.0.4103.116 (1.10.x).

---

CHANGELOG_DESKTOP.md

Release notes for 1.10.x Hotfix 3

---

lib/test.js

required for https://github.com/brave/brave-core/pull/5493

don't run ninja for each rust lib

---

CHANGELOG_ANDROID.md

[Android] Release notes for 1.10.x HF2

---

lib/config.js

This PR required for https://github.com/brave/brave-browser/issues/10203 .
Requires brave-core PR is https://github.com/brave/brave-core/pull/5361 .
Build this PR along with b-b branch `android-sync-v2` and ensure it is built and sync v2 works on Android.

Android sync v2 needs enable_brave_sync flag

---

package.json

Fixes #10364 
Related PR: brave/brave-core#5679

Upgrade from Chromium 83 to Chromium 84

---

package.json

Fixes #10594
Related PR: brave/brave-core#6025

Upgrade from Chromium 84.0.4147.68 to Chromium 84.0.4147.85.

---

package.json

Fixes #10594
Related PR: brave/brave-core#6054
Uplift from #10595

Upgrade from Chromium 84.0.4147.68 to Chromium 84.0.4147.85 (1.11.x).

---

package.json

Fixes #10594
Related PR: brave/brave-core#6053
Uplift from #10595 

Upgrade from Chromium 84.0.4147.68 to Chromium 84.0.4147.85 (1.12.x).

---

package.json

Fixes #10714 
Related PR: brave/brave-core#6066

Upgrade from Chromium 84.0.4147.85 to Chromium 84.0.4147.89

---

package.json

Fixes #10714
Related PR: brave/brave-core#6068
Uplift from #10715 

Upgrade from Chromium 84.0.4147.85 to Chromium 84.0.4147.89 (1.12.x).

---

package.json

Fixes #10714
Related PR: brave/brave-core#6069
Uplift from #10715

Upgrade from Chromium 84.0.4147.85 to Chromium 84.0.4147.89 (1.11.x).

---

.github/ISSUE_TEMPLATE/desktop.md

Removes dev from the create issue template

---

lib/gnCheck.js
package.json
scripts/commands.js

Uplift of https://github.com/brave/brave-browser/pull/10599
Resolves : https://github.com/brave/brave-browser/issues/9365

Fix 9365: Add gn check to npm scripts (Uplift 1.12.x)

---

CHANGELOG_DESKTOP.md

Release notes for 1.11.x Hotfix1

---

package.json

Fixes #10950
Related PR: brave/brave-core#6225

Upgrade from Chromium 84.0.4147.89 to Chromium 84.0.4147.105

---

package.json

Fixes #10950
Related PR: brave/brave-core#6230
Uplift from #10951

Upgrade from Chromium 84.0.4147.89 to Chromium 84.0.4147.105 (1.12.x).

---

package.json

Fixes #10950
Related PR: brave/brave-core#6231
Uplift from #10951

Upgrade from Chromium 84.0.4147.89 to Chromium 84.0.4147.105 (1.11.x).

---

CHANGELOG_DESKTOP.md

Release notes for 1.11.x HF2

---

package.json

network_audit -> network-audit

---

.gitmodules

Requires https://github.com/brave/brave-core/pull/6278
See https://github.com/brave/brave-browser/issues/11028

remove git submodules that are no longer needed in brave-browser

---

CHANGELOG_ANDROID.md

Add Release notes for Android 1.11.x

---

.github/ISSUE_TEMPLATE/DesktopAndroid.md
.github/ISSUE_TEMPLATE/android-issue.md

Adding new combined template for both Desktop & Android

---

package.json

Fixes #11025 
Related PR: brave/brave-core#6276

Upgrade from Chromium 84.0.4147.105 to Chromium 84.0.4147.111

---

package.json

Fixes #11025
Related PR: brave/brave-core#6364
Uplift from #11026 

Upgrade from Chromium 84.0.4147.105 to Chromium 84.0.4147.111 (1.13.x).

---

package.json

Fixes #11025
Related PR: brave/brave-core#6365
Uplift from #11026

Upgrade from Chromium 84.0.4147.105 to Chromium 84.0.4147.111 (1.12.x).

---

package.json

Fixes #10636
Related PR: brave/brave-core#6042

Upgrade from Chromium 84 to Chromium 85

---

Jenkinsfile

For https://github.com/brave/devops/issues/3458
With https://github.com/brave/brave-core/pull/6341

split ci pipeline

---

package.json

Fixes #11153 
Related PR: brave/brave-core#6387

Upgrade from Chromium 84.0.4147.111 to Chromium 84.0.4147.125

---

package.json

Fixes #11153
Related PR: brave/brave-core#6393
Uplift from #11154

Upgrade from Chromium 84.0.4147.111 to Chromium 84.0.4147.125 (1.12.x).

---

Jenkinsfile

For https://github.com/brave/devops/issues/3495 and https://github.com/brave/devops/issues/3496
With https://github.com/brave/brave-core/pull/6409

split ci pipeline by platform

---

package.json

Fixes #11207 
Related PR: brave/brave-core#6407

Upgrade from Chromium 85.0.4183.59 to Chromium 85.0.4183.69.

---

package.json

Fixes #11303 
Related PR: brave/brave-core#6445

Upgrade from Chromium 84.0.4147.125 to Chromium 84.0.4147.135 (1.12.x).

---

CHANGELOG_DESKTOP.md

Release notes for 1.12.x Hotfix #1

---

Jenkinsfile

fixed ci pipeline params

---

package.json

Fixes #11332
Related PR: brave/brave-core#6470
Uplift from #11335 

Upgrade from Chromium 85.0.4183.69 to Chromium 85.0.4183.78 (1.14.x).

---

package.json

Fixes #11332
Related PR: brave/brave-core#6471
Uplift from #11335

Upgrade from Chromium 85.0.4183.69 to Chromium 85.0.4183.78 (1.13.x).

---

package.json

Fixes #11401
Related PR: brave/brave-core#6481

Upgrade from Chromium 85.0.4183.78 to Chromium 85.0.4183.83

---

package.json

Fixes #11401
Related PR: brave/brave-core#6489
Uplift from #11402 

Upgrade from Chromium 85.0.4183.78 to Chromium 85.0.4183.83 (1.14.x).

---

package.json

Fixes #11401
Related PR: brave/brave-core#6490
Uplift from #11402

Upgrade from Chromium 85.0.4183.78 to Chromium 85.0.4183.83 (1.13.x).

---

CHANGELOG_ANDROID.md

Fixes incorrect CR listed

---

docs/source/installing-brave.rst

This is a partial solution for brave/brave-browser#8690.
Thanks to @programmer-04 for confirming the installation instructions in https://github.com/brave/brave-browser/pull/9424.

Add Manjaro instructions to unofficial packages

---

docs/source/installing-brave.rst

Closes https://github.com/brave/brave-browser/issues/8690.

Add installation instructions for Arch Linux

---

package.json

Fixes #11621 
Related PR: brave/brave-core#6589

Upgrade from Chromium 85.0.4183.83 to Chromium 85.0.4183.102

---

package.json

Fixes #11621
Related PR: brave/brave-core#6604
Uplift from #11622

Upgrade from Chromium 85.0.4183.83 to Chromium 85.0.4183.102 (1.13.x).

---

CHANGELOG_DESKTOP.md

Release notes for 1.13.x Release #3

---

CHANGELOG_ANDROID.md

Release notes for 1.13.x Release #4

---

package.json

Fixes #10884
Related PR: brave/brave-core#6195

Upgrade from Chromium 85 to Chromium 86.

---

.github/ISSUE_TEMPLATE/android-issue.md
.github/ISSUE_TEMPLATE/desktop.md

Fix https://github.com/brave/brave-browser/issues/11727

OS is specified by labels and not the title

---

package.json

Fix https://github.com/brave/brave-browser/issues/11748.

sync test-security script with brave-core

---

package.json

Fixes #11747
Related PR: brave/brave-core#6662

Upgrade from Chromium 86.0.4240.30 to Chromium 86.0.4240.42.

---

CHANGELOG_ANDROID.md

Add Release notes for Android 1.14.x Release

---

package.json

Fixes #10884
Fixes #11747
Related PR: brave/brave-core#6677
Uplifts from #10886, #11750 

Upgrade from Chromium 85 to Chromium 86 (1.15.x).

---

package.json

Fixes #11793 
Related PR: brave/brave-core#6675

Upgrade from Chromium 85.0.4183.102 to Chromium 85.0.4183.121

---

CHANGELOG_DESKTOP.md

Release notes for 1.14.x Release #3

---

CHANGELOG_ANDROID.md

Release notes for Android 1.14.x #3

---

package.json

Fixes #11827 
Related PR: brave/brave-core#6690

Upgrade from Chromium 85.0.4183.121 to Chromium 85.0.4183.127.

---

package.json

Fixes #11829 
Related PR: brave/brave-core#6691

Upgrade from Chromium 86.0.4240.42 to Chromium 86.0.4240.55

---

CHANGELOG_ANDROID.md

Release notes for 1.14.x Release #4

---

package.json

Fixes #11829
Related PR: brave/brave-core#6696
Uplift from #11833 

Upgrade from Chromium 86.0.4240.42 to Chromium 86.0.4240.55 (1.15.x).

---

Jenkinsfile

add terminate_node param for CI

---

package.json

Fixes #11956
Related PR: brave/brave-core#6752

Upgrade from Chromium 86.0.4240.55 to Chromium 86.0.4240.68

---

package.json

Fixes #11956
Related PR: brave/brave-core#6759
Uplift from #11957 

Upgrade from Chromium 86.0.4240.55 to Chromium 86.0.4240.68 (1.16.x).

---

package.json

Fixes #11956
Related PR: brave/brave-core#6760
Uplift from #11957

Upgrade from Chromium 86.0.4240.55 to Chromium 86.0.4240.68 (1.15.x).

---

docs/source/_static/custom.css
docs/source/conf.py
docs/source/installing-brave.rst

Resolves #11978
Resolves #11979
Once these changes are published, navigate to https://brave-browser.readthedocs.io/en/latest/installing-brave.html and confirm that a warning regarding Linux is displayed at the top of the page, and that no failed Stylesheet calls are found in the Network tab of the developer tools.

Documentation Improvements

---

package.json

Fixes #12002 
Related PR: brave/brave-core#6773

Upgrade from Chromium 86.0.4240.68 to Chromium 86.0.4240.72

---

package.json

Fixes #12002
Related PR: brave/brave-core#6778
Uplift from #12003

Upgrade from Chromium 86.0.4240.68 to Chromium 86.0.4240.72 (1.16.x).

---

package.json

Fixes #12002
Related PR: brave/brave-core#6777
Uplift from #12003 

Upgrade from Chromium 86.0.4240.68 to Chromium 86.0.4240.72 (1.15.x).

---

package.json

Fixes #12021 
Related PR: brave/brave-core#6799

Upgrade from Chromium 86.0.4240.72 to Chromium 86.0.4240.75

---

package.json

Fixes #12021
Related PR: brave/brave-core#6801
Uplift from #12023

Upgrade from Chromium 86.0.4240.72 to Chromium 86.0.4240.75 (1.16.x).

---

package.json

Fixes #12021
Related PR: brave/brave-core#6800
Uplift from #12023 

Upgrade from Chromium 86.0.4240.72 to Chromium 86.0.4240.75 (1.15.x).

---

CHANGELOG_DESKTOP.md

Release notes for 1.15.x Release #1

---

package.json

Fixes #12100 
Related PR: brave/brave-core#6837

Upgrade from Chromium 86.0.4240.75 to Chromium 86.0.4240.80

---

package.json

Fixes #12100
Related PR: brave/brave-core#6848
Uplift from #12101 

Upgrade from Chromium 86.0.4240.75 to Chromium 86.0.4240.80 (1.15.x).

---

package.json

Fixes #12100
Related PR: brave/brave-core#6849
Uplift from #12101

Upgrade from Chromium 86.0.4240.75 to Chromium 86.0.4240.80 (1.16.x).

---

CHANGELOG_ANDROID.md

Release notes for 1.15.x Release #3

---

package.json

Fixes #12124 
Related PR: brave/brave-core#6854

Upgrade from Chromium 86.0.4240.80 to Chromium 86.0.4240.99.

---

package.json

Fixes #12124
Related PR: brave/brave-core#6862
Uplift from #12125 

Upgrade from Chromium 86.0.4240.80 to Chromium 86.0.4240.99 (1.15.x).

---

package.json

Fixes #12124
Related PR: brave/brave-core#6863
Uplift from #12125

Upgrade from Chromium 86.0.4240.80 to Chromium 86.0.4240.99 (1.16.x).

---

package.json

Fixes #12225 
Related PR: brave/brave-core#6905

Upgrade from Chromium 86.0.4240.99 to Chromium 86.0.4240.111

---

package.json

Fixes #12225
Related PR: brave/brave-core#6907
Uplift from #12228 

Upgrade from Chromium 86.0.4240.99 to Chromium 86.0.4240.111 (1.15.x).

---

package.json

Fixes #12225
Related PR: brave/brave-core#6908
Uplift from #12228

Upgrade from Chromium 86.0.4240.99 to Chromium 86.0.4240.111 (1.16.x).

---

package.json

Fixes #12225
Related PR: brave/brave-core#6911
Uplift from #12228

Upgrade from Chromium 86.0.4240.99 to Chromium 86.0.4240.111 (1.17.x).

---

CHANGELOG_DESKTOP.md

Release notes for 1.15.x Release #4

---

CHANGELOG_DESKTOP.md

Release notes for 1.16.x Release #1

---

package.json

Fixes #11534
Related PR: brave/brave-core#6554

Upgrade from Chromium 86 to Chromium 87.

---

package.json

Fixes #12395 
Related PR: brave/brave-core#6986

Updated from Chromium 87.0.4280.27 to Chromium 87.0.4280.40.

---

CHANGELOG_ANDROID.md

Release notes for 1.16.x Release #2

---

CHANGELOG_ANDROID.md

Release notes for 1.16.x Release #2 (Fix)

---

package.json

Fixes #12471
Related PR: brave/brave-core#7018

Upgraded from Chromium 86.0.4240.111 to Chromium 86.0.4240.183 (1.17.x).

---

package.json

Fixes #12471
Related PR: brave/brave-core#7022

Upgraded from Chromium 86.0.4240.111 to Chromium 86.0.4240.183 (1.16.x).

---

CHANGELOG_DESKTOP.md

Release notes for 1.16.x Release #3

---

package.json

Fixes #12479
Related PR: brave/brave-core#7027

Upgraded from Chromium 86.0.4240.183 to Chromium 86.0.4240.185.

---

package.json

Fixes #12479
Related PR: brave/brave-core#7038
Uplift from #12480

Upgraded from Chromium 86.0.4240.183 to Chromium 86.0.4240.185 (1.16.x).

---

CHANGELOG_ANDROID.md

Release notes for 1.16.x Release #4

---

package.json

Fixes #12519
Related PR: brave/brave-core#7058

Updated from Chromium 87.0.4280.40 to Chromium 87.0.4280.47.

---

package.json

Fixes #12527 
Related PR: brave/brave-core#7061

Updated from Chromium 87.0.4280.47 to Chromium 87.0.4280.49.

---

package.json

Fixes #11534
Related PR: brave/brave-core#7085
Uplifts from:
#11535
#12399
#12522
#12528

Upgrade from Chromium 86 to Chromium 87 (1.17.x)
