lib/start.js, scripts/commands.js
Fix #150
Related: https://github.com/brave/brave-core/pull/87
Documented here: https://github.com/brave/brave-browser/wiki/Debugging-brave-extension
You can do this with:
```
npm run start -- --disable_brave_extension
```
or
```
yarn start --disable_brave_extension
```
=> Add CLI arg for starting without Brave extension

lib/config.js, scripts/commands.js
To build with specific channel, pass channel option to build.
Options can be beta, canary, dev and release.
Issue: https://github.com/brave/brave-browser/issues/10
Depends on https://github.com/brave/brave-core/pull/78
=> Add channel option to build command

lib/config.js
With default `symbol_level=2` x86 brave binary reached 6.4 GiB, this is beyond ELF32 can handle and the next steps had failed.
=> symbol_level is set to 1 for x86 Linux

lib/test.js, scripts/commands.js
Fix https://github.com/brave/brave-browser/issues/238
**Example running all tests:**
`npm run test -- brave_browser_tests`
**Example running some specific tests:**
`npm run test -- brave_browser_tests --filter=BraveContentSettingsObserverBrowserTest.*`
I also updated test docs here:
https://github.com/brave/brave-browser/wiki/Tests
=> Add the ability to filter tests via npm

lib/test.js, scripts/commands.js
Fix https://github.com/brave/brave-browser/issues/262
The wiki is also updated.
This adds an extra optional argument to run tests in Release mode
npm run test -- brave_browser_tests Release
=> Allow running tests in Release

.gitignore, lib/build.js, lib/config.js, lib/createDist.js, lib/util.js, scripts/commands.js, scripts/sync.js, src/.gitkeep
These are various improvements/fixes I added while working on the CI builds.
* Add mac signing id and keychain parameters
* Add gclient_verbose option to sync
* Allow util.js func options to be set with out explicit cwd
* Use git -C option to specify repos
Switching directories on windows can cause strange issues in
the case of depot_tools assumingly because the shell will see
the git in the current directory and run that instead of what is
run elsewhere.
* Fix setting references on the command line with yarn sync.
Commander camelcases options with dashs which breaks when used with
'--brave-core_ref'. This also renames the option to --brave_core_ref
Have been using in the new CI infrastructure.
Will likely need to come back and start adding some tests for ./lib/* (none currently).
=> Update scripts for create_dist

package.json
The current version of uglify we are using doesn't seem to properly support ES6 and wasn't properly transpiling brave-ui which targets ES6 as well.
This just adds the dependency, see https://github.com/brave/brave-core/pull/151 for the test plan and fix.
address #309
test plan: none
=> add uglifyjs-webpack-plugin as dep

lib/config.js
Fixes: https://github.com/brave/brave-browser/issues/204 - Adding Safe Browsing API key to config
Similar to: https://github.com/brave/browser-laptop-bootstrap/blob/master/lib/config.js#L33
=> Adding safe browsing api key to config

lib/start.js, scripts/commands.js
Fix https://github.com/brave/brave-browser/issues/335
=> Add --disable_pdfjs_extension switch

lib/chromiumRebaseL10n.js, lib/l10nUtil.js, package.json, scripts/commands.js
Fix https://github.com/brave/brave-browser/issues/364
This replaces the following steps in the Brave wiki with a single command `npm run chromium_rebase_l10n`:
---
Chromium rebase wiki steps getting replaced:
```
cd brave
cp ../chrome/app/chromium_strings.grd app/brave_strings.grd
```
Open up `app/brave_strings.grd` and replace `settings_chromium_strings.grdp` with `settings_brave_strings.grdp`
Also apply these replacements:
```
%s/Google Chrome/Brave/g
%s/Chromium/Brave/g
%s/Chrome/Brave/g
%s/Google/Brave/g
%s/The Brave Authors. All rights reserved./Brave Software Inc. All rights reserved./g
%s/The Brave Authors/Brave Software Inc./g
```
`cp ../chrome/app/settings_chromium_strings.grdp app/settings_brave_strings.grdp`
Open up the file and apply these replacements:
```
%s/Google …
```
=> Provide a script to do GRD string upgrades for Chromium rebasing

lib/build.js, lib/config.js, lib/createDist.js, lib/util.js, scripts/sync.js
Few things to clean up post #229 merge
* Fix `yarn run sync --<project>_ref=` command
* Set build target through the config for create_dist
* Check config.gClientVerbose directly and remove unused options
* buildMuon
* Renamed to buildTarget
* Now uses build target set in config
Just manually right now across various machines (which is likely why so many bugs are getting missed here). Have this ticket open for adding testing to the build tools in general https://github.com/brave/brave-browser/issues/304.
=> Cleanup for #229

lib/build.js, scripts/commands.js
We sometimes copies upstream file in our chromium_src.
Then, our cc_wrapper scripts replaces original file with same file in chromium_src
if existed.
However, if we only modify copied file, gn doens't trigger rebuild
when original file isn't touched.
To fix this, use this option to touch original file.
To touch all overridden files, use --touch_overridden_files='*'.
To touch specific files contain specific strings, use --touch_overridden_files='manifest'.
This will touch original chrome_manifest_handlers.cc file.
Close https://github.com/brave/brave-browser/issues/352
=> Introduce --touch_overridden_files option to build command

lib/config.js
Example: widevine_cmdm_compoennt_installer.cc is included in a generated jumbo .cc file via a relative path.
Fix https://github.com/brave/brave-browser/issues/411
It will be re-added eventually in https://github.com/brave/brave-browser/issues/410
=> Disable use_jumbo_build for now

lib/updatePatches.js, lib/util.js
By overwriting images, we can use our resources w/o changing grd file.
Also, png file shouldn't be included to patch set.
This PR is introduced for https://github.com/brave/brave-core/pull/158.
Related issue: https://github.com/brave/brave-browser/issues/317
=> Overwrite chrome/app/theme/chromium resources with ours

lib/config.js
This turns off distro version checks for non-official builds
This is in reference to https://github.com/brave/brave-browser/issues/305
Run a liux build with associated patches
=> add toggle for enable_distro_version_check

lib/updatePatches.js, lib/util.js
Chromum compares pre-installed midl files and generated midl files from
IDL file during the build to check integrity.
Generated files during the build time and upstream generated files are
different because we use different IDL file(google_update_idl.idl) for google update.
So, we should copy our pre-installed files to overwrite upstream
pre-installed files.
Also, these files should not be the target of update_patches command.
issue: https://github.com/brave/brave-browser/issues/179
=> Copying our pre-generated midl files to overwrite upstream midl files

lib/config.js
Reverts brave/brave-browser#306
Seeing the error below when building on mac and windows, reverting this PR fixes it.
```
yrliou@jocelyn-mbpr.local:~/brave$ yarn build
yarn run v1.3.2
$ node ./scripts/commands.js build
update branding...
building brave...
update omaha midl files...
gn gen /Users/yrliou/brave/src/out/Debug --args="safe_browsing_mode=1 root_extra_deps=[\"//brave\"] is_component_build=true proprietary_codecs=true ffmpeg_branding=\"Chrome\" enable_nacl=false enable_widevine=true target_cpu=\"x64\" is_official_build=false is_debug=true dcheck_always_on=true brave_channel=\"\" google_api_key=\"AIzaSyAH90V94EcZBP5oH7oc-mXQrSKgASVxER8\" brave_google_api_key=\"AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q\" brave_google_api_endpoint=\"https://www.googleapis.com/geolocation/v1/geolocate?ke …
```
=> Revert "add toggle for enable_distro_version_check"

scripts/commands.js
Issue: https://github.com/brave/brave-browser/issues/394
=> Use nightly instead of canary for channel option

lib/build.js, scripts/commands.js
As @bridiver 's comment(https://github.com/brave/brave-browser/pull/371#issuecomment-398268762), touching automatically would be much better than by using options.
Touch overridden file automatically when it is older than file in chromium_src.
Issue https://github.com/brave/brave-browser/issues/352
Close https://github.com/brave/brave-browser/issues/434
=> Touch overridden files automatically

lib/updatePatches.js, lib/util.js
Overwrite chrome/app/theme/chromium with brave/app/theme/brave.
With this, app icon of stable/development version ues ours.
chrome/app/theme path is excluded from updatePatches.
Issue https://github.com/brave/brave-browser/issues/10
`yarn start` for checking app icon for dev.
`yarn start Release` for checking app icon for stable.
`export CHROME_VERSION_EXTRA=dev; yarn start Release` for checking app icon for dev.
`export CHROME_VERSION_EXTRA=beta; yarn start Release` for checking app icon for beta.
=> Update app icon of stable/development version on linux

lib/config.js, lib/util.js, scripts/sync.js
This reverts commit 6c2176eee55bb9ef5dc52d655225d8129df36435.
This is necessary because chromium removed the `--cache-dir` option from gclient in favor of an environment variable [1]. This means we no longer need to pass this through to the build system -- an environment variable will do just as well.
[1] https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/1105473
=> Revert "add optional cache for cloning repos"

lib/updatePatches.js
Changed file list uses '/' separator.
However, result from path.join() on Windows uses '\' separator.
Because of this difference, files in chrome/app/theme are not excluded.
Close https://github.com/brave/brave-browser/issues/465
=> Don't create patch files under chrome/app/theme

lib/createDist.js
Current rename method just removes non-stable dist package file.
Need to re-enable that method when we determine final name of dist package name.
issue https://github.com/brave/brave-browser/issues/396
=> Skip rename method of linux dist

lib/updatePatches.js
=> warn patch maintainer to remove patch

lib/updatePatches.js, lib/util.js
Fix https://github.com/brave/brave-browser/issues/519
Please see https://github.com/brave/brave-core/pull/240 for more info.
Will need to be merged together with above.
=> Fix product_logo in chrome://versions and default_browser_infobar

package-lock.json, package.json
LESS has [hoek](https://npmjs.org/package/hoek) as a dep which was flagged by nodesecurity as vulnerable to prototype pollution.
More in https://nodesecurity.io/advisories/566
Updating LESS to v3.7.1 solves the issue by updating the dep.
Test plan:
- Go to newtab page
- Styles unaffected. Should still be able to properly parse LESS files.
=> update LESS to v3.7.1

package-lock.json, package.json, tsconfig.json
=> Adds TypeScript support

lib/start.js, scripts/commands.js
On MacOSX, update is triggered in official build.
On Windows, however, it isn't.
Close https://github.com/brave/brave-browser/issues/575
Check `--disable-brave-update` is attached when `yarn start` without `--enable_brave_update`
=> Disable software update by default when yarn start

lib/test.js
Issue: https://github.com/brave/brave-browser/issues/590
In browser tests, sparkle framework shouldn't be initialized.
`yarn test brave_browser_tests Release` w/o crash
=> Fix browser test crash on MacOS due to sparkle initialization

package.json
Bump version to 0.50.14
Was using this branch to avoid spamming people with pr bumps on build only changes (brave/brave-browser#594)
Realize this is a ugly hack so will try to figure something else out in the meantime
=> Bump patch version -- Release 0.50.14

lib/createDist.js
We don't make unstable named outputs anymore
#issue https://github.com/brave/brave-browser/issues/582
=> Don't need to try rename the unstable named deb/rpm files

lib/config.js, lib/l10nUtil.js, lib/test.js, package-lock.json, package.json, scripts/commands.js
Fix https://github.com/brave/brave-browser/issues/292
Related:
https://github.com/brave/brave-core/pull/257
https://github.com/brave/brave-extension/pull/50
- The use_egl fix is the same as muon
- There will be some GRD changes in a follow up PR
=> Upgrade to Chromium 68 

package-lock.json, package.json
Related: https://github.com/brave/brave-core/pull/282
We need to do a branch for 0.53.x so setting this up in 2 commits, one will go to the 0.53.x branch and the other one won't. '
https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule
=> Bump versions 0.54.x

lib/config.js
This PR modifies the build settings to allow using sccache on Windows. Three changes were required:
1. Don't pass the `-XClang find-bad-constructs` arg, as sccache incorrectly interprets the argument as an additional source file on Windows. We accomplish this by disabling `clang_use_chrome_plugins`.
1. Don't pass `/Brepro`, as it causes the following error when compiling with sccache enabled: `warning: argument unused during compilation: '-mno-incremental-linker-compatible'`. We accomplish this by enabling `use_thin_lto`.
1. Don't pass /Fp, as this setting seems to conflict with sccache. We accomplish this by setting `enable_precompiled_headers` to false.
---
=> Modify build settings to allow sccache support on Windows

lib/config.js
On Windows, we currently only support sccache for non-official
builds. This fix allows you to keep sccache enabled in your .npmrc and
it will be used when it's allowed and not used when its disallowed.
=> Don't set CC_WRAPPER if current build settings don't support sccache

lib/config.js, lib/util.js
With this, we can avoid patching chrome/BUILD.gn for this.
issue: https://github.com/brave/brave-browser/issues/652
=> Copy proper app icon to /chrome/app/theme/mac/app.icns

lib/test.js
Reverts brave/brave-browser#593
This can be reverted because browser can check sparkle updater is enabled or not in runtime.
In this commit(https://github.com/brave/brave-core/pull/271/commits/f8cf51c6755dd5718303e874408c9108fbab9d1c), runtime detection is implemented.
This can be merged after https://github.com/brave/brave-core/pull/271 is merged.
=> Revert "Fix browser test crash on MacOS due to sparkle initialization"

lib/start.js, lib/util.js, scripts/commands.js
Use different BRANDING file for different channel because Brave on
MacOS utilizes BRANDING file to get unique app name and id.
To do this, copy channel specific branding file such as BRANDING.beta to BRANDING.
Add channel option to start command because each channel app uses
different app name.
issue: https://github.com/brave/brave-browser/issues/469
This PR should be merged together with https://github.com/brave/brave-core/pull/298.
=> Enable different channel apps run simultaneously on MacOS

lib/config.js, lib/start.js, scripts/commands.js
=> Add ability to start single process and add ability to start unofficial Release builds on macOS

lib/build.js
We need to touch original icon files to trigger rebuild.
Close https://github.com/brave/brave-browser/issues/491
=> Touch overridden icon files when our icon file is updated

lib/config.js, lib/start.js
follow up PR for https://github.com/brave/brave-browser/pull/659#discussion_r208697481
issue: #469
=> Cleanup: Move mac app name generation from start.js to config.js

lib/start.js, scripts/commands.js
Fixes #1103
Related: https://github.com/brave/brave-core/pull/431
You can do this with:
```
npm run start -- --disable_brave_rewards_extension
```
or
```
yarn start --disable_brave_rewards_extension
```
=> Add CLI arg for starting without Brave Rewards extension

package.json
Please review but don't merge yet, I'm still running builds and tests.
Fix brave/brave-browser#1130
=> Upgrade to Chromium 70.0.3538.16

lib/test.js, scripts/commands.js
Added option to specify file for test output (results).
=> added option to output test results to file

lib/config.js
This sets the `brave_referrals_api_key` and is related to the work in brave/brave-core#428
=> Add brave_referrals_api_key to build config

lib/config.js, lib/util.js, scripts/commands.js
This option compiles files as many as possible regardless of compile error.
It would be useful when we trigger full build before going to bed.
Close https://github.com/brave/brave-browser/issues/1204
=> Introduce --ignore_compile_failure to build script

lib/util.js
Requires https://github.com/brave/brave-core/pull/538
Fix https://github.com/brave/brave-browser/issues/551
=> Copy brave_privacy_page resource folder for WebRTC policy setting

lib/start.js, scripts/commands.js
fix https://github.com/brave/brave-browser/issues/1445
launch Brave by
`npm start -- --user-data-dir-name=TEST`
on three platforms
There should be "TEST" folder in
`~/Library/Application Support/BraveSoftware` on Mac
`%LOCALAPPDATA%\BraveSoftware` on Windows
`~/.config/BraveSoftware` on Linux
=> Fix user-data-dir-name switch

lib/config.js, scripts/commands.js
Fixes brave/brave-browser#1412
=> Add options for installer signing key on Mac

lib/util.js
This commit adds the --with_tags flag to gclient sync in the hopes that
doing so will fix the error while building whereby some builds will fail
due to tags not existing in some repository clones.
=> lib/util.js: Add --with_tags flag to gclient sync

lib/util.js, scripts/sync.js
At some point in the past depot tools behavior changed to automatically rebase local changes. That may actually be desirable when running `npm run sync`, but `npm run init` is expected to reset everything to a pristine state.
=> always reset DEPS without rebasing when running `init`

.gitignore, lib/start.js, lib/whitelistedUrlPrefixes.js, package.json, scripts/commands.js
'npm run network-audit' runs the browser with a clean profile for 2 minutes or until the browser quits.  it returns non-zero if any of the URL requests that happened within that time aren't whitelisted and prints the failures to stdout.
it also produces a JSON file, network-audit-results.json, which contains all the network requests from the audit and produces a raw JSON file  network_log.json which can be loaded in chrome://net-internals
whenever CI is ready, we should run `npm run test-security` automatically with each PR to check for unexpected network requests and known vulns in dependencies
fix https://github.com/brave/brave-browser/issues/1694
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm …
=> add npm command for running a network audit

package.json, scripts/audit.js
fix https://github.com/brave/brave-browser/issues/1853
note that this audit will fail until all the PRs i opened in the vendor
directories are merged. see
https://github.com/brave/brave-browser/issues/1853 for references to
those PRs.
=> npm audit command should check vendor directories

docs/source/installing-brave.rst
Tweak fedora instructions for dev to point to correct rpm rpo
Closes #1904
Tested in a vagrant
=> Add Centos instructions

lib/util.js
With this copying, we don't need to modify
chrome/installer/setup/BUILD.gn to use our behaviors.cc file.
This PR should be merged together with https://github.com/brave/brave-core/pull/787
Close https://github.com/brave/brave-browser/issues/1955
=> Copy brave_behaviors.cc to chrome dir

docs/source/installing-brave.rst
This commit adds the brave-keyring package entry to the instructions for
installing the release version of brave-browser
=> docs/installing-brave.rst: add brave-keyring package entry

docs/source/installing-brave.rst
Simple edit to linux installation guide.
When curl is called without the -s flag it stalls on the download progress and does not add key.
=> Resolves #1981: silence curl download progress in piped command to add key

lib/config.js
gn_helpers used by create-dist.py is there.
Fix https://github.com/brave/brave-browser/issues/2149
=> Add src/build to python path

CHANGELOG.md
=> Release notes for 0.56.x Hotfix 1

package.json
Fix https://github.com/brave/brave-browser/issues/2200
This is a minor Chromium update with no logic changes, just a patch refresh.
See also: https://github.com/brave/brave-core/pull/937
=> Upgrade from Chromium 70.0.3538.102 to 70.0.3538.110

lib/whitelistedUrlPrefixes.js
fix https://github.com/brave/brave-browser/issues/2271
test step: `npm run network-audit` should pass
=> add network audit whitelist entries for crlset PR

lib/config.js, scripts/commands.js
When --skip_signing is used for create_dist, unsigned dmg is created
in src/out/Release/unsigned_dmg.
Fix https://github.com/brave/brave-browser/issues/2460
1. Run `yarn create_dist Release --skip_signing`
2. Check dmg is created in `src/out/Release/unsigned_dmg`
=> Add skip_signing option to create_dist target

package.json
Fix https://github.com/brave/brave-browser/issues/2556
Looks like only PDFium security fix was addressed which we don't include anyway. But for fingerprinting reasons and perception we want to stay up to the date with latest version.
=> Upgrade from Chromium 71.0.3578.80 to 71.0.3578.98

lib/l10nUtil.js
Adds an entry to replace 'Chrome Web Store' with just 'Web Store' in l10Util.js.
Fixes brave/brave-browser#2625
in conjunction with brave/brave-core#1133
See brave/brave-core#1133
=> Replace "Chrome Web Store" with "Web Store" in 0.58.x

lib/config.js
Fix https://github.com/brave/brave-browser/issues/1982
Requires: https://github.com/brave/brave-core/pull/1227
This can be reviewed at any time, but please wait for the security review before merging, and only if it is a successful security review would we merge:
https://github.com/brave/internal/issues/452
=> Enable hangouts extension to allow screen share

docs/source/installing-brave.rst
This commit simplified linux build instructions by combining Ubuntu and
Mint installation directions. A separate section for Mint 17 is still
required because it lacks files common to xenial-forward derivatives.
Test installation on Ubuntu 16.04, 18.04, Mint 17, 18, 19.
=> Improve linux build instructions

lib/l10nUtil.js
Modifies l10nUitl.js to globally replace 'Chrome Web Store' with just 'Web Store' in order to avoid ending up with 'Brave Web Store' when 'Chrome' is globally replaced with 'Brave'.
Fixes brave/brave-browser#2983
Same as brave/brave-core#1358
=> Replace "Chrome Web Store" with "Web Store"

lib/util.js, scripts/lint.py
also need https://github.com/brave/brave-core/pull/1417 because the header guard is still wrong in vendor
fix https://github.com/brave/brave-browser/issues/3059
=> fix header guard to be prefixed with `BRAVE_`

lib/updatePatches.js, lib/util.js
Runs each patch diff and writing in parallel.
A small update that reduces time on my two machines:
From ~45s to ~20s 
From ~35s to ~10s
Given we now have over 300 patches, it seems about the right time to put this in.
Git diff is safe to run in parallel.
Fix https://github.com/brave/brave-browser/issues/3084
`npm run update_patches`
Verify that no changes are made in `src/brave/patches`
Modify a chromium file
`npm run update_patches`
Verify that the single change is visible in `src/brave/patches`
=> update_patches command becomes async

lib/whitelistedUrlPrefixes.js
Partial for brave/brave-browser#3191
Core implementation: https://github.com/brave/brave-core/pull/1575
=> Use CDN for publisher list

lib/start.js, lib/whitelistedUrlPatterns.js, lib/whitelistedUrlPrefixes.js
fix https://github.com/brave/brave-browser/issues/3292
CRLSet component will fetch resources from *.gvt1.com. These requests will be proxied through crlsets2.brave.com
https://github.com/brave/brave-core/pull/1581/files#diff-58c3b6971fd1539fa4e2376e5933752eR53
Add the URLs to the whitelistedURLPrefixes to avoid `test-security` failure.
```
22:47:08  NETWORK AUDIT FAIL: https://r3---sn-nx5s7n7z.gvt1.com/edgedl/release2/chrome_component/SPjVcBe_TC4_4963/4963_all_crl-set-11554432547030691744.data.crx3?cms_redirect=yes&mip=157.52.67.21&mm=28&mn=sn-nx5s7n7z&ms=nvh&mt=1549694115&mv=u&pl=24&shardbypass=yes
22:47:08  NETWORK AUDIT FAIL: https://r4---sn-nx57ynlz.gvt1.com/edgedl/release2/chrome_component/SPjVcBe_TC4_4963/4963_all_crl-set-11554432547030691744.data.crx3?mip=157.52.67.48&pl=24&shardbyp …
```
=> Modifying audit whitelist to include CRLSet URLs

lib/config.js, lib/util.js, package.json
To build with bundling, we should provide widevine lib and header.
gn checkes that two files during the generation.
Header file is used by brave-core to get latest version and
download url. However, lib file isn't used by brave-core.
So, empty fake lib file is added just for gn.
Real cdm lib is downloaded and initialized when user accepts the
use of widevine.
This pr should be merged with https://github.com/brave/brave-core/pull/1606.
Fix #413
1. Start browser with clean profile
2. Load https://bitmovin.com/demos/drm
3. Check No drm
4. Install widevine via content settings bubble
5. Check blocked image text is changed …
=> Support widevine linux with bundle w/o default shipping

package.json
Fixes brave/brave-browser#3360
=> Fixes package.json to point to 0.61.x brave-core

lib/test.js
fixes https://github.com/brave/brave-browser/issues/3117
requires https://github.com/brave/brave-core/pull/1645
requires https://github.com/brave-intl/bat-native-confirmations/pull/67
=> Ads Confirmations

Jenkinsfile
Running `npm run sync --all` does nothing locally. I suspect this might be the problem, at least on macOS, with recent PR builder builds
=> Fixing syntax with sync

Jenkinsfile
Fixes problem where fsevents is not available on macOS (optional dep not used for CI runs; errors because no binary for node 11)
Error shown in our logs like:
```
12:31:19  0> Downloading src/third_party/node/node_modules.tar.gz...
12:31:20  node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz 
12:31:20  node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.9.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
12:31:20  gyp WARN install got an error, rolling back install
12:31:20  gyp ERR! configure error 
12:31:20  gyp ERR! stack Error: 404 response downloading https://brave-brave-binaries.s3.amazonaws.com/releases/dist/v11.9.0/node-v11.9.0-headers.tar.gz …
```
=> Don't install optional npm packages on macOS for CI runs

README.md
The Brave Discord channel has been retired. Therefore, references to it should be removed from the readme.md.
=> Remove reference to Discord channel in readme.md

lib/util.js, scripts/commands.js, scripts/lint.py
fix https://github.com/brave/brave-browser/issues/3334
script/lint.py uses GetCommonAncestorWithUpstream() which returns common ancestor with the master branch. This fixes lint script by passing a base branch from config to compute the list of files changed by the commit.
auditors: @bridiver, @mihaiplesa, @bsclifton
`master_lint_dummy` - is a dummy branch off `master`
1. Checkout `lint_fix`
2.  Checkout `master_lint_dummy` in `src/brave`
3. `npm run lint` should show lint errors for 5 files (8 errors)
`test_lint_dummy_0.62.x` - is a dummy branch off `0.62.x`
1. Checkout `test_lint_dummy_0.62.x` in `src/brave`
2. `npm run …
=> Issue 3334: Fix lint script for uplift requests

lib/whitelistedUrlPatterns.js, lib/whitelistedUrlPrefixes.js, package.json
Fixes https://github.com/brave/brave-browser/issues/3453
Going forward we will use the redirector (crlsets.brave.com) instead of fastly proxies. So updating the URLs accordingly.
Here is the code for the redirector: https://github.com/brave/redirector/blob/master/redirector/__init__.py#L30
=> Modifying whitelisted URLs for CRLSets

lib/whitelistedUrlPatterns.js
PR builder passed here: https://staging.ci.brave.com/job/brave-browser-build-pr/job/PR-3929/
fix #3927 
CRLSets on windows started requesting resources from storage.googleapis.com. We updated the redirector to proxy requests for these resources: https://github.com/brave/redirector/commit/372e4426582c11d4dcd2ab57da9567c5c12b172c
This PR adds `storage.googleapis` to the network audit whitelist since requests to the URL will be proxied through the redirector.
PR to proxy requests in brave-core: https://github.com/brave/brave-core/pull/2114/files
1. Covered by automated tests
=> Issue 3927: Whitelist storage.googleapis.com which is now proxied though crlsets.brave.com

lib/build.js, lib/config.js, lib/util.js, scripts/commands.js
Signing is moved from `create_dist` step because signed binaries are
needed to generate sig files. And sig files can't be generated by gn
because of python version of depot_tools.
So, build step signes and generates sig files by system python and they
will be used by installer packaging.
Issue: https://github.com/brave/brave-browser/issues/944
Please refer Test plan at
https://github.com/brave/brave-core/pull/2023
=> Make build step sign binaries and generate widevine sig files on Windows

CHANGELOG.md
=> Release notes for 0.62.x

Jenkinsfile, lib/util.js
=> added widevine steps to pipeline

Jenkinsfile, lib/util.js
Reverts brave/brave-browser#3981
Reason: Windows PR builder fails with binary signing.
=> Revert "added widevine steps to pipeline"

lib/build.js, lib/config.js, lib/util.js, scripts/commands.js
Reverts brave/brave-browser#3903
=> Revert "Make build step sign binaries and generate widevine sig files on Windows"

lib/start.js
fix #4030  
**PR Builder passed here**: https://staging.ci.brave.com/job/brave-browser-build-pr/job/PR-4036/4/
1. Verify that `npm run test-security` works on build machines.
2. Remove any entry from `lib/whitelistedUrlPrefixes.js` and confirm it fails.
=> Issue 4030: Using SIGKILL instead of SIGTERM to terminate the process on timeout

lib/start.js
Uplift of https://github.com/brave/brave-browser/pull/4036
Fixes https://github.com/brave/brave-browser/issues/4030
=> Fix `npm run test-security` issue which was breaking builds

Jenkinsfile
Fixes https://github.com/brave/devops/issues/857
- [] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
=> fixed build param init in pipeline

lib/start.js
fix https://github.com/brave/brave-browser/issues/3025
STP can cause webcompat issues, so gating this feature behind off-by-default runtime flag till the feature is thoroughly tested.
More details about the feature/switches is available here:
https://github.com/brave/brave-core/pull/403
Please reach out if you have any questions.
The test plan for this change is covered in: https://github.com/brave/brave-core/pull/403 (For Devs - Enable STP runtime and buildflags)
=> Adding a runtime switch for Smart Tracking Protection

package.json
Uplift of https://github.com/brave/brave-browser/pull/4281 to `0.65.x`
Related https://github.com/brave/brave-core/pull/2358
Fixes https://github.com/brave/brave-browser/issues/4278
Merge pull request #4281 from brave/74.0.3729.131_master_22
=> Upgrade from Chromium "74.0.3729.108" to Chromium 74.0.3729.131

package.json
Fixes https://github.com/brave/brave-browser/issues/4443
Related https://github.com/brave/brave-core/pull/2448
=> Upgrade from Chromium 74.0.3729.131 to Chromium 74.0.3729.157

Jenkinsfile
fix #4457 
Check if CI has two stages `audit-deps` and `network-audit` instead of `test-security` 
=> Issue 4457: Split test-security into audit_deps and network_audit for CI

Jenkinsfile
Closes https://github.com/brave/brave-browser/issues/4481
Closes https://github.com/brave/brave-browser/issues/4482
Closes https://github.com/brave/brave-browser/issues/4485
Closes https://github.com/brave/brave-browser/issues/4486
=> multiple CI pipeline fixes and improvements

lib/config.js, package.json
Fix https://github.com/brave/brave-browser/issues/4283
PR builder passed: https://staging.ci.brave.com/job/brave-browser-build-pr/job/PR-4551/24/
This PR disables field trials in Brave by setting `fieldtrial_testing_like_official_build` in config.js. 
The follow-up PR: https://github.com/brave/brave-core/pull/2471 :
1. Adds test for disabling field trials
2. Resets security indicator to display locks instead of security chips for EV certs (to match the behavior in current release builds)
3. Removes features that were disabled in brave_main_delegate.cc to override field trials
1. Navigate to …
=> Issue 4283: Disabling field trials 

package.json
Related https://github.com/brave/brave-core/pull/2602
Uplift of https://github.com/brave/brave-browser/pull/4718
Fixes https://github.com/brave/brave-browser/issues/4724
=> Upgrade from Chromium 75.0.3770.75 to Chromium 75.0.3770.80 (Uplift to 0.67.x)

package.json
Related https://github.com/brave/brave-core/pull/2600
Uplift of https://github.com/brave/brave-browser/pull/4718
Fixes https://github.com/brave/brave-browser/issues/4724
=> Upgrade from Chromium 75.0.3770.75 to Chromium 75.0.3770.80 (Uplift to 0.66.x)

package.json
Related https://github.com/brave/brave-core/pull/2599
Uplift of https://github.com/brave/brave-browser/pull/4718
Fixes https://github.com/brave/brave-browser/issues/4724
=> Upgrade from Chromium 75.0.3770.75 to Chromium 75.0.3770.80 (Uplift to 0.65.x)

lib/test.js
Adds ability to run unit tests for iOS using `npm run test brave_rewards_ios_tests -- --target_os=ios`
resolves #4812 
~https://github.com/brave/brave-core/pull/2667 should be merged first~
=> Add support for running iOS unit tests

lib/util.js
When signing is skipped on Windows, source directory should be output dir.
When signing is enabled, source bin files are located in different dir.
Fix https://github.com/brave/brave-browser/issues/4875
=> Fix wrong src directory for widevine sig file generation on Windows

lib/config.js
Reverts brave/brave-browser#4912
Reason:
=> Revert "Enable widevine vmp on MacOS"

package.json
Fixes #4962
Related: brave/brave-core#2732
Uplift request from #4964
=> Upgrade from Chromium 75.0.3770.90 to Chromium 75.0.3770.100 (0.65.x)

package.json
Update widevine version string to `4.10.1440.18` in package.json
Fix https://github.com/brave/brave-browser/issues/5022
1. Debug build after updating widevine version string in `package.json`
2. Start browser (`yarn start --vmodule=*widevine*=2`) with existing profile (widevine is already installed) and check below logs
```
[18294:18294:0624/064937.097475:VERBOSE1:brave_widevine_bundle_manager.cc(287)] StartupCheck: widevine prefs state looks fine
[18294:18294:0624/064937.097561:VERBOSE1:brave_widevine_bundle_manager.cc(288)] StartupCheck: installed widevine version: 4.10.1196.0
[18294:18294:0624/064937.097612:VERBOSE1:brave_widevine_bundle_manager.cc( …
```
=> Widevine 4.10.1440.18 is ready to use on linux

lib/test.js
Fix brave/brave-browser#4793
Sister PR: https://github.com/brave/brave-core/pull/2569
There's a race condition if you try to use the same gn rule, so I had to make it separate.
=> Fix adblock-rust test path

.gitignore
[`ripgrep`](https://github.com/BurntSushi/ripgrep) reports that the double asterisks in the `.gitignore` file are invalid `gitignore` syntax. Git's [documentation](https://git-scm.com/docs/gitignore) confirms that double asterisks are meaningless unless adjacent to one or more `/` characters.
=> Fix invalid .gitignore syntax

lib/util.js
This fixes a [warning found by lgtm](https://lgtm.com/projects/g/brave/brave-browser/snapshot/49c71729b7002b76ad3cade9853fce2f7e1ed149/files/lib/util.js?sort=name&dir=ASC&mode=heatmap).
The same operand was used twice in an if statement.
=> Remove Identical Operand

lib/gitPatcher.js, lib/sync/logging.js
Fix https://github.com/brave/brave-browser/issues/5245
`npm run test:scripts`
`npm run sync -- --run_hooks`
=> Apply patches without considering whitespace / line-ending differences

lib/config.js, lib/util.js, scripts/commands.js
Use `--gn` to pass through ad-hoc gn args. `--gn=is_component_build:true` translates to `is_component_build=true`.
Use `--ninja` to add command line options for Ninja. `--ninja=j:48` translates to `-j 48`.
Fix https://github.com/brave/brave-browser/issues/5184
=> Add --gn and --ninja to npm run build

lib/whitelistedUrlPatterns.js
Fix https://github.com/brave/brave-browser/issues/5275
`npm run network-audit` should test this change in CI. 
=> Fix #5275: Update whitelist patterns for new crlset request URLs

package.json
Uplift of https://github.com/brave/brave-browser/pull/5446
Related: https://github.com/brave/brave-core/pull/3049
Fixes https://github.com/brave/brave-browser/issues/5424
=> Upgrade from Chromium 76.0.3809.72 to Chromium 76.0.3809.87 (BETA)

package.json
Uplift of https://github.com/brave/brave-browser/pull/5446
Related: https://github.com/brave/brave-core/pull/3050
Fixes https://github.com/brave/brave-browser/issues/5424
=> Upgrade from Chromium 76.0.3809.72 to Chromium 76.0.3809.87 (RELEASE)

package.json
Uplift of https://github.com/brave/brave-browser/pull/5556
Related: https://github.com/brave/brave-core/pull/3108
Fixes https://github.com/brave/brave-browser/issues/5554
=> Upgrade from Chromium 76.0.3809.87 to Chromium 76.0.3809.100 (RELEASE)

docs/source/installing-brave.rst
This was reported in https://twitter.com/datashed/status/1161402640330182657
and also affects other projects:
https://github.com/signalapp/Signal-Desktop/issues/2483
https://forum.openmediavault.org/index.php/Thread/25432-E-Failed-to-fetch-Public-key-signature-verification-failed/
https://stackoverflow.com/questions/39437606/curl-35-gnutls-handshake-failed-public-key-signature-verification-has-fail
=> Add a note about Debian 9 gnutls bug

docs/source/installing-brave.rst
`curl` is not installed by default on Ubuntu systems. Unless it is explicitly marked for installation, these installation instructions would fail with an error.
=> update Ubuntu installation docs

Jenkinsfile
Get quick access to any build's uploaded output for quick testing by the product team (or other). I intentionally left this as occuring not only for succesful builds, but only when there's at least 1 uploaded artifact. That means that macOS may fail for example, but we can still view the Windows builds.
Should look something like this:
I tested this against DMing me, but I think we should create a channel called something like `#build-downloads`.
=> Build: send notification to slack with list of downloads

docs/source/installing-brave.rst
Changed installation instructions to reflect the current status on Cent OS 7 that is not working at the moment.
=> Changed CentOS 7 installation instructions

lib/util.js
This is now neccessary for https://github.com/brave/brave-core/pull/3165 since it uses a simple method for replacing the chromium avatar placeholder: just overwriting the image.
Address https://github.com/brave/brave-browser/issues/5207
This can be merged ahead of time with no consequence
Contained within brave-core PR
=> Overwrite chromium theme/x/common directory for avatar placeholder

lib/l10nUtil.js, lib/pullL10n.js, lib/pushL10n.js, scripts/commands.js
Fix https://github.com/brave/brave-browser/issues/5686
Documentation added here:
https://github.com/brave/brave-browser/wiki/Strings-and-Localization#localizing-extensions
=> Add l10n support for ethereum-remote-client

Jenkinsfile
Right now, the signing is not done correctly and the outputs cannot be run on macOS due to a codesign error
Fix https://github.com/brave/brave-browser/issues/5823
Run an output from this PR job from the CI system
=> CI: For PRs, don't sign builds so that build outputs can be used

Jenkinsfile
Go back to using nightly builds by default in CI to observe if this fixes issues that @mihaiplesa is seeing. We can then reintroduce the channel change as a separate PR and see the CI result in isolation.
Corresponds with https://github.com/brave/brave-core/pull/3331
=> CI: revert to nightly channel for PR builds

Jenkinsfile
We'll want to use a build number in the path (so concurrent builds don't conflict)
This reverts commit cf038bcd12e5c6316cb994dae52e64915198d241, reversing
changes made to 6e843d4b063df0dc989c65d276d3d9806c64d7b0.
=> Revert "Merge pull request #5893 from brave/customworkspace"

lib/config.js, package.json
Fixes #5375
Related PR: brave/brave-core#3358
=> Upgrade from Chromium 76.0.3809.132 to Chromium 77.0.3865.65

lib/config.js, scripts/commands.js
Related to #4820
@SergeyZhukovsky Now that we're using a `chromium_src` override to handle versioning (instead of patching), I needed to switch the build config to use `android_override_version_name` instead of `android_default_version_name`. Without this change, the version number wasn't being picked up.
See steps in related issue.
=> Replace android_default_version_name with android_override_version_name

scripts/lint.py
Fixes brave/brave-browser#5971
Removed auth_config from our script as we don't need to pass it to
devtools script any more.
The failure is due to devtools change:
commit	934836a6c5b1a3442db7f7197569fc1bbdcb8991	[log] [tgz]
author	Edward Lemur <ehmaldonado@chromium.org>	Mon Sep 09 20:16:54 2019
committer	Commit Bot <commit-bot@chromium.org>	Mon Sep 09 20:16:54 2019
tree	c6cb985aca378a2f816bb7d21a072394b1d4882a
parent	1e4d70d1dd0865b0ac824beccee70d3852705dd8 [diff]
git-cl: Remove unused auth configs.
auth_config is a Rietveld thing, so it's not necessary
in most of the code, except for triggering try bots.
Bug: 1001756
Change-Id: I0f243a297b05a43a61b052ba75c5886556e81b4e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/1793018
- Verified that these …
=> Fixes lint script.

Jenkinsfile, lib/config.js, package-lock.json, package.json, scripts/lint.py
Uplift of https://github.com/brave/brave-browser/pull/5896 and https://github.com/brave/brave-browser/pull/5967
Fixes https://github.com/brave/brave-browser/issues/5375
Fixes https://github.com/brave/brave-browser/issues/5966
Related https://github.com/brave/brave-core/pull/3385
=> Upgrade from Chromium 76.0.3809.132 to Chromium 77.0.3865.75 (uplift to 0.68.x)

lib/config.js, package.json, scripts/lint.py
Fixes #5375
Related PR: brave/brave-core#3408
Uplift request from #5896 
=> Upgrade from Chromium 76.0.3809.132 to Chromium 77.0.3865.65 (0.70.x)

scripts/updatePatches.js
new_tab_page_view.xml
channel_constants.xml
These files are overwritten by brave's one.
So, update_patches commands should not generate patch file for them.
fix https://github.com/brave/brave-browser/issues/6126
=> [Android] Don't generate patch file for overwritten files

package-lock.json
=> Issue 6163: Fixing prototype pollution vulnerability in handlebars

lib/config.js
Fixes https://github.com/brave/brave-browser/issues/6375
Build and run android x86_32 on emulator
=> Set enable_profiling to false for Android debug build config

lib/test.js
Fix https://github.com/brave/brave-browser/issues/6138
Sister PR: https://github.com/brave/brave-core/pull/3514
Documentation added here: https://github.com/brave/brave-browser/wiki/Tests#android
=> Add support for Android unittests

CHANGELOG.md
=> Release notes for 0.69.x Hotfix 1

lib/config.js
Component builds are faster for incremental changes. Developers like to sometimes use Release builds. We had previously set all Release builds to not use component builds when this only needs to be done for official builds.
Before this PR, for Debug builds Component Builds were already the default, but for Release builds one must specify `npm run build Release -- --official_build=false --gn=is_component_build:true`. With this PR, `is_component_build` is always true unless `official_build` is true (which it is by default for Release).
There is a GN check to make sure component builds are not enabled for official builds.
=> Build: use component build for Release non-official builds

Jenkinsfile
Closes https://github.com/brave/brave-browser/issues/6593
=> enabled sccache for windows and fixed git cache path

lib/util.js, scripts/.vpython, scripts/lint.py
fixes https://github.com/brave/brave-browser/issues/6434
1. Uninstall httplib2 `pip uninstall httplib2`
2. Update package.json to checkout `httplib2_lint` in brave-core
3. run: `npm run init`
4. in brave-core: `git checkout -b TEMP_LINT`
5. run: `npm run lint` and verify one error shows up 
=> Fix 6434: Using vpython for lint

lib/util.js, scripts/.vpython, scripts/lint.py
Uplift request for https://github.com/brave/brave-browser/pull/6638
1. Uninstall httplib2 pip uninstall httplib2
2. Update package.json to checkout httplib2_lint in brave-core
3. run: npm run init
4. in brave-core: git checkout -b TEMP_LINT
5. run: npm run lint and verify one error shows up
=> Fix 6434: Using vpython for lint (0.71.x)

lib/config.js, lib/createDist.js, scripts/commands.js
Work in progress.
Depends upon changes in brave-core branch `issue_5177`.
Requires NPM configuration such as:
```
npm config --userconfig=.npmrc set notary_user APPLEID_EMAIL_ADDRESS
npm config --userconfig=.npmrc set notary_password APPLE_APP_SPECIFIC_PASSWORD
```
Fixes: https://github.com/brave/brave-browser/issues/5177
Related: https://github.com/brave/brave-core/pull/3725
=> Add MacOS notarization

Jenkinsfile
Originally done in https://github.com/brave/brave-browser/pull/6676/commits/f9e622d804d225b80aa593818a38abcc99ea64c1 to make that PR pass CI.
=> Increase timeout for unit tests on Windows and Mac

Jenkinsfile, lib/config.js, lib/createDist.js, scripts/commands.js
Uplift of #5485
Related https://github.com/brave/brave-core/pull/3857
Approved, please ensure that before merging:
=> Add MacOS notarization (Uplift of #5485 to 0.71.x)

CHANGELOG.md
=> Release notes for 0.71.x

package-lock.json, package.json
Fixes #6987
Related PR: brave/brave-core#4016
Uplift from #6990 
Upgrade from Chromium 78.0.3904.97 to Chromium 78.0.3904.108
=> Upgrade from Chromium 78.0.3904.97 to Chromium 78.0.3904.108 (1.0.x)

package-lock.json, package.json
Fixes #6987
Related PR: brave/brave-core#4021
Uplift from #6990
=> Upgrade from Chromium 78.0.3904.97 to Chromium 78.0.3904.108 (1.2.x)

lib/config.js
Required for https://github.com/brave/brave-core/issues/3420
=> Add config option for webcompat reporter API endpoint

docs/source/installing-brave.rst
This is to clarify that it won't work on 64-bit ARM for example: https://www.reddit.com/r/brave_browser/comments/e4l0pz/brave_on_raspberry_pi/
=> Clarify what we mean by 64-bit Linux distros

lib/l10nUtil.js
This happens in the module root, which isn't ideal. It's nice to let users know that this is going on, but too much information about it was confusing (for me at least) as to whether this was part of the command I was running (it
=> Reduce verbosity of GRD to GRDP mapping

.github/CODEOWNERS, lib/build.js, lib/licensing.js
Fixes https://github.com/brave/brave-browser/issues/7150.
It depends on https://github.com/brave/brave-core/pull/4103.
Same as https://github.com/brave/brave-core/pull/4103.
=> Automatically generate LICENSE files for external components

lib/build.js, lib/licensing.js
Uplift of #7155 .
This depends on https://github.com/brave/brave-core/pull/4128 in order to build successfully.
=> Automatically generate LICENSE files for external components (uplift to 1.1.x)

docs/source/installing-brave.rst
As mentioned in #7506, this is no longer needed.
=> Remove no-longer-necessary user namespace comment (#7506)

CHANGELOG.md
=> Release Notes for 1.2.x

package.json
Upgrade from Chromium 79.0.3945.117 to Chromium 79.0.3945.130
Uplift of https://github.com/brave/brave-browser/pull/7782
Fixes https://github.com/brave/brave-browser/issues/7781
Related https://github.com/brave/brave-core/pull/4385
=> Upgrade from Chromium 79.0.3945.117 to Chromium 79.0.3945.130 (uplift to 1.3)

package.json
Upgrade from Chromium 79.0.3945.117 to Chromium 79.0.3945.130
Uplift of https://github.com/brave/brave-browser/pull/7782
Fixes https://github.com/brave/brave-browser/issues/7781
Related https://github.com/brave/brave-core/pull/4386
=> Upgrade from Chromium 79.0.3945.117 to Chromium 79.0.3945.130 (uplift to 1.4)

package.json
Upgrade from Chromium 79.0.3945.117 to Chromium 79.0.3945.130
Uplift of https://github.com/brave/brave-core/pull/4383
Fixes https://github.com/brave/brave-browser/issues/7781
Related https://github.com/brave/brave-core/pull/4384
=> Upgrade from Chromium 79.0.3945.117 to Chromium 79.0.3945.130 (uplift to 1.2)

lib/whitelistedUrlPrefixes.js
This is needed before https://github.com/brave/brave-core/pull/4314 can land because the Mac build machines use these OS resolvers:
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 1.1.1.1
nameserver 1.0.0.1
Nothing to test in here, but it will make the `npm run network-audit` test pass in brave/brave-core#4314.
=> Whitelist DoH servers in the network auditor (brave/brave-browser#1864)

lib/licensing.js
Fixes brave/brave-browser#7176.
Requires https://github.com/brave/brave-core/pull/4380.
1. Open `brave://credits`.
2. Verify that the "Brave Local Data" entry is present and that the license text is there too.
=> Directories underscores in components/third_party

lib/util.js, scripts/updatePatches.js
fix https://github.com/brave/brave-browser/issues/5368
=> Replace incognito marker svg file

lib/config.js
closes https://github.com/brave/brave-browser/issues/7842
=> set Android version to the same as desktop

lib/config.js
Fix https://github.com/brave/brave-browser/issues/7892
This is the config side of the fix, allowing us to set the developer options code via .npmrc and pass it to the build.
=> Add config for Android developer options

lib/whitelistedUrlPrefixes.js
Uplift for https://github.com/brave/brave-browser/pull/7960
Fixes #7959
=> Fix 7959: Add tor.bravesoftware.com to audit whitelist (1.4.x)

lib/whitelistedUrlPrefixes.js
Uplift for https://github.com/brave/brave-browser/pull/7960
Fixes #7959
=> Fix 7959: Add tor.bravesoftware.com to audit whitelist (1.3.x)

.github/CODEOWNERS
According to https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax, we don't have to use individual code owners, we can also use a team, which is much better in this case.
=> Use team ownership for network-audit whitelist

lib/l10nUtil.js
We should not replace google's own product name such as Google Docs
or Google Drive.
fix https://github.com/brave/brave-browser/issues/5450
=> Fixup some strings for google product names

lib/l10nUtil.js, lib/util.js, package.json
Fixes #7255
Fixes #7975
Related PR: brave/brave-core#4469
Uplift request from #7732
=> Upgrade from Chromium 79.0.3945.117 to Chromium 80.0.3987.78 (1.4.x)

lib/l10nUtil.js, lib/util.js, package.json
Fixes #7255
Fixes #7975 
Related PR: brave/brave-core#4467
Uplift request from #7732 
=> Upgrade from Chromium 79.0.3945.117 to Chromium 80.0.3987.78 (1.3.x)

lib/whitelistedUrlPatterns.js, lib/whitelistedUrlPrefixes.js
Fix #8034 
PR for proxy https://github.com/brave/brave-core/pull/4482
1. network-audit should pass.
=> Fix 8034: Add Crowd Deny requests to audit whitelist

package.json
Fixes #8058
Related PR: brave/brave-core#4521
Uplift from #8064
=> Upgrade from Chromium 80.0.3987.85 to Chromium 80.0.3987.87 (1.5.x).

package.json
Fixes #8058
Related PR: brave/brave-core#4519
Uplift from #8064 
=> Upgrade from Chromium 80.0.3987.85 to Chromium 80.0.3987.87 (1.3.x).

Jenkinsfile
Closes https://github.com/brave/brave-browser/issues/8091
=> added feature to run network audit on demand and disabled sccache on windows

lib/config.js
fix https://github.com/brave/brave-browser/issues/7875
=> don't treat warnings as errors for non release builds

lib/whitelistedUrlPatterns.js, lib/whitelistedUrlPrefixes.js
Fix #8034 
Uplift for https://github.com/brave/brave-browser/pull/8035
=> Fix 8034: Add Crowd Deny requests to audit whitelist (uplift to 1.4)

lib/util.js
fixes https://github.com/brave/brave-browser/issues/8023
=> Fixes app icon on mono builds

scripts/lint.py
Fix #8127 
git_cl.py was recently updated to change the function arguments for cl.GetChange.
https://chromium.googlesource.com/chromium/tools/depot_tools/+/7f6dec01696fa5319c505ca8f57579a5b02c4184%5E%21/git_cl.py
Updating the lint script to match the args.
1. Edit any `.cc` file to remove the first line of the file license.
2. run `npm run lint`, you should get an error
=> Fix 8127: Update GetChange to remove the author arg

lib/util.js
fixes https://github.com/brave/brave-browser/issues/8023 for debug mode
=> fixes an app icons in debug mode

docs/source/installing-brave.rst
As of Fedora 31, this package is not necessarily installed in minimal images. Without it, a user will run into the following error trying to use `dnf config-manager`:
No such command: config-manager. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(config-manager)'"
I tested that the package can be installed on Fedora 29 and CentOS 8 too.
=> Add missing dnf-plugins-core package for Fedora installs

package.json
Fixes #8188
Related PR: brave/brave-core#4621
Uplift from #8195
=> Upgrade from Chromium 80.0.3987.87 to Chromium 80.0.3987.100 (1.4.x).

package.json
Fixes #8188
Related PR: brave/brave-core#4622
Uplift from #8195
=> Upgrade from Chromium 80.0.3987.87 to Chromium 80.0.3987.100 (1.3.x).

Jenkinsfile
Closes https://github.com/brave/brave-browser/issues/8260
Related https://github.com/brave/brave-core/pull/4658
=> removed version mismatch check

lib/licensing.js
Fixes brave/brave-browser#7460 along with https://github.com/brave/brave-core/pull/4481.
`npm run build Release`
Look at the "Background images" entry in `brave://credits`. It should contain URLs and licenses for all 16 background images.
=> Auto-generate NTP backgrounds LICENSE file

lib/build.js
Addresses (but does not fix) https://github.com/brave/brave-browser/issues/8615
=> Comment out licensing so we can get a Nightly build

.sonarcloud.properties
For https://github.com/brave/devops/issues/501
With https://github.com/brave/brave-core/pull/4775
=> added sonarcloud analysis

docs/source/installing-brave.rst
Now that we have merged the beta and dev channels, there's no need to promote the dev channel anymore.
=> Remove references to dev channel

lib/build.js, lib/createDist.js
This effectively re-enables the LICENSE file creation and fixes https://github.com/brave/brave-browser/issues/8618.
1. Go into `chrome://credits`.
2. Ensure that "Background images" is present and that its licensing info can be expanded.
3. Ensure that "Brave Ad Block" is present and that its licensing info can be expanded.
=> Generate LICENSE files in create_dist

lib/build.js, lib/createDist.js
Uplift of https://github.com/brave/brave-browser/pull/8560.
1. Go into `chrome://credits`.
2. Ensure that "Background images" is present and that its licensing info can be expanded.
3. Ensure that "Brave Ad Block" is present and that its licensing info can be expanded.
=> Move LICENSE file generation to create_dist (fixes #8618)

lib/config.js
Fix https://github.com/brave/brave-browser/issues/8381
This enables it locally and builds fine, but doesn't work locally. I think because it needs to be a play store build and not just a local build.  I think we should try landing this and see if it works. If it doesn't then we can dig in more.
=> Use safe_browsing_mode=2 for Android

scripts/lint.py
Fix #8683 
1. Run `npm run lint` to confirm no errors on lint
=> Fix 8683: Use GetAffectedFiles instead of GetChange

lib/config.js
Uplift for PR https://github.com/brave/brave-browser/pull/8664
Fix #8381
please ensure that before merging: 
=> Use safe_browsing_mode=2 for Android (Uplift for 1.7.x)

lib/config.js
Uplift for PR https://github.com/brave/brave-browser/pull/8664
Fix #8381
please ensure that before merging: 
=> Use safe_browsing_mode=2 for Android (Uplift to 1.5.x)

scripts/lint.py
Fix #8683 
Uplift for https://github.com/brave/brave-browser/pull/8684
1. Run `npm run lint` and confirm that it doesn't fail.
=> Fix 8683: Use GetAffectedFiles instead of GetChange (Uplift for 1.7.x)

scripts/lint.py
Fix #8683 
Uplift for https://github.com/brave/brave-browser/pull/8684
1. Run `npm run lint` and confirm that it doesn't fail.
=> Fix 8683: Use GetAffectedFiles instead of GetChange (Uplift for 1.5.x)

scripts/commands.js
Should make test execution faster and more reliable.
For more info see https://bravesoftware.slack.com/archives/CA5FPHWLF/p1584498924254400
=> Update `test_launcher_jobs` to be 4. 

lib/config.js, lib/util.js, package.json, scripts/sync.js, scripts/updatePatches.js
Fixes #8308
Related PR: brave/brave-core#4548
=> Upgrade from Chromium 80.0.3987.149 to Chromium 81.0.4044.69.

package-lock.json
Fixes brave/brave-browser#8722
Related https://github.com/brave/brave-core/pull/4998 
=> Rebuild package-lock.json to fix npm audit errors

lib/config.js
Uplift of PR https://github.com/brave/brave-browser/pull/8863 to 1.7.x
Related https://github.com/brave/brave-core/pull/5138
Fixes https://github.com/brave/brave-browser/issues/8864
Fixes https://github.com/brave/brave-browser/issues/8896
=> pass brave_channel in env (uplift to 1.7.x) 

lib/util.js
Required for https://github.com/brave/brave-core/pull/5147
=> don't copy java/res

lib/whitelistedUrlPatterns.js
Issue: https://github.com/brave/brave-browser/issues/8218
=> Add super referral's mapping table url to whitelisted url for auditing

lib/util.js
Reverts brave/brave-browser#8994
Reason: With this PR, NTP background images are not visible.
=> Revert "don't copy java/res"

Jenkinsfile
For https://github.com/brave/brave-browser/issues/8979
=> uplifted ci pipeline changes

package.json
Uplift of https://github.com/brave/brave-browser/pull/9001
Fixing https://github.com/brave/brave-browser/issues/9000
Related https://github.com/brave/brave-core/pull/5190
=> Upgrade from Chromium 81.0.4044.83 to Chromium 81.0.4044.92 (uplift to 1.8.x)

Jenkinsfile, scripts/sync.js
Fixes: https://github.com/brave/brave-browser/issues/9124
=> Remove GIT_CACHE_PATH temporarily to avoid remote inconsistencies

lib/build.js, lib/createDist.js
Uplift for https://github.com/brave/brave-browser/pull/9115
=> Pr9115 android signing uplift 1.7.x

Jenkinsfile
Related to brave-browser#9168
1. Wait for CI build to complete
2. Ensure near the apk there are .tar file with symbols
=> Android symbols archive have .tar extension now

package.json
Less risky version of https://github.com/brave/brave-browser/pull/9304 for 1.8.x
Only changes the remote, no other changes
=> Use Chromium GitHub instead of Gerrit instance

package.json
Uplift of https://github.com/brave/brave-browser/pull/9494
Fixes https://github.com/brave/brave-browser/issues/9493
Related https://github.com/brave/brave-core/pull/5405
=> Upgrade from Chromium 81.0.4044.122 to Chromium 81.0.4044.129 (uplift to 1.9.x)

package.json
Uplift of https://github.com/brave/brave-browser/pull/9494
Fixes https://github.com/brave/brave-browser/issues/9493
Related https://github.com/brave/brave-core/pull/5404
=> Upgrade from Chromium 81.0.4044.122 to Chromium 81.0.4044.129 (uplift to 1.8.x)

lib/test.js
=> Added ability to run UI java tests for Android

Jenkinsfile
Fix https://github.com/brave/brave-browser/issues/9567
=> Fix PR builder

Jenkinsfile
For https://github.com/brave/devops/issues/3004
=> several fixes to ci pipeline

Jenkinsfile
=> fixed slash escaping in branch name

lib/start.js, package.json
Fixes #9558 
DoH is disabled for network-audit to ensure that requests to only whitelisted URLs are made when the browser is bootstrapped.
=> Fix 9558: Disable DoH for network-audit

lib/test.js
Resolves https://github.com/brave/brave-browser/issues/9532
=> Made UI java tests to run along with brave unit tests

package-lock.json
Fixes https://github.com/brave/brave-browser/issues/9578
Related https://github.com/brave/brave-core/pull/5450
From a fully initialized repo, run:
`npm run audit_deps`
No errors should occur 👍 
=> Ran `npm audit fix` to fix open npm audit warnings

Jenkinsfile
With https://github.com/brave/brave-core/pull/5506
=> fixed build status init

lib/config.js, scripts/commands.js
To generate delta installer, pass true to build_delta_installer and
pass folder that includes previous versions chrome.7z file to
last_chrome_installer. This folder should be in out dir.
For example, if we want to delta folder for it, create delta folder
to out/Release/delta and copies chrome.7z to it. and pass "delta"
to last_chrome_installer. During the build, couregette.exe will be
copied to that folder.
Issue https://github.com/brave/brave-browser/issues/9565
=> Add build_delta_installer option to create_dist

lib/config.js, lib/test.js, lib/util.js, package.json
Fixes #9760 
Related PR: brave/brave-core#5102
=> Upgrade from Chromium 81 to Chromium 83

lib/util.js
partial fix for https://github.com/brave/brave-browser/issues/9063
requires https://github.com/brave/brave-core/pull/5189
=> don't copy ntp resources

lib/util.js
Issue https://github.com/brave/brave-browser/issues/10071
=> Replace components image resources

lib/config.js
Resolves https://github.com/brave/brave-browser/issues/10279
1. Set the updater config.
2. Setup Little Snitch or Fiddler to intercept requests
3. Open Brave Browser with a clean profile
4. Navigate to `brave://components`, verify the following components download successfully:
-  Brave Local Data Update
-  Brave Ad Block Updater
-  Brave Tor Client Updater (Mac/Win/Linux)
-  NTP Sponsored Images (US)
-  Brave SpeedReader Updater
-  Brave HTTPS Everywhere Updater
-  CRLSets - Updates are not functioning correctly - likely fixed by https://github.com/brave/brave-core/pull/5847
5. Repeat the above steps with a clean profile …
=> Fix 10279: Set updater endpoint at build time

lib/util.js, scripts/sync.js
Adds the refs that chromium (src/) and brave (src/brave) are at _after_ gclient sync, in order to validate that build issues occurred on the expected checkouts.
Helps diagnose some infrequent CI issues with build errors that are the result of unexpected checkouts occurring during sync. Even if the checkouts are expected, this logging makes it explicit to the developer that there _wasn't_ an issue with sync.
----
=> Sync gets post-sync git ref logging

lib/gnCheck.js, package.json, scripts/commands.js
Resolves https://github.com/brave/brave-browser/issues/9365
CI should pass
=> Fix 9365: Add gn check to npm scripts

lib/gnCheck.js, package.json, scripts/commands.js
Uplift of https://github.com/brave/brave-browser/pull/10599
Resolves : https://github.com/brave/brave-browser/issues/9365
=> Fix 9365: Add gn check to npm scripts (Uplift 1.11.x)

.github/PULL_REQUEST_TEMPLATE.md, scripts/audit.js
Dependency of https://github.com/brave/brave-core/pull/5755.
npm run audit_deps
=> Move all audit_deps logic to brave/script/audit_deps.py

lib/config.js
This removes the need of having to handle this as via a chromium
patch + a brave specific variable in build/features.gni.
Fix brave/brave-browser#7957
N/A
=> 7957: Initialize branding_path_component = "brave" in config.js

lib/config.js, lib/util.js, package.json
Fixes #10636
Related PR: brave/brave-core#6423
Uplift from #10634 
Uplift from #11209  
=> Upgrade from Chromium 84 to Chromium 85 (1.13.x).

package.json
Fixes #11621
Related PR: brave/brave-core#6602
Uplift from #11622 
=> Upgrade from Chromium 85.0.4183.83 to Chromium 85.0.4183.102 (1.15.x).

package.json
Fixes #11621
Related PR: brave/brave-core#6603
Uplift from #11622
=> Upgrade from Chromium 85.0.4183.83 to Chromium 85.0.4183.102 (1.14.x).

lib/config.js
This arg is needed on Android so that the correct .grd is used (e.g
brave_strings.grd instead of chromium_strings.grd, see
chrome-app-BUILD.gn.patch).
Fixes #11656
Uplift from brave/brave-core#6619
=> Restores branding path config arg for Android (1.13.x).

CHANGELOG_DESKTOP.md
=> Release notes for 1.14.x Release #1

package.json
We don't need to set widevine version anymore.
We will get widevine as a component.
Resolves https://github.com/brave/brave-browser/issues/7081
=> Use widevine component on linux

package.json
Fixes #13900
Related PR: brave/brave-core#7794
Uplift from #13907  
=> Upgraded from Chromium 88.0.4324.96 to Chromium 88.0.4324.146 (1.20.x).

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.20.x Release #1

CHANGELOG_ANDROID.md
=> Release notes for 1.20.x

package.json
Fixes #15270
Related PR: brave/brave-core#8531
=> Upgrade from Chromium 89.0.4389.114 to Chromium 89.0.4389.128 (1.22.x).

package.json
Uplift of https://github.com/brave/brave-browser/pull/16490
Fixes brave/brave-browser#16489
Related PR: https://github.com/brave/brave-core/pull/9184
=> Upgrade from Chromium 91.0.4472.106 to Chromium 91.0.4472.114 (uplift to 1.27.x)

package.json
Uplift of https://github.com/brave/brave-browser/pull/16490
Fixes brave/brave-browser#16489
Related PR: https://github.com/brave/brave-core/pull/9183
=> Upgrade from Chromium 91.0.4472.106 to Chromium 91.0.4472.114 (uplift to 1.26.x)

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.26.x Release #1

package.json
Reverts brave/brave-browser#16818
The PR was merged too early (the counterpart PR brave/brave-core#9361 wasn't ready to merge yet).
=> Revert "Upgrade from Chromium 91 to Chromium 92 (1.27.x)."

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.29.x Release #1

package.json
Resolves #17790
Related PR: brave/brave-core#9939
Uplift from #17791
=> Upgrade from Chromium 93.0.4577.58 to Chromium 93.0.4577.63 (1.29.x).

README.md
Seems like our shared sscache cache is deprecated in favor of Goma.
=> Link to our Goma instructions for staff

lib/util.js
From NPM >=6 and as explained in RFC 21[1], npm is removing the
npm_config_* and npm_package_* environment variables from the
context of lifecycle scripts and so, while some of them such
as the npm_package_config_* ones will still work on NPM 7, we
need to adapt to this change or it won't be able to setup the
repository from NPM 8 on.
This change does a small change to make sure that we work on
every possible situation, relying on those environment variables
if still using NPM <= 7, or simply reading the package.json file
as a dictionary when using NPM >= 8.
[1] https://github.com/npm/rfcs/blob/main/implemented/0021-reduce-lifecycle-script-environment.md
Resolves https://github.com/brave/brave-browser/issues/19993
N/A
=> Fix npm run init to work when using NPM >= 8

.github/workflows/pr_ready_for_review.yml
Resolves https://github.com/brave/devops/issues/6595
Creates an action that will perform a rebase when a PR is moved from draft to ready for review. 
This is to trigger a fresh CI run (as we don't run CI against draft PRs) and ensure the PR is up to date before being reviewed and merged.  
If the label `CI/run-draft` is present, it will not rebase as CI will have been run on pushes to the branch. 
The rebase label is added as part of the action to give visibility to PR owners and reviewers this has taken place.
This change has been deployed to:
=> Add rebase when PRs move from draft to ready for review

CHANGELOG_DESKTOP.md
=> [Desktop] Release notes for 1.34.x

CHANGELOG_ANDROID.md
=> Release notes for `1.38.x - Release`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.38.x Release #6

CHANGELOG_ANDROID.md
=> Release notes for `1.39.x - Release`

CHANGELOG_DESKTOP.md
=> Desktop release notes for `1.40.x - Release`

CHANGELOG_ANDROID.md, CHANGELOG_DESKTOP.md
Resolves https://github.com/brave/brave-browser/issues/29261
=> Release notes for `1.49.x - Release #4`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/29547
N/A
=> Release notes for `1.50.x - Release`

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.51.x

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/30294
N/A
=> Release notes for `1.51.x - Release`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/milestone/390
=> Release notes for `1.56.x - Release`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/32264
N/A
=> Release notes for `1.57.x - Release`

lib/logging.js, package-lock.json, package.json
`log-update` was only required for `updateStatus` in `logging.js`, but that function is not used anywhere and can be safely removed.
`package-lock.json` goes from 525 lines to just 125.
=> Remove unused `log-update` dependency

.github/ISSUE_TEMPLATE/ios.md
This simply adds an iOS issue template since we're going to start logging more iOS issues here in the future
=> Add iOS issue template

README.md
This adds info about building iOS after it has been migrated into brave-core and fixes one of the outdated links about npm config
=> Update README to add info on iOS builds

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.62.x Release #5

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/37661
N/A
=> Release notes for `1.64.x - Release #3`

CHANGELOG_iOS.md
Didn't create issue as it's a quick fix to change to order of the releases.
N/A
=> Changlog fix - changing to correct order

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/37747
N/A
=> Add Release Notes for iOS Release 1.65

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/37706
N/A
=> Release notes for `1.65.x - Release`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/38628
N/A
=> Release notes for `1.66.x - Release`

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/39067
N/A
=> Android Release Notes for 1.67.x - Release #2

CHANGELOG_iOS.md
Resolves [#38470](https://github.com/brave/brave-browser/issues/38470)
N/A
=> Add Release Notes for iOS Release 1.66.113

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/40178
N/A
=> Android release notes for 1.68.x - Release #3

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/39536
N/A
=> Add Release Notes for iOS Release 1.67

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.71.x Release

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/41709
N/A
=> Android release notes for 1.71.x - Release

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/41647
N/A
=> Add Release Notes for iOS Release 1.69.170

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.73.x Release

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/42214
N/A
=> Add Release Notes for iOS Release 1.71.125

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/42712
N/A
=> Add Release Notes for iOS Release 1.73.97

package-lock.json, package.json
Simple change that 
1. defines allowed node versions in `package.json`
2. enforce this in`.npmrc`
Resolves brave/brave-browser#42911
=> define acceptable node versions, and enforce at install time

CHANGELOG_DESKTOP.md
=> Desktop Release Notes for 1.74.x Release

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/43324
N/A
=> Android release notes for 1.74.x - Release

CHANGELOG_iOS.md
Resolves https://github.com/brave/brave-browser/issues/43403
N/A
=> Add Release Notes for iOS Release 1.74

CHANGELOG_ANDROID.md
Resolves https://github.com/brave/brave-browser/issues/44444
N/A
=> Android release notes for 1.76.x - Release
